### PR TITLE
supernova: reserve enough size for synthdefs

### LINKED ISSUE #3196: supernova: crash on number of synth arguments/controls
Hello,
I recently built SC with supernova on macOS (10.12.6). It turns out that Supernova crashes when number of arguments or controls exceeds certain number. 
This happens on current develop build (as of 2017-09-21), but _did not_ occur on develop build from march 2017.
Reproducer:
```supercollider
(
Server.supernova;
s.boot
)

//works
(
SynthDef(\multich, {
	Out.kr(0, DC.ar(0) * \someArg.kr(34.collect({|i| i })));
}).add
)
x = Synth(\multich);
x.free;

//crashes
(
SynthDef(\multich, {
	Out.kr(0, DC.ar(0) * \someArg.kr(35.collect({|i| i })));
}).add
)
x = Synth(\multich);
x.free;

//works
(
SynthDef(\multich, {arg outbus = 0;
	Out.kr(outbus, DC.ar(0) * \someArg.kr(31.collect({|i| i })));
}).add
)
x = Synth(\multich);
x.free;

//crashes
(
SynthDef(\multich, {arg outbus = 0;
	Out.kr(outbus, DC.ar(0) * \someArg.kr(32.collect({|i| i })));
}).add
)
x = Synth(\multich);
x.free;

//for comparison
//works
(
SynthDef(\multich, {
	Out.kr(0, DC.ar(0) * 35.collect({|i| i }));
}).add
)
x = Synth(\multich);
x.free;

//works as well
(
SynthDef(\multich, {arg outbus = 0;
	Out.kr(outbus, DC.ar(0) * 32.collect({|i| i }));
}).add
)
x = Synth(\multich);
x.free; 
```
Here is part of macOS crash report:
```
Thread 10 Crashed:
0   supernova                     	0x0000000108fa9fac malloc_ex + 652 (tlsf.c:757)
1   supernova                     	0x0000000108f751f9 nova::dsp_thread_queue<nova::dsp_queue_node<nova::rt_pool_allocator<void*> >, nova::rt_pool_allocator<void*> >::dsp_thread_queue(unsigned long, bool) + 89 (memory_pool.hpp:68)
2   supernova                     	0x0000000108f7420f nova::node_graph::generate_dsp_queue() + 63 (dependency_graph_generator.hpp:39)
3   supernova                     	0x0000000108f7a3e1 nova::nova_server::rebuild_dsp_queue() + 33 (server.cpp:219)
4   supernova                     	0x0000000108f285b1 nova::nova_server::tick() + 225 (server.hpp:243)
5   supernova                     	0x0000000108f2590a nova::realtime_engine_functor::run_tick() + 202 (server.hpp:284)
6   supernova                     	0x0000000108f2540b nova::portaudio_backend<nova::realtime_engine_functor, float, false>::perform(void const*, void*, unsigned long, PaStreamCallbackTimeInfo const*, unsigned long) + 235 (portaudio_backend.hpp:315)
7   libportaudio.2.dylib          	0x000000010938650b AdaptingProcess + 938
8   libportaudio.2.dylib          	0x000000010938ad6b AudioIOProc + 972
9   com.apple.audio.units.Components	0x000000010e05aef5 AUInputElement::PullInput(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 185
10  com.apple.audio.units.Components	0x000000010df518a8 AUInputFormatConverter2::InputProc(OpaqueAudioConverter*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription**, void*) + 196
11  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f92f56b AudioConverterChain::CallInputProc(unsigned int) + 415
12  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f92f2c8 AudioConverterChain::FillBufferFromInputProc(unsigned int*, CABufferList*) + 130
13  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f92f22c BufferedAudioConverter::GetInputBytes(unsigned int, unsigned int&, CABufferList const*&) + 178
14  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f92f0f0 CBRConverter::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) + 106
15  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f92272d BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 281
16  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f9229f1 AudioConverterChain::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) + 99
17  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f92272d BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 281
18  com.apple.audio.toolbox.AudioToolbox	0x00007fff9f9221fe AudioConverterFillComplexBuffer + 282
19  com.apple.audio.units.Components	0x000000010df5135f AUInputFormatConverter2::PullAndConvertInput(AudioTimeStamp const&, unsigned int&, AudioBufferList&, AudioStreamPacketDescription*, bool&) + 107
20  com.apple.audio.units.Components	0x000000010df511a8 AUConverterBase::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 580
21  com.apple.audio.units.Components	0x000000010e05e084 AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 154
22  com.apple.audio.units.Components	0x000000010e05dd84 AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 504
23  com.apple.audio.units.Components	0x000000010df542de AUHAL::AUIOProc(unsigned int, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) + 1814
24  com.grame.JackRouter          	0x000000010a874355 JackRouterDevice::Process(unsigned int, void*) + 1477
25  libjack.0.dylib               	0x000000010a8b947f Jack::JackClient::Execute() + 319
26  libjack.0.dylib               	0x000000010a8c78de Jack::JackPosixThread::ThreadHandler(void*) + 158
27  libsystem_pthread.dylib       	0x00007fffb64c693b _pthread_body + 180
28  libsystem_pthread.dylib       	0x00007fffb64c6887 _pthread_start + 286
29  libsystem_pthread.dylib       	0x00007fffb64c608d thread_start + 13
```

### PR DESCRIPTION
**Pull request by brianlheim**
In `sc_synthdef::prepare(void)`, the memory requirement for a sc_synth structure was underreported because it did not change with #3063. As a result, there was memory corruption. This commit both fixes the issue and adds clarifying comments to the calculations.

Fixes #3196, and helps #3266 as it applies to supernova. Tested on macOS 10.13.

cc @dyfer, @samaaron. Definitely doesn't change anything on sonic pi w/ scsynth.

### CODE REVIEW

File: server/supernova/sc/sc_synthdef.cpp [hunk 1]
```diff
@@ -381,8 +381,12 @@ void sc_synthdef::prepare(void)
     memory_requirement_ += (graph.size() + calc_unit_indices.size() + 1) * sizeof(Unit*); // reserves space for units (one more to allor prefetching)
 
     // memory that is required to fill the sc_synth data structure
-    const size_t ctor_alloc_size = parameter_count() * (sizeof(float) + sizeof(int) + sizeof(float*))
-                                 + constants.size() * sizeof(Wire);
+    // see SC_Graph.h for corresponding data structure
+    // mControls, mControlRates, mAudioBusOffset, mMapControls
+    const size_t param_alloc_size = parameter_count() * (sizeof(float) + sizeof(int) + sizeof(int32) + sizeof(float*));
```
Comment (vivid-synth) [inline server/supernova/sc/sc_synthdef.cpp]: This is a really good find!(!) I worry that we may forget about this in the future, too - is there somewhere we can document this sort of thing?

Comment (brianlheim) [reply server/supernova/sc/sc_synthdef.cpp]: @vivid-synth are the notes around the related code not enough? Where else could I document it? Currently AFAIK (and it seems like I'm involved in most of these conversations), there is no real documentation of these internals. I would be happy to write more verbose in-source comments if you think that's a good idea. I have done some work on getting Doxygen hooked up with our CI to automate online docs,
 and I was envisioning using that at some point in the future when it actually becomes worthwhile to direct people there. (http://www.brianlheim.com/supercollider/)

**Comment by brianlheim** [comment]
Also cc @telephon @jamshark70, you might want to give this some real-world testing to see if it all still works as expected (on Supernova).

File: server/supernova/sc/sc_synthdef.cpp (hunk 1 above)
Comment (vivid-synth) [reply server/supernova/sc/sc_synthdef.cpp]: Oh I missed that you've got docs on the ```.h``` and ```.cpp``` files too, nice 👍
