### PR TITLE
File.mkdir now throws an error

### LINKED ISSUE #3635: classlib: File.mkdir should fail on failure
As pointed out in #3633, `File:*mkdir` just prints a warning if it fails to complete. This makes checking for failure impossible. It should instead fail in some helpful way, like internally throwing an exception or returning a nonzero error code.

### PR DESCRIPTION
**Pull request by jamshark70**
Fixes #3635.

Per https://www.boost.org/doc/libs/1_49_0/libs/filesystem/v3/doc/reference.html#Error-reporting, all that is necessary to get an error to be thrown is to remove the error_code argument from the call to `bfs::create_directories()`. On success, it drops through to `return errNone`; on failure, a C++ exception is raised, caught, and passed along to a sclang PrimitiveFailedError.

Test:

```
File.mkdir("/usr/oh-no-you-cant");

ERROR: Primitive '_FileMkDir' failed.
caught exception 'boost::filesystem::create_directory: Permission denied: "/usr/oh-no-you-cant"' in primitive in method Meta_File:mkdir
```

Also, I added a short section to the File documentation about error handling for the boost functions.

### CODE REVIEW

File: lang/LangPrimSource/PyrFilePrim.cpp [hunk 1]
```diff
@@ -162,11 +162,8 @@ int prFileMkDir(struct VMGlobals * g, int numArgsPushed)
 	if (error != errNone)
 		return error;
 
-	boost::system::error_code error_code;
 	const bfs::path& p = SC_Codecvt::utf8_str_to_path(filename);
-	bfs::create_directories(p, error_code);
-	if (error_code)
-		postfl("Warning: %s (\"%s\")\n", error_code.message().c_str(), p.c_str());
+	bfs::create_directories(p);
```
Comment (brianlheim) [inline lang/LangPrimSource/PyrFilePrim.cpp]: per docs this function also returns a boolean indicating whether or not a new directory was created as a result of this call. It would be useful to return that as well, no?

File: HelpSource/Classes/File.schelp [hunk 2]
```diff
@@ -111,6 +111,27 @@ method::mtime
...
+The methods link::Classes/Function#-try:: and link::Classes/Function#-protect:: can detect and handle these errors. See link::Guides/Understanding-Errors:: for details.
+
+Currently, link::Classes/File#*copy::, link::Classes/File#*fileSize::, link::Classes/File#*mkdir::, link::Classes/File#*mtime::, and link::Classes/File#*type:: throw errors upon failure.
+
+link::Classes/File#*delete:: does not throw an error, but instead returns a Boolean:
+
+list::
+## code::true:: -- You can assume that the path no longer exists. (Either it existed and was deleted, or it didn't exist and it still doesn't exist.)
+## code::false:: -- The file could not be deleted (probably a permissions error). Your code should assume that the path still exists.
+::
```
Comment (brianlheim) [inline HelpSource/Classes/File.schelp]: Why split this information? i.e. shouldn't it be placed within each individual function's documentation? This is out of style with the rest of documentation.

File: HelpSource/Classes/File.schelp [hunk 3]
```diff
@@ -111,6 +111,27 @@ method::mtime
...
 
+subsection:: Error handling in filesystem utilities
+
+If one of the above file system primitives fails, in most cases, a PrimitiveFailedError object will be thrown:
+
+code::
+File.mkdir("/usr/oh-no-you-cant");
+
+ERROR: Primitive '_FileMkDir' failed.
+caught exception 'boost::filesystem::create_directory: Permission denied: "/usr/oh-no-you-cant"' in primitive in method Meta_File:mkdir
```
Comment (brianlheim) [inline HelpSource/Classes/File.schelp]: this gets sc syntax highlighting when it shouldn't; you can use a `teletype::` block instead to avoid that

File: lang/LangPrimSource/PyrFilePrim.cpp (hunk 1 above)
Comment (jamshark70) [reply lang/LangPrimSource/PyrFilePrim.cpp]: Not exactly. I haven't changed the function being called: it is still `create_directories()`, not `create_directory()`. Doc says:

> Returns: The value of `!exists(p)` prior to the establishment of the postcondition.

In other words, it distinguishes between returning successfully after creating a directory that didn't exist before, vs returning successfully with no action (because the directory already existed).

If users really need to know, they can already check `File.exists` before calling `File.mkdir` -- so it would be the difference between:

```
if(File.exists(dir).not) {
	try {
		File.mkdir(dir)
	} { |error|
		error.reportError
	}
} {
	"% already existed, no need to re-create\n".postf(dir.basename)
};

// vs
try {
	if(File.mkdir(dir).not) {
		"% already existed, no need to re-create\n".postf(dir.basename)
	}
} { |error|
	error.reportError
}
```

... the latter of which is admittedly slightly less verbose, but also seems to me less clear. Burying the crucial action in an `if` condition is not exactly good for legibility.

I can't see any other benefit. All other cases I can imagine where the directory would not be created end with an error being thrown.

Comment (jamshark70) [reply lang/LangPrimSource/PyrFilePrim.cpp]: Well, I tried this:

```
int prFileMkDir(struct VMGlobals * g, int numArgsPushed)
{
	PyrSlot *b = g->sp;
	char filename[PATH_MAX];

	int error = slotStrVal(b, filename, PATH_MAX);
	if (error != errNone)
		return error;

	const bfs::path& p = SC_Codecvt::utf8_str_to_path(filename);
	bool result = bfs::create_directories(p);

	SetBool(g->sp, result);
	return errNone;
}
```

But `File.mkdir(aString)` still returns the File class, not the thing that I supposedly `SetBool`-ed.

I'm out of time. Chinese universities' spring semester is a lot later than American ones' -- I still have two exams to arrange and a pile of audio files to grade. Feel free to push a working change to get the Boolean result -- I don't object to the idea as such, but I'm not going to do any more on this myself.

File: HelpSource/Classes/File.schelp (hunk 2 above)
Comment (jamshark70) [reply HelpSource/Classes/File.schelp]: Both helpfile fixes done (will reply only this once).

File: lang/LangPrimSource/PyrFilePrim.cpp (hunk 1 above)
Comment (jamshark70) [reply lang/LangPrimSource/PyrFilePrim.cpp]: OK. I realized overnight that I could check the Writing Primitives documentation and find out where to set the return value. Done.

Note that I'm copying the style `PyrSlot *a = g->sp - 1, *b = g->sp;` from the other file primitives. If this is stylistically incorrect, that would involve changes outside the scope of this PR. So I think I've addressed all the concerns now.

**Comment by brianlheim** [comment]
Note - this is an API change, anyone who was doing something of the form `File.mkdir(a).mkdir(b)` will have to change.

**Comment by jamshark70** [comment]
> anyone who was doing something of the form File.mkdir(a).mkdir(b) will have to change.

Ah... I didn't think of that. In that case, I'll suggest reverting that commit.

> this is the only (sane) way to get this information back to the user. It matches behavior with delete

Not exactly.

In `delete`, a `false` return is the only way to know that the method did not leave the system in the expected state: You expected the file to be gone, and it isn't gone.

`mkdir`'s false doesn't indicate anything about the system's final state, but rather about its initial state: `false` means "you have your directory, but I didn't do any work to put it there." `mkdir` reports failure by throwing an error.

The return value from `delete` is necessary. The return value from `mkdir` is... a/ who cares if the directory existed before the call or not? (only a tiny percent of use cases, I'd guess) and b/ if you have one of those rare cases where it's crucial to be sure the directory is brand-new = empty, you had better not rely on a single Boolean from this method to be sure of it and c/ if you really need to know, you can check `File.exists` first.

IMO the return value from `mkdir` gives information of limited value, which can be obtained by other means. It's not needed.

**Comment by brianlheim** [comment]
> if you really need to know, you can check File.exists first.

As I've noted several times already, filesystem operations can happen from other processes and threads between any two calls, so any code that operates on the filesystem is only correct if it makes no assumptions about consistency between calls. That's why having this return value is useful; it provides the only 100% reliable information about whether a directory was created.

> if you have one of those rare cases where it's crucial to be sure the directory is brand-new = empty, you had better not rely on a single Boolean from this method to be sure of it

I don't understand this comment... that single boolean does in fact give you that information. That's the whole point.

> IMO the return value from mkdir gives information of limited value, which can be obtained by other means. It's not needed.

It can't be obtained reliably any other way.

**Comment by brianlheim** [comment]
But, in any case, if you are really dead-set on keeping compatibility here we can merge this without the return value change and make an audit of the `File` utilities at some later date. Personally I am just worried that users will rely on the workaround you suggested above, which is fundamentally incorrect.

**Comment by jamshark70** [comment]
> As I've noted several times already, filesystem operations can happen from other processes and threads between any two calls, so any code that operates on the filesystem is only correct if it makes no assumptions about consistency between calls.

I would be more convinced if the probability of interference from outside threads were high. But it seems to me that this must be vanishingly small.

- sclang is non-preemptive: If you do `File.exists` and then `File.mkdir` with no intervening `yield`, it's guaranteed that no other sclang operation can occur in the interim.

- Therefore the only possible interference is that another process happens to be mucking about at exactly the same path, in exactly the gap of microseconds between sclang method calls -- with no knowledge of path strings in other processes! I'll take a rough guess that the probability is several orders of magnitude smaller than 1%.

You're correct that it's not impossible. But I would have to guess that the probability of code breakage is likely to be larger. (Or, another way to consider the risk is: It's also possible that some other thread could `rmdir` your new directory before you were able to use it.)

Also, what are the cases to be distinguished?

- After `mkdir`, the location exists or doesn't exist: "doesn't exist" = error was thrown.

- After `mkdir`, the location is new or previously existing: Who cares? (That's a serious question. This is the only thing that the Boolean return tells you. In the overwhelming majority of cases, "old or new" simply doesn't matter.)

- After `mkdir`, the location is empty or not: Now *that* is useful to know. If it's new (`true` return), then it's guaranteed to be empty. If previously existing, it may or may not be empty. If you truly need an empty directory, you cannot do only `File.mkdir` anyway. You must either remove the old location and re-create, or delete the old contents yourself. (And even then, accepting the logic that other threads might be doing filesystem operations, by the time you get around to writing a file, you can't be sure the directory is still empty...)

At the end of the day, whether we return the Boolean or not is not very important -- and if I really objected strenuously, I wouldn't have added the commit. BUT... I am not certain about the Boolean return is critically useful. "Who cares?" is genuinely not a sarcastic question here. I look at the use cases and I can't think of a good reason why it matters if the directory is brand-new or not. If there is such a case, then it's an honest answer to "who cares" and I'd be happy to hear it.

**Comment by brianlheim** [comment]
> I would be more convinced if the probability of interference from outside threads were high. But it seems to me that this must be vanishingly small.

I don't know what to tell you, there are a lot of processes that modify the filesystem all the time and well designed code needs to be robust to that fact. Any sclang code that launches async processes, or launches async callbacks, or that needs to interface with other applications, will have to deal with this reality. We just had a user on the ML ask about interfacing sclang with R for data collection and analysis. In that kind of environment sclang may be called from a script and be operating alongside other processes modifying the same directory.

The answer to "who cares?" is "a user you haven't met yet."

Anyway that is not the point of this conversation. I've also proposed an alternative way of moving this PR forward so if you're still not convinced please just go with that.

**Comment by brianlheim** [comment]
OK, thanks for the discussion!

> I maintain that you're going to need a lot more than just this Boolean to be sure it's safe.

I think the point I'm trying to make is that if it comes down to having to report on or debug concurrent filesystem code, there's no substitute for atomicity.

> What is a use case where it makes a difference whether it previously existed or is newly created?

I think there's been at least one case within this project where, as a result of a larger request, some code wanted to report to the user whether or not a new directory had been created. Another practical case where this might matter is if some script wanted to attempt to return the filesystem back to the state it was in before it ran.
