### PR TITLE
sclang: fix kw and inlined method crash

### LINKED ISSUE #4474: 'loop' message with a keyword argument crashes sclang
## Environment

* SuperCollider version: 3.10
* Operating system: Linux (doesn't matter)

## Steps to reproduce

Two crashes with very similar input code. 

It appears that the compiler is generating some sort of incorrect data structure for the `loop` special method selector, if the receiver is not a function (i.e., not bytecode-optimized) *and* there is a keyword argument.

- Crash 1: The interpreter crashes when it tries to execute this wrong data structure.
- Crash 2: The bytecode printer crashes when it tries to dumpByteCodes for it.

```
$ gdb sclang
(gdb) run
...
sc3> a = 100.loop(xyz: 1);

Thread 1 "sclang" received signal SIGSEGV, Segmentation fault.
0x00005555555c3341 in Interpret (g=g@entry=0x555555b16a80 <gVMGlobals>)
    at /home/dlm/share/supercollider/lang/LangSource/PyrInterpreter3.cpp:822
822	            selector = slotRawSymbol(&slotRawObject(&g->block->selectors)->slots[op3]);

(gdb) where
#0  0x00005555555c3341 in Interpret(VMGlobals*) (g=g@entry=0x555555b16a80 <gVMGlobals>)
    at /home/dlm/share/supercollider/lang/LangSource/PyrInterpreter3.cpp:822
#1  0x0000555555680cf8 in runInterpreter(VMGlobals*, PyrSymbol*, int) (g=g@entry=0x555555b16a80 <gVMGlobals>, selector=selector@entry=0x555555ce4948, numArgsPushed=numArgsPushed@entry=1)
    at /home/dlm/share/supercollider/lang/LangSource/PyrInterpreter3.cpp:127
#2  0x0000555555685497 in runLibrary(PyrSymbol*) (selector=selector@entry=0x555555ce4948) at /home/dlm/share/supercollider/lang/LangSource/PyrLexer.cpp:2269
#3  0x00005555556bb63e in SC_LanguageClient::runLibrary(PyrSymbol*) (this=<optimized out>, symbol=0x555555ce4948)
    at /home/dlm/share/supercollider/lang/LangSource/SC_LanguageClient.cpp:161
#4  0x00005555555c7327 in SC_TerminalClient::interpretCmdLine(char const*, unsigned long, bool) (this=0x555555becb90, cmdLine=<optimized out>, size=<optimized out>, silent=<optimized out>)
    at /home/dlm/share/supercollider/lang/LangSource/SC_TerminalClient.cpp:310
#5  0x00005555555c9630 in SC_TerminalClient::interpretInput() (this=0x555555becb90) at /home/dlm/share/supercollider/lang/LangSource/SC_TerminalClient.cpp:325
#6  0x00005555555cc58c in boost::_mfi::mf0<void, SC_TerminalClient>::operator()(SC_TerminalClient*) const (p=0x555555becb90, this=<optimized out>)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/bind/mem_fn_template.hpp:49
#7  0x00005555555cc58c in boost::_bi::list1<boost::_bi::value<SC_TerminalClient*---Type <return> to continue, or q <return> to quit---
> >::operator()<boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, SC_TerminalClient>&, boost::_bi::list0&, int) (a=<synthetic pointer>..., f=<synthetic pointer>..., this=<synthetic pointer>)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/bind/bind.hpp:259
#8  0x00005555555cc58c in boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >::operator()() (this=<synthetic pointer>)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/bind/bind.hpp:1294
#9  0x00005555555cc58c in boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&, ...) (function=<synthetic pointer>...)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/handler_invoke_hook.hpp:69
#10 0x00005555555cc58c in boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >, boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost---Type <return> to continue, or q <return> to quit---
::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&, boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&) (context=<synthetic pointer>..., function=<synthetic pointer>...)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/handler_invoke_helpers.hpp:37
#11 0x00005555555cc58c in boost::asio::detail::handler_work<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >, boost::asio::system_executor>::complete<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&, boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&) (this=<synthetic pointer>, handler=<synthetic pointer>..., function=<synthetic pointer>...)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/handler_work.hpp:82
#12 0x00005555555cc58c in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x555555bf9320, base=0x7fff18053420)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/---Type <return> to continue, or q <return> to quit---
completion_handler.hpp:70
#13 0x00005555555d5d84 in boost::asio::detail::scheduler_operation::complete(void*, boost::system::error_code const&, unsigned long) (bytes_transferred=<optimized out>, ec=..., owner=0x555555bf9320, this=0x7fff18053420)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/scheduler_operation.hpp:40
#14 0x00005555555d5d84 in boost::asio::detail::scheduler::do_poll_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) (ec=..., this_thread=..., lock=..., this=0x555555bf9320)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/impl/scheduler.ipp:535
#15 0x00005555555d5d84 in boost::asio::detail::scheduler::poll(boost::system::error_code&) (ec=..., this=0x555555bf9320)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/impl/scheduler.ipp:221
#16 0x00005555555d5d84 in boost::asio::io_context::poll() (this=<optimized out>) at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/impl/io_context.ipp:92
#17 0x00005555555d5d84 in QtCollider::LangClient::customEvent(QEvent*) (this=<optimized out>, e=<optimized out>)
    at /home/dlm/share/supercollider/QtCollider/LanguageClient.cpp:73
#18 0x00007ffff68f1823 in QObject::event(QEvent*) ()
---Type <return> to continue, or q <return> to quit---
    at /opt/qt511/lib/libQt5Core.so.5
#19 0x00007ffff7306c4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /opt/qt511/lib/libQt5Widgets.so.5
#20 0x00007ffff730e2c7 in QApplication::notify(QObject*, QEvent*) ()
    at /opt/qt511/lib/libQt5Widgets.so.5
#21 0x00007ffff68c3ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /opt/qt511/lib/libQt5Core.so.5
#22 0x00007ffff68c66de in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /opt/qt511/lib/libQt5Core.so.5
#23 0x00007ffff691b263 in  () at /opt/qt511/lib/libQt5Core.so.5
#24 0x00007fffebd8e317 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007fffebd8e550 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007fffebd8e5dc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff691a86f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/qt511/lib/libQt5Core.so.5
#28 0x00007fffe3cb3f41 in  ()
    at /opt/qt511/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#29 0x00007ffff68c1e6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/qt511/lib/libQt5Core.so.5
#30 0x00007ffff68caf74 in QCoreApplication::exec() ()
    at /opt/qt511/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#31 0x00005555555d5939 in QtCollider::LangClient::commandLoop() (this=0x555555becb80) at /home/dlm/share/supercollider/QtCollider/LanguageClient.cpp:40
#32 0x00005555555c9fb9 in SC_TerminalClient::run(int, char**) (this=0x555555becb90, argc=<optimized out>, argv=<optimized out>)
    at /home/dlm/share/supercollider/lang/LangSource/SC_TerminalClient.cpp:273
#33 0x00005555555b6118 in main(int, char**) (argc=1, argv=0x7fffffffde18)
    at /home/dlm/share/supercollider/lang/LangSource/cmdLineFuncs.cpp:27
```

And:

```
sc3> { x.loop(xyz: 1) }.def.dumpByteCodes
BYTECODES: (10)
  0   01 19    PushInstVarX 'x'
  2   40       PushLiteral Symbol 'xyz'
  3   64       PushSpecialValue 1
  4   B0       TailCallReturnFromFunction

Thread 1 "sclang" received signal SIGSEGV, Segmentation fault.
dumpOneByteCode (theBlock=theBlock@entry=0x55555cb46c98, 
    theClass=theClass@entry=0x555555cf1440, 
    ip=0x55555d851dd9 <incomplete sequence \362>)
    at /home/dlm/share/supercollider/lang/LangSource/dumpByteCodes.cpp:163
163	        post(" %02X %02X %02X SendMsgX '%s'\n", op2, op3, op4, selector->name);
(gdb) where
#0  0x00005555556c34e1 in dumpOneByteCode(PyrBlock*, PyrClass*, unsigned char*) (theBlock=theBlock@entry=0x55555cb46c98, theClass=theClass@entry=0x555555cf1440, ip=0x55555d851dd9 <incomplete sequence \362>)
    at /home/dlm/share/supercollider/lang/LangSource/dumpByteCodes.cpp:163
#1  0x00005555556c3b8b in dumpByteCodes(PyrBlock*) (theBlock=0x55555cb46c98)
    at /home/dlm/share/supercollider/lang/LangSource/dumpByteCodes.cpp:1221
#2  0x00005555555dcff1 in prDumpByteCodes(VMGlobals*, int) (g=<optimized out>, numArgsPushed=<optimized out>)
    at /home/dlm/share/supercollider/lang/LangPrimSource/PyrPrimitive.cpp:2574
#3  0x00005555555e6476 in doPrimitive(VMGlobals*, PyrMethod*, int) (g=0x555555b16a80 <gVMGlobals>, meth=0x55555ae68740, numArgsPushed=<optimized out>)
    at /home/dlm/share/supercollider/lang/LangPrimSource/PyrPrimitive.cpp:3862
#4  0x00005555555bd3e2 in Interpret(VMGlobals*) (g=0x55555583a928, 
    g@entry=0x555555b16a80 <gVMGlobals>)
    at /home/dlm/share/supercollider/lang/LangSource/PyrInterpreter3.cpp:3034
#5  0x0000555555680cf8 in runInterpreter(VMGlobals*, PyrSymbol*, int) (g=g@entry=0x555555b16a80 <gVMGlobals>, selector=selector@entry=0x555555ce4948, numArgsPushed=numArgsPushed@entry=1)
    at /home/dlm/share/supercollider/lang/LangSource/PyrInterpreter3.cpp:127
#6  0x0000555555685497 in runLibrary(PyrSymbol*) (selector=selector@entry=0x555555ce4948) at /home/dlm/share/supercollider/lang/LangSource/PyrLexer.cpp:2269
#7  0x00005555556bb63e in SC_LanguageClient::runLibrary(PyrSymbol*) (this=<optimized out>, symbol=0x555555ce4948)
---Type <return> to continue, or q <return> to quit---
    at /home/dlm/share/supercollider/lang/LangSource/SC_LanguageClient.cpp:161
#8  0x00005555555c7327 in SC_TerminalClient::interpretCmdLine(char const*, unsigned long, bool) (this=0x555555becb90, cmdLine=<optimized out>, size=<optimized out>, silent=<optimized out>)
    at /home/dlm/share/supercollider/lang/LangSource/SC_TerminalClient.cpp:310
#9  0x00005555555c9630 in SC_TerminalClient::interpretInput() (this=0x555555becb90) at /home/dlm/share/supercollider/lang/LangSource/SC_TerminalClient.cpp:325
#10 0x00005555555cc58c in boost::_mfi::mf0<void, SC_TerminalClient>::operator()(SC_TerminalClient*) const (p=0x555555becb90, this=<optimized out>)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/bind/mem_fn_template.hpp:49
#11 0x00005555555cc58c in boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> >::operator()<boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, SC_TerminalClient>&, boost::_bi::list0&, int) (a=<synthetic pointer>..., f=<synthetic pointer>..., this=<synthetic pointer>)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/bind/bind.hpp:259
#12 0x00005555555cc58c in boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >::operator()() (this=<synthetic pointer>)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/bind/bind.hpp:1294
---Type <return> to continue, or q <return> to quit---
#13 0x00005555555cc58c in boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&, ...) (function=<synthetic pointer>...)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/handler_invoke_hook.hpp:69
#14 0x00005555555cc58c in boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >, boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&, boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&) (context=<synthetic pointer>..., function=<synthetic pointer>...)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/handler_invoke_helpers.hpp:37
#15 0x00005555555cc58c in boost::asio::detail::handler_work<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >, boost::asio::system_executor>::complete<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >(boost::_bi::bind_t<void, boost::_mfi::mf0---Type <return> to continue, or q <return> to quit---
<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&, boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > >&) (this=<synthetic pointer>, handler=<synthetic pointer>..., function=<synthetic pointer>...)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/handler_work.hpp:82
#16 0x00005555555cc58c in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf0<void, SC_TerminalClient>, boost::_bi::list1<boost::_bi::value<SC_TerminalClient*> > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x555555bf9320, base=0x7fff0c013a80)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/completion_handler.hpp:70
#17 0x00005555555d5d84 in boost::asio::detail::scheduler_operation::complete(void*, boost::system::error_code const&, unsigned long) (bytes_transferred=<optimized out>, ec=..., owner=0x555555bf9320, this=0x7fff0c013a80)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/scheduler_operation.hpp:40
#18 0x00005555555d5d84 in boost::asio::detail::scheduler::do_poll_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) (ec=..., this_thread=..., lock=..., this=0x555555bf9320)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/---Type <return> to continue, or q <return> to quit---
impl/scheduler.ipp:535
#19 0x00005555555d5d84 in boost::asio::detail::scheduler::poll(boost::system::error_code&) (ec=..., this=0x555555bf9320)
    at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/detail/impl/scheduler.ipp:221
#20 0x00005555555d5d84 in boost::asio::io_context::poll() (this=<optimized out>) at /home/dlm/share/supercollider/external_libraries/boost/boost/asio/impl/io_context.ipp:92
#21 0x00005555555d5d84 in QtCollider::LangClient::customEvent(QEvent*) (this=<optimized out>, e=<optimized out>)
    at /home/dlm/share/supercollider/QtCollider/LanguageClient.cpp:73
#22 0x00007ffff68f1823 in QObject::event(QEvent*) ()
    at /opt/qt511/lib/libQt5Core.so.5
#23 0x00007ffff7306c4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /opt/qt511/lib/libQt5Widgets.so.5
#24 0x00007ffff730e2c7 in QApplication::notify(QObject*, QEvent*) ()
    at /opt/qt511/lib/libQt5Widgets.so.5
#25 0x00007ffff68c3ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /opt/qt511/lib/libQt5Core.so.5
#26 0x00007ffff68c66de in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /opt/qt511/lib/libQt5Core.so.5
#27 0x00007ffff691b263 in  () at /opt/qt511/lib/libQt5Core.so.5
#28 0x00007fffebd8e317 in g_main_context_dispatch ()
---Type <return> to continue, or q <return> to quit---
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fffebd8e550 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007fffebd8e5dc in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff691a86f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/qt511/lib/libQt5Core.so.5
#32 0x00007fffe3cb3f41 in  ()
    at /opt/qt511/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#33 0x00007ffff68c1e6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/qt511/lib/libQt5Core.so.5
#34 0x00007ffff68caf74 in QCoreApplication::exec() ()
    at /opt/qt511/lib/libQt5Core.so.5
#35 0x00005555555d5939 in QtCollider::LangClient::commandLoop() (this=0x555555becb80) at /home/dlm/share/supercollider/QtCollider/LanguageClient.cpp:40
#36 0x00005555555c9fb9 in SC_TerminalClient::run(int, char**) (this=0x555555becb90, argc=<optimized out>, argv=<optimized out>)
    at /home/dlm/share/supercollider/lang/LangSource/SC_TerminalClient.cpp:273
#37 0x00005555555b6118 in main(int, char**) (argc=1, argv=0x7fffffffde18)
    at /home/dlm/share/supercollider/lang/LangSource/cmdLineFuncs.cpp:27
```

### LINKED ISSUE #5429: if crashes using keyword arguments
hello all

as in subject, the expression below crashes ("Interpreter has crashed or stopped forcefully. [Exit code: 11]")

```supercollider
true.if({'x'}) == 'x'; // true
true.if(trueFunc: {'x'}) // crash...
```

scide suggests the keywords for if

$ sclang -version # debian testing
sclang 3.11.2 (Built from branch 'not_a_git_checkout' [na])
$ uname -a
Linux x270 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux
$

i don't have any other  versions to test on just now

best,
rohan

### PR DESCRIPTION
**Pull request by JordanHendersonMusic**
## Purpose and Motivation

Closes #4474

Closes #5429

Passing keywords to control flow no longer crashes the interpreter. It will never inline the methods though.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

### CODE REVIEW

File: lang/LangSource/PyrParseNode.cpp [hunk 1]
```diff
@@ -1880,11 +1880,8 @@ void PyrCallNode::compileCall(PyrSlot* result) {
                 SendSpecialMsgX.emit(Operands::ArgumentCount::fromRaw(numArgs + 2 * numKeyArgs),
                                      Operands::KwArgumentCount::fromRaw(numKeyArgs), Operands::Index::fromRaw(index));
                 break;
-            case selUnary:
-            case selBinary:
-                index = conjureLiteralSlotIndex((PyrParseNode*)mSelector, gCompilingBlock, &mSelector->mSlot);
-                // fall through
             default:
+                index = conjureLiteralSlotIndex((PyrParseNode*)mSelector, gCompilingBlock, &mSelector->mSlot);
```
Comment (Spacechild1) [inline lang/LangSource/PyrParseNode.cpp]: Would you mind adding a comment? Given the explicit fall through, that code must have been intentional, so it's worth explaining why it has been wrong.

In general, it would be highly appreciated if you could add some comments while you are doing sclang fixes/features. I always try to do the same when I'm working on Supernova or scsynth. The SuperCollider codebase is notoriously underdocumented and every single comment we add will help future contributors. Let's use this big opportunity while we are immersed in the code and have all that context in our head.

Comment (JordanHendersonMusic) [reply lang/LangSource/PyrParseNode.cpp]: > Given the explicit fall through, that code must have been intentional, so it's worth explaining why it has been wrong.

It is always wrong to pass a selector index to send-message, it needs a literal slot index (a symbol). `index` is correctly set when `seltype` is normal, but not in the other cases.

The issue is the incredibly confusing out parameters of the `conjure*` functions and all their logic. They need a rewrite.

I'll add some comments, but they won't help much here unfortunately.

Comment (Spacechild1) [reply lang/LangSource/PyrParseNode.cpp]: > It is always wrong to pass a selector index to send-message, it needs a literal slot index (a symbol). index is correctly set when seltype is normal, but not in the other cases.

That would already be a helpful comment! Just to understand why we have to call `conjureLiteralSlotIndex`. Now everything makes sense to me.

Comment (JordanHendersonMusic) [reply lang/LangSource/PyrParseNode.cpp]: Okay I've revised this and figured out why the unary and binary cases where there to begin with.

What I had before of sending a normal message works in all cases, but doesn't apply the possible special message optimisation. However, you can't do this when you have a unary and binary message, because the byte codes don't exist for these with keyword arguments (particularly doesn't make sense for unary messages).  So it is the fall through that was actually incorrect. I've changed this now and added some tests.

edit: ... i just found more bugs...

Comment (JordanHendersonMusic) [reply lang/LangSource/PyrParseNode.cpp]: @Spacechild1 sorry for the back and forth, I think this is good now. 

I found this fun bug `(!?)(1, obj: 2) ` which tried to call `and` instead.

File: lang/LangSource/PyrParseNode.cpp [hunk 2]
```diff
@@ -1866,28 +1865,43 @@ void PyrCallNode::compileCall(PyrSlot* result) {
...
+                              Operands::Index::fromRaw(selectorSlotIndex));
                 break;
-            case selUnary:
-            case selBinary:
-                index = conjureLiteralSlotIndex((PyrParseNode*)mSelector, gCompilingBlock, &mSelector->mSlot);
-                // fall through
+            }
+
             default:
+                // In this case, the selector is a special one, and we can use the send speical message.
```
Comment (Spacechild1) [inline lang/LangSource/PyrParseNode.cpp]: typo in "speical".

Just a question: does "the selector is a special one" mean that the selector is supposed to be `selSpecial`, or that it is any selector other than `selNormal`, `selUnary` and `selBinary`? In the first case, it would be good to add `assert(selType == selSpecial)`.

Comment (JordanHendersonMusic) [reply lang/LangSource/PyrParseNode.cpp]: No, there are four kinds of behaviour here, normal, special, unary, and binary. That is, four different ways the index returned from `conjure...` is to be interpreted.

Normal: added selector to function def selector array.
Special: this is a known selector, refer to it by a special-selector-index, nothing has been added to the selector array.
Unary & Binary: these are known selectors, refer to them by a (unary|binary)- selector-index, nothing has been added to the selector array.

Normal requires using SendMsg(X); special, SendSpecialMsg(X); unary, SendSpecialUnaryArithMsg; binary SendSpecialBinaryMsg. 

We have more entries in the selector enum than behaviour, as we also use when we try and inline the definitions.
```c++
enum {
    selNormal,
    selSpecial,
    selUnary,
    selBinary,
    selIf,
    selWhile,
    selAnd,
    selOr,
    selCase,
    selSwitch,
    selLoop,
    selSuperNew,
    selQuestionMark,
    selDoubleQuestionMark,
    selExclamationQuestionMark,
    selNumSelectorTypes
};
```
The ones that aren't selNormal, selUnary or selBinary, have the same behaviour as special, in that they return a special-index.

Comment (Spacechild1) [reply lang/LangSource/PyrParseNode.cpp]: > We have more entries in the selector enum than behaviour, as we also use when we try and inline the definitions.

> The ones that aren't selNormal, selUnary or selBinary, have the same behaviour as special, in that they return a special-index.

That was exactly the source of my confusion. Thanks for the explanation! I guess the problem is just that I'm not really familiar with that part of sclang :)

Comment (JordanHendersonMusic) [reply lang/LangSource/PyrParseNode.cpp]: Yeah... this function is confusing — thanks for digging in and reviewing this! Like most things in this part of sclang, the readability issues are caused by incrementally adding optimisations, the core ideas are straight forward. Moss's documentation on the bytecodes, which I turned into types, is something I found very helpful.

Comment (Spacechild1) [reply lang/LangSource/PyrParseNode.cpp]: There is also a chapter about sclang internals in the SuperCollider Book but IIRC it is a bit outdated. Have you read it? It would have been great to have you as the co-author for the 2nd edition... Maybe for the 3rd edition in 10 years :-D

**Review by Spacechild1 — APPROVED** [review]

File: lang/LangSource/PyrParseNode.cpp (hunk 2 above)
Comment (JordanHendersonMusic) [reply lang/LangSource/PyrParseNode.cpp]: TBH, I never looked at it because of the paywall. 

I just had a cheeky peek and saw there is all the bytecode information there, that would have been good to know about! A lot of the rest is subtly out of date though and if the chance came about, I'd be more than happy to contribute.
