### PR TITLE
List audio devices on Windows

### LINKED ISSUE #1557: ServerOptions.inDevices not working on Linux Platform + Windows 8
The error received (using ubuntu) :

```

CALL STACK:
    MethodError:reportError   0x1ec2008
        arg this = <instance of PrimitiveFailedError>
    Nil:handleError   0x1d85798
        arg this = nil
        arg error = <instance of PrimitiveFailedError>
    Thread:handleError   0x1f98378
        arg this = <instance of Thread>
        arg error = <instance of PrimitiveFailedError>
    Object:throw   0x1d9bd38
        arg this = <instance of PrimitiveFailedError>
    Function:protect   0x1c89578
        arg this = <instance of Function>
        arg handler = <instance of Function>
        var result = <instance of PrimitiveFailedError>
    Interpreter:executeFile   0x3740eb8
        arg this = <instance of Interpreter>
        arg pathName = "simplePitchTrack.scd"
        arg args = [*0]
        var result = nil
        var saveExecutingPath = nil
    Process:interpretCmdLine   0x1c8c438
        arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive 'none' failed.
Failed.
RECEIVER: nil

```

Weirdly enough this ServerOptions.inDevices line works perfectly fine on OSX and there is no warning in the documentation that says that this property is platform specific.

Is there a different way to get a listing of the input devices on these platforms?

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

Add listing devices with PortAudio backend (by default on Windows). With this PR following commands will work on Windows:
```supercollider
ServerOptions.inDevices;
ServerOptions.outDevices;
ServerOptions.devices;
```

Fixes #1557.

RE #1557 - the issue mentions listing devices not working on Linux as well, but since we use JACK on Linux there's [no point implementing listing devices](https://github.com/supercollider/supercollider/issues/1557#issuecomment-114677077). (Maybe at some point we could consider implementing available JACK server names... but this PR is really for Windows users and PortAudio).

## Types of changes

- Documentation
- New feature

## To-do list

- [x] Code is tested
- ~~All tests are passing~~
  - there are no tests
- [x] Updated documentation
- [x] This PR is ready for review
- [x] Cleanup commit history

### CODE REVIEW

**Comment by brianlheim** [comment]
does this depend on another PR? i see a bunch of CMake changes that aren't really noted in the PR description

**Comment by brianlheim** [comment]
oh, i see now, it's because sclang now needs to link with PortAudio

File: lang/LangPrimSource/PyrPrimitive.cpp [hunk 1]
```diff
@@ -4348,11 +4348,16 @@ void initPrimitives() {
...
+#ifdef SC_AUDIO_API_COREAUDIO
     void initCoreAudioPrimitives();
     initCoreAudioPrimitives();
 #endif
 
+#ifdef SC_AUDIO_API_PORTAUDIO
+    void initPortAudioPrimitives();
+    initPortAudioPrimitives();
+#endif
+
```
Comment (brianlheim) [inline lang/LangPrimSource/PyrPrimitive.cpp]: these two paragraphs would become

```cpp
#if defined(SC_AUDIO_API_COREAUDIO) || defined(SC_AUDIO_API_PORTAUDIO)
    initAudioBackendPrimitives();
#endif
```

File: lang/LangPrimSource/SC_PortAudioPrim.cpp [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+            name = GetPaDeviceName(i);
+
+        if (!name.empty()) {
+            PyrString* string = newPyrString(g->gc, name.c_str(), 0, true);
+            SetObject(devArray->slots + j, string);
+            devArray->size++;
+            g->gc->GCWriteNew(devArray, (PyrObject*)string); // we know array is white so we can use GCWriteNew
+            j++;
+        }
+    }
```
Comment (brianlheim) [inline lang/LangPrimSource/SC_PortAudioPrim.cpp]: this function body could be written much more idiomatically. essentially, it's 3 steps:
1. collect device infos (which already contain the name of the device, btw; you don't need `GetPaDeviceName` here)
2. filter by the IN/OUT condition
3. transform filtered device infos into a PyrArray

the first step is just a `for` loop filling a `std::vector`; the second step you can write with the standard library functions [std::remove_if](https://en.cppreference.com/w/cpp/algorithm/remove) and [std::vector::erase](https://en.cppreference.com/w/cpp/container/vector/erase). you can use the size of the vector after filtering as a replacement for the variable `num` in this function body.

the third step is then also a simple `for` loop.

since device names are null-terminated `const char*`, you don't have to use an intermediary `std::string` to hold that data.

Comment (dyfer) [reply lang/LangPrimSource/SC_PortAudioPrim.cpp]: OK, I'll try to implement the the logic you suggest.
However, we do need `GetPaDeviceName` - on Windows that returns `backend name : device name` and is consistent with what the server uses.

File: lang/LangPrimSource/PyrPrimitive.cpp (hunk 1 above)
Comment (dyfer) [reply lang/LangPrimSource/PyrPrimitive.cpp]: > so, i'm thinking that to avoid code duplication it's probably best to merge `SC_CoreAudioPrim.cpp` and `SC_PortAudioPrim.cpp` into a new C++ file, `SC_AudioBackendPrim.cpp` (feel free to choose a better name, i'm not sure that one is accurate).

Below you also suggest refactoring what I wrote for PortAudio part. How would you like the combined file structured? Should CoreAudio part be also refactored?

Comment (brianlheim) [reply lang/LangPrimSource/PyrPrimitive.cpp]: no, the CoreAudio part doesn't need to be refactored, you can just stick a ifdef around it. if i've read the code right, then prListAudioDevices and initXPrimitives won't be duplicatedlike they are now

File: lang/LangPrimSource/SC_PortAudioPrim.cpp (hunk 2 above)
Comment (brianlheim) [reply lang/LangPrimSource/SC_PortAudioPrim.cpp]: ah okay, i forgot it does more than just read the name field on Windows. probably worth adding an overloading taking a PaDeviceInfo so you don't need to call PaGetDeviceInfo twice and keep around a list of indices

Comment (brianlheim) [reply lang/LangPrimSource/SC_PortAudioPrim.cpp]: an overload of GetPaDeviceName, i mean

Comment (dyfer) [reply lang/LangPrimSource/SC_PortAudioPrim.cpp]: Do you mean for GetPaDeviceName to be able to take device info on top of device index?

**Comment by dyfer** [comment]
@brianlheim I think I addressed your suggestions. How does the PortAudio section look like now?

I consciously made the change to always add the device selection file (regardless of the API), also as an attempt to make CMakeLists a little less cluttered _(very little...)_. I think the only downside is that it does change the type of error (when calling `ServerOptions.devices`) when compiled with JACK/on Linux. I don't think this is a big issue but I wanted to point it out.

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp [hunk 3]
```diff
@@ -125,6 +131,56 @@ int listDevices(struct VMGlobals* g, int type) {
...
+    int numDevices;
+    PaError err = Pa_Initialize();
+    if (err != paNoError)
+        return 0;
+
+    numDevices = Pa_GetDeviceCount();
+    if (numDevices < 0)
+        return 0;
+
+    std::vector<const PaDeviceInfo*> deviceInfos;
```
Comment (dyfer) [inline lang/LangPrimSource/SC_AudioDevicePrim.cpp]: @brianlheim do I need to deallocate this vector?

**Comment by brianlheim** [comment]
> I think the only downside is that it does change the type of error (when calling ServerOptions.devices) when compiled with JACK/on Linux. I don't think this is a big issue but I wanted to point it out.

that seems fine to me, as long as it fails; it's documented as not being implemented anyway.

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp (hunk 3 above)
Comment (brianlheim) [reply lang/LangPrimSource/SC_AudioDevicePrim.cpp]: nope, that is the magic of [RAII](https://en.cppreference.com/w/cpp/language/raii) -- in short, much of modern C++ relies on the concept of treating an object's constructor as an initialization and resource acquisition step, and treating its destructor (here, called when we exit the function) as a resource freeing step. opening files (std::fstream), allocating memory (std::vector and other std containers), creating threads (std::thread), and acquiring/releasing a lock (std::lock_guard) all can work this way in C++.

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp [hunk 4]
```diff
@@ -125,6 +131,56 @@ int listDevices(struct VMGlobals* g, int type) {
...
+        if (type < BOTH) {
+            if (type < IN) {
+                if (pdi->maxOutputChannels > 0)
+                    deviceInfos.push_back(pdi);
+            } else {
+                if (pdi->maxInputChannels > 0)
+                    deviceInfos.push_back(pdi);
+            }
+        } else
+            deviceInfos.push_back(pdi);
```
Comment (brianlheim) [inline lang/LangPrimSource/SC_AudioDevicePrim.cpp]: i think you kind of copied this from above, but it's a really awkward way to write it. we know `type` can only have 3 values, so a series of if-elses is a clearer way to write it:

```cpp
if (type == OUT) {
    ...
} else if (type == IN) {
    ...
} else {
    // type is BOTH
    ...
}
```

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp [hunk 5]
```diff
@@ -125,6 +131,56 @@ int listDevices(struct VMGlobals* g, int type) {
...
+    }
+
+    int numSelectedDevices = deviceInfos.size();
+
+    PyrSlot* a = g->sp - 2;
+    PyrObject* devArray = newPyrArray(g->gc, numSelectedDevices * sizeof(PyrObject), 0, true);
+    SetObject(a, devArray); // this is okay here as we don't use the receiver below
```
Comment (brianlheim) [inline lang/LangPrimSource/SC_AudioDevicePrim.cpp]: having a local variable named `a` is not really helping here -- you can just write `SetObject(g->sp - 2, devArray)`

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp [hunk 6]
```diff
@@ -125,6 +131,56 @@ int listDevices(struct VMGlobals* g, int type) {
...
+
+    for (int i = 0; i < numSelectedDevices; i++) {
+        PyrString* string = newPyrString(g->gc, GetPaDeviceName(deviceInfos[i]).c_str(), 0, true);
+        SetObject(devArray->slots + i, string);
+        devArray->size++;
```
Comment (brianlheim) [inline lang/LangPrimSource/SC_AudioDevicePrim.cpp]: you can simply set `devArray->size = numSelectedDevices` above or below this loop, this is kind of unnecessary work

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp [hunk 7]
```diff
@@ -125,6 +131,56 @@ int listDevices(struct VMGlobals* g, int type) {
...
+                    deviceInfos.push_back(pdi);
+            } else {
+                if (pdi->maxInputChannels > 0)
+                    deviceInfos.push_back(pdi);
+            }
+        } else
+            deviceInfos.push_back(pdi);
+    }
+
+    int numSelectedDevices = deviceInfos.size();
```
Comment (brianlheim) [inline lang/LangPrimSource/SC_AudioDevicePrim.cpp]: personally, i would just use `deviceInfos.size()` instead of creating another local variable. it's the same number of characters, and typically having fewer local variables (within reason) makes code easier to understand. when you see `numSelectedDevices` below, it's not immediately obvious that it has a relationship to `deviceInfos`, and it's definitely not obvious that that relationship stays intact. small point, but just wanted to state my preference

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp [hunk 8]
```diff
@@ -125,6 +131,56 @@ int listDevices(struct VMGlobals* g, int type) {
...
+
+    PyrSlot* a = g->sp - 2;
+    PyrObject* devArray = newPyrArray(g->gc, numSelectedDevices * sizeof(PyrObject), 0, true);
+    SetObject(a, devArray); // this is okay here as we don't use the receiver below
+
+    for (int i = 0; i < numSelectedDevices; i++) {
+        PyrString* string = newPyrString(g->gc, GetPaDeviceName(deviceInfos[i]).c_str(), 0, true);
+        SetObject(devArray->slots + i, string);
+        devArray->size++;
+        g->gc->GCWriteNew(devArray, (PyrObject*)string); // we know array is white so we can use GCWriteNew
```
Comment (brianlheim) [inline lang/LangPrimSource/SC_AudioDevicePrim.cpp]: generally try to avoid c-style casts when a less aggressive cast will work -- c-style casts can do lots of conversion including changing const-ness (https://en.cppreference.com/w/cpp/language/explicit_cast). here, you should use `static_cast<PyrObject*>(string)`

File: HelpSource/Reference/AudioDeviceSelection.schelp [hunk 9]
```diff
@@ -24,7 +24,7 @@ code::
 Server.default.options.device_("MOTU 828");
 ::
 
-On macOS you can programmatically obtain a list of available audio devices without booting the server:
+You can programmatically obtain a list of available audio devices without booting the server:
```
[the remark this answers is not in the document]
Comment (dyfer) [reply HelpSource/Reference/AudioDeviceSelection.schelp]: Sounds good. I went with your first suggestion, since it seems more user-friendly. It the user compiles SC with a different backend, they likely understand the implications of different backends.

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp (hunk 8 above)
Comment (dyfer) [reply lang/LangPrimSource/SC_AudioDevicePrim.cpp]: I can't say that I understand all these particular objects (`PyrString`, `PyrObject`) and this was copied from the coreaudio code. However, when I tried to use your suggestion, I got 
```
error: static_cast
      from 'PyrString *' to 'PyrObject *', which are not related by inheritance, is not allowed
```

File: lang/LangPrimSource/SC_PortAudioPrim.cpp (hunk 2 above)
Comment (brianlheim) [reply lang/LangPrimSource/SC_PortAudioPrim.cpp]: (answered on slack)

File: lang/LangPrimSource/SC_AudioDevicePrim.cpp (hunk 8 above)
Comment (brianlheim) [reply lang/LangPrimSource/SC_AudioDevicePrim.cpp]: ah, my mistake, i thought PyrString was a derived class of PyrObject, but it's not. you'll have to use `reinterpret_cast`.

**Comment by brianlheim** [comment]
thanks!
