### PR TITLE
sclang: LanguageConfig store fix

### LINKED ISSUE #4595: LanguageConfig.store writes to default yaml file even if interpreter is using another one
## Environment

* SuperCollider version: 3.10.3
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

1. in the IDE, open preferences -> interpreter
2. add new configuration file
3. save changes
4. reboot interpreter
then:

```supercollider
LanguageConfig.addIncludePath("/any/path");
LanguageConfig.store; //stores in the default sclang_conf.yaml file
```
Reboot the interpreter - the changes are not applied.
## Expected vs. actual behavior

`LanguageConfig.store` by default stores the configuration in the default `sclang_conf.yaml` file, not in the one currently used by the interpreter.

While this is sort of documented:
```
Arguments:
file | Path to the configuration file to store. If the value is nil it defaults to Platform.userConfigDir +/+ "sclang_conf.yaml"
```
I would argue that this is not a desired behavior and that the configuration changes should by default be saved to the file currently used by the language. 

What do others think about this?

### PR DESCRIPTION
**Pull request by dyfer**
Use the currently specified config file when saving language configuration

## Purpose and Motivation

Fixes #4595 

I couldn't get the [proposed fix](https://github.com/supercollider/supercollider/issues/4595#issuecomment-534786390) to work - adding anything in the language method before calling the sclang primitive causes errors - there doesn't seem to be a way to modify the argument in sclang before calling the primitive.

~~This seems like a proper fix, but there's one area for improvement, see below.~~
## Types of changes

- Documentation
- Bug fix
- Breaking change

## To-do list

- [x] Code is tested
- [ ] ~~All tests are passing - does this need tests?~~
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

File: lang/LangPrimSource/PyrPrimitive.cpp [hunk 1]
```diff
@@ -3645,7 +3645,10 @@ static int prLanguageConfig_writeConfigFile(struct VMGlobals* g, int numArgsPush
         config_path = SC_Codecvt::utf8_str_to_path(path);
         gLanguageConfig->writeLibraryConfigYAML(config_path);
     } else {
-        config_path = SC_Filesystem::instance().getDirectory(SC_Filesystem::DirName::UserConfig) / "sclang_conf.yaml";
+        config_path = SC_Codecvt::path_to_utf8_str(gLanguageConfig->getConfigPath());
+        if (config_path.size() == 0)
+            config_path =
+                SC_Filesystem::instance().getDirectory(SC_Filesystem::DirName::UserConfig) / "sclang_conf.yaml";
```
Comment (dyfer) [inline lang/LangPrimSource/PyrPrimitive.cpp]: `"sclang_conf.yaml"` is harcoded here, while we have it defined [here](https://github.com/supercollider/supercollider/blob/3037bf299bf21618bdf11fce53bf53427e84f13a/lang/LangSource/SC_LanguageConfig.cpp#L44). Would there be a way to use that constant here?

**Comment by jamshark70** [comment]
> I couldn't get the proposed fix to work - adding anything in the language method before calling the sclang primitive causes errors

Ah ok, I didn't catch that. I was accidentally trying to put bytecodes before a primitive call but that's not allowed.

A language side solution, then, would be a method `*store` to check the path and a second method `*prStore` to call the primitive.

- Downside: Looks a little funny.

- Upsides: There's a *lot* of precedent in the class library already (funny-looking or no, it's an established practice). Also, it *feels* less risky to me to handle it in the class library than in C++ but my feeling might be irrelevant.

Actually I can think of a concrete reason to do it in the library: readability / accessibility. Users could check class library code to see how the default is determined, where many users will not dig into the C++ sources.

File: lang/LangPrimSource/PyrPrimitive.cpp (hunk 1 above)
Comment (brianlheim) [reply lang/LangPrimSource/PyrPrimitive.cpp]: sure! probably the easiest thing to do would be add `extern const char* SCLANG_YAML_CONFIG_FILENAME` in the header, and remove the `static` from the cpp file.

File: lang/LangPrimSource/PyrPrimitive.cpp [hunk 2]
```diff
@@ -3645,7 +3645,10 @@ static int prLanguageConfig_writeConfigFile(struct VMGlobals* g, int numArgsPush
         config_path = SC_Codecvt::utf8_str_to_path(path);
         gLanguageConfig->writeLibraryConfigYAML(config_path);
```
Comment (brianlheim) [inline lang/LangPrimSource/PyrPrimitive.cpp]: whoops, just realized this results in a superfluous write -- can you remove this line?

File: lang/LangPrimSource/PyrPrimitive.cpp [hunk 3]
```diff
@@ -3645,7 +3645,10 @@ static int prLanguageConfig_writeConfigFile(struct VMGlobals* g, int numArgsPush
...
     } else {
-        config_path = SC_Filesystem::instance().getDirectory(SC_Filesystem::DirName::UserConfig) / "sclang_conf.yaml";
+        config_path = SC_Codecvt::path_to_utf8_str(gLanguageConfig->getConfigPath());
+        if (config_path.size() == 0)
```
Comment (brianlheim) [inline lang/LangPrimSource/PyrPrimitive.cpp]: `if (config_path.empty())`

**Comment by brianlheim** [comment]
> Users could check class library code to see how the default is determined, where many users will not dig into the C++ sources.

or better yet, they could simply read the documentation which this PR provides

**Comment by brianlheim** [comment]
> does this need tests?

generally my view is that configuration logic like this is finnicky and not incredibly rewarding to test, but if you'd like to add a test i'm not opposed to it :)

File: lang/LangPrimSource/PyrPrimitive.cpp (hunk 1 above)
Comment (dyfer) [reply lang/LangPrimSource/PyrPrimitive.cpp]: do you mean a new header file?

**Comment by dyfer** [comment]
> A language side solution, then, would be a method *store to check the path and a second method *prStore to call the primitive.

this seem like a reasonable language-side solution.

However, the language side is still buggy IMO. @brianlheim @jamshark70 what do you think about proceeding to fix the cpp side with this PR and maybe also providing explicit classlib side like suggested by @jamshark70? Or is this PR with the accompanying docs enough?

**Comment by jamshark70** [comment]
> or better yet, they could simply read the documentation which this PR provides

That's fair -- I'm not requesting changes and I won't stand in the way of this PR as it is. I also think, all other things being equal, if there's a choice between providing a default value for a method argument in class library code or in the backend, it's probably better as a general practice to do it in the class library.

Less of a concern here because LanguageConfig is already basically just a front end for primitives (almost all of its functionality is hidden in C++, making it kind of a special case). But it may not be an ideal habit to get into.

**Comment by dyfer** [comment]
With most everything else with LanguageConfig being hidden I think it's a valid point that it's not worthwhile to have this part exposed/controlled in sclang. 

I'll proceed with work on the cpp part.

File: lang/LangPrimSource/PyrPrimitive.cpp (hunk 1 above)
Comment (brianlheim) [reply lang/LangPrimSource/PyrPrimitive.cpp]: nah, it can go in the sc language config header file

**Comment by brianlheim** [comment]
> However, the cpp side is still buggy IMO

what do you mean?

> I thought about it for a moment and that would probably require starting another sclang in the test, and also writing to a default configuration file. This seems like too much hassle for the test?

yes i agree it's too much hassle

File: lang/LangPrimSource/PyrPrimitive.cpp (hunk 1 above)
Comment (dyfer) [reply lang/LangPrimSource/PyrPrimitive.cpp]: `SCBase.h`?

**Comment by dyfer** [comment]
> > However, the cpp side is still buggy IMO
> 
> what do you mean?

I was referring to fixing this in classlib and leaving cpp as is. IMO the language save primitive should not overwrite the default config file, when a different config file is used.

File: lang/LangPrimSource/PyrPrimitive.cpp (hunk 1 above)
Comment (brianlheim) [reply lang/LangPrimSource/PyrPrimitive.cpp]: yes

**Comment by brianlheim** [comment]
oh, i thought you were referring to some bug that this PR doesn't cover. it's fine as is, let's focus on getting it merged

File: lang/LangPrimSource/PyrPrimitive.cpp (hunk 1 above)
Comment (dyfer) [reply lang/LangPrimSource/PyrPrimitive.cpp]: Should I move all these or just `SCLANG_YAML_CONFIG_FILENAME`?


```supercollider
static const char* INCLUDE_PATHS = "includePaths";
static const char* EXCLUDE_PATHS = "excludePaths";
static const char* POST_INLINE_WARNINGS = "postInlineWarnings";
static const char* CLASS_LIB_DIR_NAME = "SCClassLibrary";
static const char* SCLANG_YAML_CONFIG_FILENAME = "sclang_conf.yaml";
```

Comment (brianlheim) [reply lang/LangPrimSource/PyrPrimitive.cpp]: just the one, unless you see places where the others could be used. to clarify, you are not moving anything, but rather adding an extern declaration in the header and removing static here.

Comment (dyfer) [reply lang/LangPrimSource/PyrPrimitive.cpp]: thanks, that's helpful. I think I understand now.

**Comment by brianlheim** [comment]
further explanation on what happened with the const char * here --

if the declaration (in the header) were not extern, the compiler and linker would try to create a memory location for each file that includes it (and fail because they can't have the same name)

if the definition (in the cpp) were static, the compiler and linker would not allow you to reference that variable from other cpp files, and linking would fail.

linkage is a really tricky concept to understand in C++ and these things still trip me up from time to time. it doesn't help that different language standards changed the linkage properties of certain kinds of variables.
