### PR TITLE
sclang: introduce unixCmd for array of arguments

### LINKED ISSUE #1738: unixCmd adds "sh -c" to the command
`sc_popen()` prevents user code from killing a process launched by unixCmd. Among the user impacts, this means the MP3 quark is broken, with no easy workaround.

common/sc_popen.cpp, lines 53-54:

```
    argv[0] = (char *)"sh";
    argv[1] = (char *)"-c";
```

In POSIXy systems, this executes a command that looks like `sh -c user...command...`. Both OSX and Linux respond by creating a process, with one PID, for "sh." Subsequently, "sh" launches another process for the user's command, with a different PID.

In sclang, `unixCmd` returns the PID to the user. However, this is the PID of `sh`. If you then do `"kill -9 %".format(thePid).unixCmd`, the `sh` process will be killed, _but the user-command process keeps running!_

There is no guaranteed, consistent way to extrapolate from the "sh" PID to the user-command PID -- hence, no reliable way to kill the actual command process.
- If there is no concrete benefit to prepending `sh -c`, then... it's actively doing harm, so take it out.
- If there is a good reason to have it, then we need to find some way to make both PIDs available to the user.

### PR DESCRIPTION
**Pull request by miguel-negrao**
fixes #1738 

Incorporated some of @timblechmann 's feedback. 

* changed from malloc/free to new/delete. I wasn't able to use unique_ptr for sc_process due to some very complicated type error.
* removed un-const castings.
* moved function to the same file as other unix primitives. There was no reason for it be in the array primitives file.

tested with:

["/bin/echo","hello","world"].unixCmd
["/bin/echo",1,"world"].unixCmd
[].unixCmd

x = ["/usr/local/bin/scsynth","-u","57128"].unixCmd

pid at x checks out with pgrep.

### CODE REVIEW

File: lang/LangPrimSource/PyrUnixPrim.cpp [hunk 1]
```diff
@@ -147,35 +152,29 @@ static void string_popen_thread_func(struct sc_process *process)
...
-	struct sc_process *process;
 	PyrSlot *a = g->sp - 1;
 	PyrSlot *b = g->sp;
-	int err;
 
 	if (!isKindOfSlot(a, class_string)) return errWrongType;
 
-	char *cmdline = (char*)malloc(slotRawObject(a)->size + 1);
-	err = slotStrVal(a, cmdline, slotRawObject(a)->size + 1);
-	if(err) {
```
Comment (miguel-negrao) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: These error checks are not necessary because above the slot was already checked for class_string which is the same check done inside slotStrVal

File: lang/LangPrimSource/PyrUnixPrim.cpp [hunk 2]
```diff
@@ -186,6 +185,79 @@ int prString_POpen(struct VMGlobals *g, int numArgsPushed)
...
+	if (!(slotRawInt(&obj->classptr->classFlags) & classHasIndexableInstances))
+		return errNotAnIndexableObject;
+		
+	if( obj->size < 1)
+		return errFailed;
+		
+	PyrSlot filenameSlot;
+	getIndexedSlot(obj, &filenameSlot, 0);
+	if (!isKindOfSlot(&filenameSlot, class_string)) return errWrongType;
+	char filename[slotRawObject(&filenameSlot)->size + 1];
```
Comment (miguel-negrao) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: Used stack here, suppose that a filename even if long won't blow the stack ?

**Comment by crucialfelix** [comment]
If the command is not found or the process exits with an error, it throws a primitive failed, right ?

Is there anyway to easily get both the stdout and the error code ?  See Pipe *call / *callSync

**Comment by miguel-negrao** [comment]
> If the command is not found or the process exits with an error, it throws a primitive failed, right ?
> 

No. if execve fails error 127 is reported. If the process exits with an error that error is reported (posted). No primitive failed error it thrown.

```
	res = WEXITSTATUS(res);

	if(process->postOutput)
		postfl("RESULT = %d\n", res);
```

> Is there anyway to easily get both the stdout and the error code ? See Pipe *call / *callSync

You can get stdOut via unixCmdGetStdOut which uses Pipe internally. If there is an error the error goes to stderr not stdout, therefore it won't be displayed with unixCmdGetStdOut. You can however redirect stderr to stdout in the shell:

    "ls; ls --asdasd 2>&1".unixCmdGetStdOut

**Comment by jamshark70** [comment]
Felix - check the unixCmd help:

http://doc.sccode.org/Classes/String.html#-unixCmd

Arguments:
action	
A Function that is called when the process has exited. It is passed two arguments: the exit code and pid of the exited process.

unixCmd is asynchronous, so it can't throw an error in SC if the child process fails.

File: lang/LangPrimSource/PyrUnixPrim.cpp (hunk 2 above)
Comment (timblechmann) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: there is a notion of `PATH_MAX`/`MAX_PATH`. variable length arrays aren't well supported with msvc, which only implements a subset of c99.

File: common/sc_popen.cpp [hunk 3]
```diff
@@ -31,10 +34,29 @@
...
+	argv[0] = v0.data();
+	std::string str1 = "-c";
+	std::vector<char> v1( str1.begin(), str1.end() );
+	v1.push_back('\0');
+	argv[1] = v1.data();
+	std::string str2 = command;
+	std::vector<char> v2( str2.begin(), str2.end() );
+	v2.push_back('\0');
+	argv[2] = v2.data();
+	argv[3] = NULL;
```
Comment (timblechmann) [inline common/sc_popen.cpp]: `nullptr` is a bit more typesafe than `NULL`

File: lang/LangPrimSource/PyrUnixPrim.cpp [hunk 4]
```diff
@@ -147,35 +152,29 @@ static void string_popen_thread_func(struct sc_process *process)
...
+	char *cmdline = new char[slotRawObject(a)->size + 1];
+	slotStrVal(a, cmdline, slotRawObject(a)->size + 1);
 
 #ifdef SC_IPHONE
 	SetInt(a, 0);
 	return errNone;
 #endif
 
-	process = (struct sc_process *)malloc(sizeof(struct sc_process));
+	sc_process *process = new sc_process;
```
Comment (timblechmann) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: what about:
`std::unique_ptr<sc_process> process ( new sc_process )`

if `string_popen_thread_func` takes a smart pointer as argument, you can model the transfer of ownership of `sc_process` to the helper thread. no need to free the struct manually

File: lang/LangPrimSource/PyrUnixPrim.cpp [hunk 5]
```diff
@@ -186,6 +185,79 @@ int prString_POpen(struct VMGlobals *g, int numArgsPushed)
...
+	}
+
+	thread thread(std::bind(string_popen_thread_func, process));
+	thread.detach();
+
+	for (int i=1; i<obj->size; ++i) {
+		delete [] argv[i];
+	}
+
+	SetInt(a, process->pid);
```
Comment (timblechmann) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: maybe a bit safer: don't dereference process after passing it to `string_popen_thread_func`: the thread might finish and deallocate the process struct before you read the pid

File: lang/LangPrimSource/PyrUnixPrim.cpp (hunk 4 above)
Comment (miguel-negrao) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: Doing that:

```
diff --git a/lang/LangPrimSource/PyrUnixPrim.cpp b/lang/LangPrimSource/PyrUnixPrim.cpp
index a959d94..84b00d5 100644
--- a/lang/LangPrimSource/PyrUnixPrim.cpp
+++ b/lang/LangPrimSource/PyrUnixPrim.cpp
@@ -115,7 +115,7 @@ struct sc_process {
 	bool postOutput;
 };
 
-static void string_popen_thread_func(struct sc_process *process)
+static void string_popen_thread_func(std::unique_ptr<sc_process> process)
 {
 	FILE *stream = process->stream;
 	pid_t pid = process->pid;
@@ -134,7 +134,7 @@ static void string_popen_thread_func(struct sc_process *process)
 	if(process->postOutput)
 		postfl("RESULT = %d\n", res);
 
-	delete process;
+	//delete process;
 
 	gLangMutex.lock();
 	if(compiledOK) {
@@ -165,7 +165,7 @@ int prString_POpen(struct VMGlobals *g, int numArgsPushed)
 	return errNone;
 #endif
 
-	sc_process *process = new sc_process;
+	std::unique_ptr<sc_process> process(new sc_process);
 	process->stream = sc_popen(cmdline, &process->pid, "r");
 	setvbuf(process->stream, 0, _IONBF, 0);
 
@@ -174,7 +174,7 @@ int prString_POpen(struct VMGlobals *g, int numArgsPushed)
 	delete [] cmdline;
 
 	if(process->stream == NULL) {
-		delete process;
+		//delete process;
 		return errFailed;
 	}
 
@@ -235,14 +235,14 @@ int prArrayPOpen(struct VMGlobals *g, int numArgsPushed)
 		}
 	}
```

I get this error which is too advanced for me. Googling didn't help me much.

```
[ 34%] Building CXX object lang/CMakeFiles/libsclang.dir/LangPrimSource/PyrUnixPrim.cpp.o
In file included from /usr/include/c++/5/mutex:42:0,
                 from /usr/include/c++/5/condition_variable:39,
                 from /home/miguel/Development/SuperCollider/supercollider/common/SC_Lock.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangSource/PyrSched.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangPrimSource/PyrUnixPrim.cpp:33:
/usr/include/c++/5/functional: In instantiation of ‘struct std::_Bind_simple<std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>()>’:
/usr/include/c++/5/thread:137:59:   required from ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>; _Args = {}]’
/home/miguel/Development/SuperCollider/supercollider/lang/LangPrimSource/PyrUnixPrim.cpp:181:60:   required from here
/usr/include/c++/5/functional:1505:61: error: no type named ‘type’ in ‘class std::result_of<std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>()>’
       typedef typename result_of<_Callable(_Args...)>::type result_type;
                                                             ^
/usr/include/c++/5/functional:1526:9: error: no type named ‘type’ in ‘class std::result_of<std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>()>’
         _M_invoke(_Index_tuple<_Indices...>)
         ^
In file included from /usr/include/c++/5/mutex:38:0,
                 from /usr/include/c++/5/condition_variable:39,
                 from /home/miguel/Development/SuperCollider/supercollider/common/SC_Lock.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangSource/PyrSched.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangPrimSource/PyrUnixPrim.cpp:33:
/usr/include/c++/5/tuple: In instantiation of ‘constexpr std::_Head_base<_Idx, _Head, false>::_Head_base(const _Head&) [with long unsigned int _Idx = 0ul; _Head = std::unique_ptr<sc_process>]’:
/usr/include/c++/5/tuple:357:21:   required from ‘constexpr std::_Tuple_impl<_Idx, _Head>::_Tuple_impl(const _Head&) [with long unsigned int _Idx = 0ul; _Head = std::unique_ptr<sc_process>]’
/usr/include/c++/5/tuple:473:33:   required from ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {std::unique_ptr<sc_process, std::default_delete<sc_process> >}]’
/usr/include/c++/5/functional:1114:70:   required from ‘std::_Bind<_Functor(_Bound_args ...)>::_Bind(_Functor&&, _Args&& ...) [with _Args = {std::unique_ptr<sc_process, std::default_delete<sc_process> >&}; _Functor = void (*)(std::unique_ptr<sc_process>); _Bound_args = {std::unique_ptr<sc_process, std::default_delete<sc_process> >}]’
/usr/include/c++/5/functional:1468:42:   required from ‘typename std::_Bind_helper<std::__is_socketlike<_Func>::value, _Func, _BoundArgs ...>::type std::bind(_Func&&, _BoundArgs&& ...) [with _Func = void (&)(std::unique_ptr<sc_process>); _BoundArgs = {std::unique_ptr<sc_process, std::default_delete<sc_process> >&}; typename std::_Bind_helper<std::__is_socketlike<_Func>::value, _Func, _BoundArgs ...>::type = std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>]’
/home/miguel/Development/SuperCollider/supercollider/lang/LangPrimSource/PyrUnixPrim.cpp:181:59:   required from here
/usr/include/c++/5/tuple:108:25: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = sc_process; _Dp = std::default_delete<sc_process>]’
       : _M_head_impl(__h) { }
                         ^
In file included from /usr/include/c++/5/condition_variable:43:0,
                 from /home/miguel/Development/SuperCollider/supercollider/common/SC_Lock.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangSource/PyrSched.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangPrimSource/PyrUnixPrim.cpp:33:
/usr/include/c++/5/bits/unique_ptr.h:356:7: note: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^
```

**Comment by miguel-negrao** [comment]
I don't understand why when I use vector for the argv strings, although they are printed correctly by cout, for instance 'echo' will not print anything. I'm I doing something wrong ?

```
@@ -229,9 +230,11 @@ int prArrayPOpen(struct VMGlobals *g, int numArgsPushed)
                        PyrSlot argSlot;
                        getIndexedSlot(obj, &argSlot, i);
                        if (!isKindOfSlot(&argSlot, class_string)) return errWrongType;
-                       char *arg = new char[slotRawObject(&argSlot)->size + 1];
-                       slotStrVal(&argSlot, arg, slotRawObject(&argSlot)->size + 1);
-                       argv[i] = arg;
+                       //char *arg = new char[slotRawObject(&argSlot)->size + 1];
+                       std::vector<char> arg(slotRawObject(&argSlot)->size + 1);
+                       slotStrVal(&argSlot, arg.data(), slotRawObject(&argSlot)->size + 1);
+                       argv[i] = arg.data();
+                       std::cout << "**" << argv[i] << "**\n";
                }
        }
        
@@ -249,9 +252,9 @@ int prArrayPOpen(struct VMGlobals *g, int numArgsPushed)
        thread thread(std::bind(string_popen_thread_func, process));
        thread.detach();
 
-       for (int i=1; i<obj->size; ++i) {
+       /*for (int i=1; i<obj->size; ++i) {
                delete [] argv[i];
-       }
+       }*/
 
        SetInt(a, process->pid);
        return errNone;

running: ["/bin/echo","hello","world"].unixCmd; 0.exit

*** Welcome to SuperCollider 3.7alpha1. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
**hello**
**world**
 
RESULT = 0
empty
cleaning up OSC
terminate called without an active exception
Aborted
```

**Comment by miguel-negrao** [comment]
Except for the unique_ptr I think I addressed the other issues. Also, this doesn't work for windows, so for windows the primitive will call just post a message, not sure that is the proper to deal with this. I'm not familiar with the windows process code to do changes there.

File: lang/LangPrimSource/PyrUnixPrim.cpp (hunk 4 above)
Comment (timblechmann) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: `thread thread(std::bind(string_popen_thread_func, process));`

this tries to copy the `unique_ptr` ... but you don't want to "copy", but to "move" it:

this might work:
`thread thread(std::bind(string_popen_thread_func, std::move(process)));`

or if you don't change the function signature, you can use a lambda function:
```
thread thread( [processInThread=std::move(process)] {
  string_popen_thread_func( process.get() );
});
```

Comment (miguel-negrao) [inline lang/LangPrimSource/PyrUnixPrim.cpp]: Changing to move I still get one error:

```
[ 18%] Building CXX object lang/CMakeFiles/libsclang.dir/LangPrimSource/PyrUnixPrim.cpp.o
In file included from /usr/include/c++/5/mutex:42:0,
                 from /usr/include/c++/5/condition_variable:39,
                 from /home/miguel/Development/SuperCollider/supercollider/common/SC_Lock.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangSource/PyrSched.h:26,
                 from /home/miguel/Development/SuperCollider/supercollider/lang/LangPrimSource/PyrUnixPrim.cpp:33:
/usr/include/c++/5/functional: In instantiation of ‘struct std::_Bind_simple<std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>()>’:
/usr/include/c++/5/thread:137:59:   required from ‘std::thread::thread(_Callable&&, _Args&& ...) [with _Callable = std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>; _Args = {}]’
/home/miguel/Development/SuperCollider/supercollider/lang/LangPrimSource/PyrUnixPrim.cpp:182:72:   required from here
/usr/include/c++/5/functional:1505:61: error: no type named ‘type’ in ‘class std::result_of<std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>()>’
       typedef typename result_of<_Callable(_Args...)>::type result_type;
                                                             ^
/usr/include/c++/5/functional:1526:9: error: no type named ‘type’ in ‘class std::result_of<std::_Bind<void (*(std::unique_ptr<sc_process>))(std::unique_ptr<sc_process>)>()>’
         _M_invoke(_Index_tuple<_Indices...>)
         ^
```

**Comment by miguel-negrao** [comment]
Doesn't build for osx:

```
/Users/travis/build/supercollider/supercollider/common/sc_popen.cpp:37:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'

        std::string str0 = "/bin/sh";

                    ^

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:188:33: note: template is declared here

    class _LIBCPP_TYPE_VIS_ONLY basic_string;

                                ^
```

What could be the issue ?
