### PR TITLE
Fix SequenceableCollection -unixCmd on Windows 

### LINKED ISSUE #6742: unixCmd doesn't return the proper PID on Windows
## Environment

* SuperCollider version: 3.14-dev
* Operating system: Windows 11
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// basic:
s.boot;
s.pid; // compare with the PID of the scsynth.exe in the Task Manager

// similarly when  running commands by hand:
r = (Server.program + Server.default.options.asOptionsString).unixCmd;
r.postln; // compare with the scsynth.exe's PID in the Task Manager

// incorrect PID also happens with ArrayedCollection -unixCmd, which has a different implementation IIUC
r = [Server.program, Server.default.options.asOptionsString].unixCmd; // note that this doesn't start the server on macOS due to shell quoting; however it does seem to work on Windows
r.postln; // pid is still incorrect though

// this makes it impossible to keep track of the process, e.g. to terminate it:
thisProcess.platform.killProcessByID(r); // doesn't stop the server process
```

## Expected vs. actual behavior

Expected: the PID matches the PID of the command. Actual: some other number is returned.

I found notes on related functionality in #1738 and #3539, but I don't see this problem being explicitly reported. 

On macOS and Linux we are getting the PID of scsynth reliably. It would be great to fix this...

This issue prevents the `TestServer_clientID_booted` tests from completing on Windows.

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

In this PR:
- `ArrayedCollection -unixCmd` is fixed to _not_ run the command through `cmd.exe`, which matches behavior on *nix
  - as a result, a proper PID of the requested command is now returned from this method
- `sc_popen()` is renamed to `sc_popen_shell()` to reflect the behavior of the function.

The rest of the functionality previously present in this PR will be addressed in separate Issues/PRs.

How to test this:
```supercollider
// pid with ArrayedCollection
r = [Server.program, "-u", "57110"].unixCmd; // run scsynth using ArrayedCollection -unixCmd
r.postln; // this should match the scsynth pid in Task Manager
thisProcess.platform.killProcessByID(r); // scsynth should exit
```

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
@Spacechild1 I went down this rabbit hole... Do you have any opinion on the proposed solution?

File: common/sc_popen.cpp [hunk 1]
```diff
@@ -163,10 +163,11 @@ std::tuple<pid_t, FILE*> sc_popen_argv(const std::vector<std::string>& strings,
         strings.begin(), strings.end(), std::string(),
         [](const std::string& a, const std::string& b) -> std::string { return a + (a.length() > 0 ? " " : "") + b; });
 
-    return sc_popen(std::move(commandLine), type);
+    return sc_popen_c(std::move(commandLine).data(), type.data());
 }
 
 std::tuple<pid_t, FILE*> sc_popen(std::string&& command, const std::string& type) {
+    command = "cmd /c " + command;
     return sc_popen_c(command.data(), type.data());
```
Comment (Spacechild1) [inline common/sc_popen.cpp:171]: `sc_open_c` is just the C-style version of `sc_open`, so they should have the same behavior (= spawn a process with the given arguments). If `cmd /c` is required, it should be explicitly added by the caller.

Comment (dyfer) [reply common/sc_popen.cpp:171]: Maybe I'm not understanding correctly? 
Running `String .unixCmd` in a shell is a [behavior defined in SC](https://github.com/supercollider/supercollider/pull/6837/files#diff-a15e8fe708dbb2bcd27256def5a360fbacc152340db2385f013b05af940fb8f8R675). On *nix we do [sh -c](https://github.com/supercollider/supercollider/pull/6837/files#diff-ddec1c4dde7311f60d467ba6918bc5abcfe4b4718638d305850f16d3263984e8R29-R30) so I think `cmd /c` matches the intended behavior on Windows?

Comment (Spacechild1) [reply common/sc_popen.cpp:171]: Of course, this would also apply to the Linux version. (`sc_popen` adds `/bin/sh -c` and forwards to `sc_popen_argv`.)

In either case, I would expect `sc_popen` to just run the given command as is.

If you are motivated, it would be cool to fix this on both sides. Otherwise just keep your solution, but maybe add a comment.

Comment (Spacechild1) [reply common/sc_popen.cpp:171]: Here's another idea: keep your fix, but rename `sc_popen` to something like `sc_popen_shell` in both implementations. Then it would be clear what the function does :)

File: common/sc_popen.cpp [hunk 2]
```diff
@@ -163,10 +163,11 @@ std::tuple<pid_t, FILE*> sc_popen_argv(const std::vector<std::string>& strings,
         strings.begin(), strings.end(), std::string(),
         [](const std::string& a, const std::string& b) -> std::string { return a + (a.length() > 0 ? " " : "") + b; });
 
-    return sc_popen(std::move(commandLine), type);
+    return sc_popen_c(std::move(commandLine).data(), type.data());
```
Comment (Spacechild1) [inline common/sc_popen.cpp:166]: Since you are just calling a member function, there's no point in moving the object!

**Comment by Spacechild1** [comment]
> ArrayedCollection -unixCmd is fixed to not run the command through cmd.exe, which matches behavior on *nix
> as a result, a proper PID of the requested command is now returned from this method

Cool!

This might be out of scope to this PR, but maybe you could add cross links between `String-unixCmd` and `SequencableCollection-unixCmd` in the documentation, e.g. "If you want to run a program without a shell, please use link::Classes/SequencableCollection#-unixCmd::" and vice versa.

> String -unixCmd still returns the PID of cmd.exe and not of the specified command, but there doesn't seem to be a straightforward solution for this
> execvp used on *nix for running a command is not available on Windows

`execvp` is used together with `fork` to overlay the *child* process with the desired program. `fork + exec` is basically the Unix equivalent to `CreateProcess`.

However, `sh` in turn executes the given command(s) as child process(es), so I would totally expect that `String -unixCmd` returns the PID of the shell itself, both on Windows and Unix! Are your sure that this isn't the case?

---

Side note: I think it's a pretty strange design that `SequencableCollection-unixCmd` and `String-unixCmd` have different behavior. Personally, I would have given `String-unixCmd` a different name altogether, e.g. `String-shellCmd`.

**Comment by dyfer** [comment]
> This might be out of scope to this PR, but maybe you could add cross links between `String-unixCmd` and `SequencableCollection-unixCmd` in the documentation, e.g. "If you want to run a program without a shell, please use link::Classes/SequencableCollection#-unixCmd::" and vice versa.

Good idea, I think it's a small addition and could go in here.

> > String -unixCmd still returns the PID of cmd.exe and not of the specified command, but there doesn't seem to be a straightforward solution for this
> > execvp used on *nix for running a command is not available on Windows
> 
> `execvp` is used together with `fork` to overlay the _child_ process with the desired program. `fork + exec` is basically the Unix equivalent to `CreateProcess`.
> 
> However, `sh` in turn executes the given command(s) as child process(es), so I would totally expect that `String -unixCmd` returns the PID of the shell itself, both on Windows and Unix! Are your sure that this isn't the case?

I checked on current macOS and I can't see a separate shell and I get the PID of the actual process I'm runnnig.

HOWEVER I remember previously seeing a separate `sh` shell being spun and getting a PID of that! Actually there's an existing issue: https://github.com/supercollider/supercollider/issues/1738

One difference I think was that killing that shell would also kill the command on *nix (I think?), which wasn't the case on Windows before this PR.

> 
> Side note: I think it's a pretty strange design that `SequencableCollection-unixCmd` and `String-unixCmd` have different behavior. Personally, I would have given `String-unixCmd` a different name altogether, e.g. `String-shellCmd`.

Yeah, very strange. Incidentally, the issue describing `sh -c` also links to the SeqCollection-unixCmd addition: https://github.com/supercollider/supercollider/pull/3539

**Comment by Spacechild1** [comment]
> HOWEVER I remember previously seeing a separate sh shell being spun and getting a PID of that!

Yes, that's exactly what I would expect. In fact, I don't really see how `sh -c <command>` could possibly return the PID of `<command>`.

Thanks for the linked issue. I didn't know that `SequenceCollection -unixCmd` was added after `String -unixCmd`. They really should have picked a different name :)

**Comment by Spacechild1** [comment]
> I checked on current macOS and I can't see a separate shell and I get the PID of the actual process I'm runnig.

Can you share the command you used for testing?

**Comment by dyfer** [comment]
> Can you share the command you used for testing?

Sure! 
```supercollider
p = unixCmd("/Applications/SuperCollider_3.14-dev.app/Contents/Resources/scsynth" + s.options.asOptionsString, {"I'm done!".postln});
```

> Yes, that's exactly what I would expect. In fact, I don't really see how `sh -c <command>` could possibly return the PID of `<command>`.

I was also wondering if using `exec` in the command itself would've influenced it (sclang [does add `exec` in front of the scsynth executable](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Platform/osx/OSXPlatform.sc#L21) on *nix) but that's why I tested the confirm with a command without exec.

Just to re-iterate, I don't see an extra shell after running the command above.

BTW, if I run this in terminal:
```sh
sh -c "/Applications/SuperCollider_3.14-dev.app/Contents/Resources/scsynth -u 57110"
```
I also _don't see a new shell process_. 
Something specific to macOS maybe?

File: common/sc_popen.cpp (hunk 1 above)
Comment (dyfer) [reply common/sc_popen.cpp:171]: I renamed `sc_popen` to `sc_popen_shell`

File: common/sc_popen.cpp (hunk 2 above)
Comment (dyfer) [reply common/sc_popen.cpp]: Thanks! I removed `move`.

**Comment by Spacechild1** [comment]
> I was also wondering if using exec in the command itself would've influenced it (sclang [does add exec in front of the scsynth executable](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Platform/osx/OSXPlatform.sc#L21) on *nix)

That should be obsolete as we are using `SequencableCollection -unixCmd`. Should we go ahead and remove `exec` as part of this PR?

> I also don't see a new shell process in the Activity Monitor.

Interesting! Maybe `sh -c` automatically overlays the process with the last command? I need to check myself.

However, I definitely see the shell process on Linux, as I would expect!

Also, killing the shell process on Linux (with `Platform.killProcessByID` in sclang or `kill` in a terminal) does *not* automatically kill the child process. Contrary to popular believe, Linux does *not* automatically kill child processes when the parent process dies.

I am mentioning this because you've changed the Windows implementation of `Platform.killProcessByID` to kill all child processes. I'm not really against this change, but it should be mentioned in the docs that this behaves slightly different on Windows and Linux. Or could we maybe add a Boolean argument, e.g. `children`, that lets the user control the behavior?

On Linux, killing a process with all its child processes can be done with `pkill <PID>`. Note that the `pkill` command may not be present on some (older) systems, so we would need to check for the existance of `pkill` in `Platform.initClass`...

> EDIT: I realized that I didn't look into systemCmd, I wonder how that behaves regarding PIDs...

`systemCmd` is blocking, so it just returns the error code.

**Comment by dyfer** [comment]
> That should be obsolete as we are using `SequencableCollection -unixCmd`. Should we go ahead and remove `exec` as part of this PR?

Well, I haven't changed server boot to using `SequenceableCollection -unixCmd` in this PR. I think that should be a separate PR and there we could remove `exec`.


> However, I definitely see the shell process on Linux, as I would expect!
> 
> Also, killing the shell process on Linux (with `Platform.killProcessByID` in sclang or `kill` in a terminal) does **not** automatically kill the child process. Contrary to popular believe, Linux does _not_ automatically kill child processes when the parent process dies.

Ah! 
So does this work on Linux?
```supercollider
r = (Server.program + Server.default.options.asOptionsString).unixCmd; 
r.postln; // is this a pid of `sh -c` or of scsynth?
thisProcess.platform.killProcessByID(r); // did the server stop? or just the shell?
```
We have [code like this in the test suite](https://github.com/supercollider/supercollider/blob/develop/testsuite/classlibrary/TestServer_clientID_booted.sc#L162) and it does seem to work in CI... That particular test was the reason I went down chasing this in the first place, as it was freezing the testsuite on Windows.

> 
> I am mentioning this because you've changed the Windows implementation of `Platform.killProcessByID` to kill all child processes. I'm not really against this change, but it should be mentioned in the docs that this behaves slightly different on Windows and Linux. Or could we maybe add a Boolean argument, e.g. `children`, that lets the user control the behavior?
> 
> On Linux, killing a process with all its child processes can be done with `pkill <PID>`. Note that the `pkill` command may not be present on some (older) systems, so we would need to check for the existance of `pkill` in `Platform.initClass`...

Yea, we should clean this up on all platforms.

Curiously on macOS it works as advertised (I get a pid of the command), but let's check on Linux. It seems that the claim of returning PID of the command is not true there?

> `systemCmd` is blocking, so it just returns the error code.

Duh, of course. Thanks!

**Comment by Spacechild1** [comment]
> use ArrayedCollection -unixCmd in the class library, particularly in the Server class

Yes, please! Not only would it fix our particular issue with killing the Server on Windows, we could also get rid of that ugly `exec` command in `Server.program`.

**Comment by dyfer** [comment]
> > The scsynth command does not create a new shell. However, sh -c "yes > /dev/null" does create a new instance of bash. And indeed, killing bash does not kill the yes command.
> 
> Here's a wild guess: if `sh -c <command>` consists of a single command, macOS's shell implementation internally uses `exec` to replace the shell with that command as an optimization. It does not do that if there are multiple commands involved, which kind of makes sense.

Wow! Your guess is absolutely correct. This actually does start a new shell:
```sh
sh -c "/Applications/SuperCollider_3.14-dev.app/Contents/Resources/scsynth -u 57110 > /dev/null"
```
Needless to say, stopping that shell does not stop scsynth.

I'll proceed with other changes.

**Comment by dyfer** [comment]
Now this PR only fixes the `SequenceableCollection -unixCmd`.

File: common/sc_popen.cpp [hunk 3]
```diff
@@ -163,10 +163,11 @@ std::tuple<pid_t, FILE*> sc_popen_argv(const std::vector<std::string>& strings,
         strings.begin(), strings.end(), std::string(),
         [](const std::string& a, const std::string& b) -> std::string { return a + (a.length() > 0 ? " " : "") + b; });
 
-    return sc_popen(std::move(commandLine), type);
+    return sc_popen_c(commandLine.data(), type.data());
 }
 
-std::tuple<pid_t, FILE*> sc_popen(std::string&& command, const std::string& type) {
+std::tuple<pid_t, FILE*> sc_popen_shell(std::string&& command, const std::string& type) {
+    command = "cmd /c " + command;
```
Comment (Spacechild1) [inline common/sc_popen.cpp:170]: Modifying and reassinging to an rvalue reference is a bit funky. I think `sc_popen_shell` should just take `std::string` by value.

Generally, functions should only take arguments by rvalue reference if it *must* be an r-value reference, e.g. to distinguish a copy constructor from a move constructor. Another use case are "unversial references":
```
template<typename T>
void foo(T&& x);
```
Otherwise, just pass by value. The caller can still move into the function and the function itself can move the argument.

**Comment by Spacechild1** [comment]
Cool! Just a little code style comment from my side. Apart from that, this looks good and can be merged, at least from my side.

File: common/sc_popen.cpp (hunk 3 above)
Comment (dyfer) [reply common/sc_popen.cpp:170]: I know this is basic stuff, but it goes beyond my knowledge of cpp. I tried applying the change, is this what you meant?

Comment (dyfer) [reply common/sc_popen.cpp:170]: Also, I noticed that `sc_popen_shell()` on *nix uses moves the command string when passing the data to the vector. Is that done "just in case" or is there an actual reason for it?

Comment (Spacechild1) [reply common/sc_popen.cpp:170]: > I tried applying the change, is this what you meant?

Yes, thanks!

> Also, I noticed that sc_popen_shell() on *nix moves the command string when passing the data to the vector. Is that done "just in case" or is there an actual reason for it?

This is just a small performance optimization. `std::move` turns a normal reference into a rvalue-reference, so that the destination - here `std::vector::push_back` - knows that it can move from its argument. In case of `std::string` it can steal the underlying buffer instead of making a copy. (Does this actually matter in the context of spawning a subprocess? Probably not :)

**Comment by capital-G** [comment]
I haven't followed the whole thread, but I currently run into some problems using `.unixCmd` on macOS and switched to `.runInTerminal`, but this creates another set of problems...
E.g. `"wget -h".unixCmd(postOutput: true);` will not print anything to stdout, but `"ls".unixCmd(postOutput: true);` will do - seems inconsistent and in fact `wget` will not get executed at all - maybe this is a security feature of macOS as I could run some binaries but not all?

I haven't checked the source code of the popen implementation, but maybe we should switch to [`boost.Process`](https://www.boost.org/doc/libs/1_86_0/doc/html/process.html) in order to outsource the maintenance workload of multi-platform support?
It would be great to e.g. specify cwd or environment vars w/o patching the shell command - this also make multi-platform support easier.

<details>

BTW: TIL there is a difference on unix between using `"` and `'`

E.g.

```
HELLO=42 /bin/zsh -c "echo $HELLO"
```

will return nothing, but

```
HELLO=42 /bin/zsh -c 'echo $HELLO'
```

will return `42` - the difference is that `'` will not be evaluated in the current shell, but `"` will be evaluated and expanded by the surrounding shell.
</details>

**Comment by dyfer** [comment]
> E.g. `"wget -h".unixCmd(postOutput: true);` will not print anything to stdout, but `"ls".unixCmd(postOutput: true);` will do

~~I've had issues with the past with commands not posting, but that seemed to be due to them either flushing or not flushing their output (which I think is inferred from the environment they run in?)~~

Actually, for wget on macOS that's probably an issue with `$PATH`. I'm not sure what's the mechanism of inheriting the environment vars in SC, but I've found that homebrew-installed commands were sometimes not found when trying to run them in SC.

```supercollider
"wget -h".unixCmd({|err| "exit code: ".post; err.postln;}); 
```
^^ this posts 127, which I believe is "command not found".
However, this works on my macOS:
```supercollider
"/opt/homebrew/bin/wget -h".unixCmd;
```

I can't remember how I circumvented this in the past...


In any case, the total rework is maybe desirable, but should be a separate PR.

What I think is REALLY desirable is cleaning up unixCmd/systemCmd String/SequenceableCollection interface, it's quite confusing currently.

**Comment by dyfer** [comment]
@Spacechild1 if this looks good to you, could you approve the PR?

**Review by Spacechild1 — APPROVED** [review]
