### PR TITLE
[IDE] Fix detached docklet visibility bug

### LINKED ISSUE #3287: Detached, closed docklet partially reappears when launching the IDE
Starting the IDE with any of the docklets (Documents, Post Window, Help Browser) being **detached and closed** will show up as a *ghost* window (empty and unclosable).

deepinscreenshot_select-area_20180410201221

 
### Reproducer

- open, **detach** and **close** any docklet (View -> Docklets)
- close the IDE
- open the IDE again
- most of the time, see the *ghost* window in place of the closed docklet location

This happens at least on linux with some window manager (bug appears using `xfce4`, `icewm`, **not** with `awesome-wm`, ...).

------

Here, assuming the help browser is undocked --

It looks like the IDE's startup process always opens a window for the help browser. Then, if the IDE config file records that the help browser was closed when it last quit, it closes the browser window.

I found in the past, intermittently, that the IDE would try to close the help window before opening it -- leaving a non-functioning, non-painted window open. Before I can even close the window, I have to press Ctrl-D to load the main help page. Of course, the reason why I keep the help window closed is so that I don't have to index the help files unless I'm requesting help! So, this wastes time.

Since upgrading to 3.9 beta (built from source), I'm now finding that this race condition occurs roughly 90% of the time when I launch the IDE. So, it's changing from an occasional irritant into a constant WTF.

It's *reeeeeaaaalllllllllyyyyyyyy* annoying.

Ubuntu Studio 16.04, xfce 4.12, Qt 5.5.1 (from Ubuntu packages).

### PR DESCRIPTION
**Pull request by gusano**
Fix #3287 

This fixes what seems to be a weird race condition: when starting the IDE, a detached (and closed) docklet container can be raised just after it has been hidden, leading into a *ghost* unresponsive window (see linked issue).

I'm not sure this is the most elegant fix so I'm open to any hint if this needs to be done differently.

cc @jamshark70

### CODE REVIEW

File: editors/sc-ide/widgets/main_window.cpp [hunk 1]
```diff
@@ -67,6 +67,7 @@
 #include <QUrl>
 #include <QMimeData>
 #include <QMetaMethod>
+#include <QDebug>
```
Comment (gusano) [inline editors/sc-ide/widgets/main_window.cpp]: This is not directly related but it was missing.. Let me know if I should revert that one.

Comment (brianlheim) [reply editors/sc-ide/widgets/main_window.cpp]: if you included it for `qDebug()`, it's not really necessary as `qDebug` is a global feature: http://doc.qt.io/qt-5/qtglobal.html#qDebug

File: editors/sc-ide/widgets/util/docklet.hpp [hunk 2]
```diff
@@ -74,7 +74,7 @@ class Docklet : public QObject
         return const_cast<Docklet*>(this)->currentContainer() != mDockWidget;
     }
 
-    void setDetached( bool detached );
+    void setDetached( bool detached, bool visible = true );
```
Comment (brianlheim) [inline editors/sc-ide/widgets/util/docklet.hpp]: consider renaming this function; a call to "`setDetached( bool, bool )`" is opaque. suggestion - `setDetachedWithVisibility`. i don't think a default value for the second argument is a good idea, it will make calling code harder to understand.

**Comment by jamshark70** [comment]
I've just launched the IDE five times in a row, without a single ghost help browser appearing.

I'm crying.

Thank you @gusano !!!

I don't have much to say about code review. Sometime later I might suggest including some of the changes I was testing, specifically to defer MainWindow initialization by a QTimer. The bulk of it is here -- https://github.com/jamshark70/supercollider/commit/1cd6643aa2938d2eff5f0cf6d0adbf79689d8af6 -- but I would have to check if I added something functionally different in another branch.

The reason is: I also notice that the main IDE window "drifts" to the left when launching. I usually have the IDE window flush left on the screen, but often when I launch the IDE, the window's left margin is slightly offscreen. I found, when I was testing the suggestion from the Qt forum, that the window position was more accurate.

Using this PR as is, I still get the window-position problem.

I cherry picked the above commit and tested, but then it always shows the help browser. I think it's because of help_browser.hpp:

```
    void onInterpreterStart() {
        if (isVisible() && mHelpBrowser->url().isEmpty())
            mHelpBrowser->goHome();
    }
```

... where `isVisible()` is true, even if the window is supposed to be hidden.

But, come to think of it, window drift is another issue to log later.

I'd like to see this fix in 3.9 (currently based on develop).

**Comment by jamshark70** [comment]
FWIW https://github.com/supercollider/supercollider/commit/ecd59e16f203a82911fea00a20bbda70b8f85f48 cherry-picks cleanly onto 3.9, tested locally and it's good.

**Comment by brianlheim** [comment]
@jamshark70 - we aren't planning to do any more 3.9 releases (this has been mentioned a few times on the ML). if 3.10 takes longer than expected maybe we can do another patch release and backport some of the fixes

**Comment by gusano** [comment]
@brianlheim thanks! Force pushed with your suggestions.
@jamshark70 actually the first reason that made me have a look at this issue was that using `QTimer` sounded wrong to me :) Let's fix one bug at a time :japanese_ogre:

**Comment by jamshark70** [comment]
I agree this PR should fix just the one bug.

If QTimer is wrong, then I'm not clear why the IDE window is positioned incorrectly without it ;) but that's a question for another thread.
