### PR TITLE
Post window font

### LINKED ISSUE #7373: Unable to change font size in IDE Post window (shortcuts and context menu unresponsive)
## Environment

* SuperCollider version: 3.15.0-dev
* Operating system: All (macOS 15.7.4, Ubuntu 22.04.4, Windows 11)
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// No specific code required; the issue occurs directly in the IDE.

// 1. Open the SuperCollider IDE
// 2. Attempt to change the Post window font size using:
//    - Ctrl + +
//    - Ctrl + -
//    - Ctrl + 0
// 3. Alternatively, right‑click in the Post window and select:
//    - Enlarge Font
//    - Shrink Font
//    - Reset Font Size
```

## Expected vs. actual behaviour

**Expected:**  
The Post window font size should increase, decrease, or reset when using the keyboard shortcuts or the context‑menu options.

**Actual:**  
None of the font size controls has any effect.  
No error messages are shown.

**Note:**
On macOS, no keyboard shortcut appears when right‑clicking in the Post window.

### PR DESCRIPTION
**Pull request by stefandiaconu**
Fix enlarge font
Fix shrink font
Use lambda instead of pointer to member function as it doesn't preserve default arguments

## Purpose and Motivation

Fixes #7373

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

### CODE REVIEW

File: editors/sc-ide/widgets/post_window.cpp [hunk 1]
```diff
@@ -127,7 +129,7 @@ void PostWindow::createActions(Settings::Manager* settings) {
     connect(action, &QAction::triggered, this, &PostWindow::onAutoScrollTriggered);
     addAction(action);
     settings->addAction(action, "post-auto-scroll", postCategory);
-}
+}/**/
```
Comment (capital-G) [inline editors/sc-ide/widgets/post_window.cpp]: our formatter complains about this ;)

See https://github.com/supercollider/supercollider/wiki/Pre%E2%80%90commit on how to run the formatter locally somehow easily

```suggestion
}
```

**Review by capital-G — CHANGES_REQUESTED** [review]
Thanks - except for the unnecessary comment this is fine :)

**Review by capital-G — APPROVED** [review]
Thanks for this! Will merge this once the pipeline succeeds!

File: editors/sc-ide/widgets/post_window.cpp (hunk 1 above)
Comment (stefandiaconu) [reply editors/sc-ide/widgets/post_window.cpp]: Yes, I missed that. Probably I tried to use some key combinations and IDE added it. I'm still learning CLion :) I removed that and pushed a new commit
