### PR TITLE
[scsynth portaudio] allow independent input output devices

### LINKED ISSUE #3990: [enhancement] Support ServerOptions inDevice and outDevice in Windows
Environment
-----------

* Your SuperCollider version: 3.9.x
* Your operating system and version: Windows 2010

Expected Behavior
-----------------

Audio driver technologies typically found in Windows (e.g. MME, WASAPI, WDM) tend to publish inputs and outputs as separate devices, for instance:

```
MME : Microsoft Soundmapper - Input (device #0 with 2 ins 0 outs)
MME : Microsoft Soundmapper - Output (device #4 with 0 ins 2 outs)
```

(ASIO is an exception, which tends to show duplex devices.)

The user should be able to select two devices for duplex audio using the same interface supported in MacOS:

```
s.options.inDevice = "MME : Microsoft Soundmapper - Input";
s.options.outDevice = "MME : Microsoft Soundmapper - Output";
```

Probably a couple of restrictions would be needed: both devices must be the same driver type (unless we're certain PortAudio can handle input from MME and output to WASAPI, for instance), and both devices might need to be the same hardware interface. It all depends on what PortAudio can do.

Current Behavior
----------------

`inDevice` and `outDevice` are supported in MacOS only. Effectively, this means that Windows users must either use ASIO (and there are reports that asio4all can be flaky), or otherwise the only way they can choose devices is to set the system default in Windows's control panel.

Caveats: I'm not on Windows myself. If you specify one input or output device using `s.options.device`, *maybe* PortAudio will find the matching device and open them both. That seems pretty unlikely to me. What I do know for sure is that scsynth's `-H` argument can accept only one device name, while we see a *lot* of soundcards split among multiple virtual devices.

Also adding supernova tag (feature parity).

(Note also that it would make no sense to implement this for Linux, because JACK handles the soundcard connection and scsynth has no opportunity to override JACK's hardware device. `-H` is used as the name under which scsynth appears in JACK.)

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

This is a cleaned up version of #4009 focused on scsynth and documentation. See #4476  for supernova-related PR. Fixes #3990.

On Windows, scsynth was not able to select separate input and output devices (it accepted only single device name and tried to use it as both input and output). This essentially prevented manual device selection for anything other than soundcards with ASIO drivers. 

This PR allows independent device selection, provides documentation and improves automatic device selection with PortAudio.

Thanks to @jamshark70 @sonoro1234 and others who helped with the original PR. This is the summary of the discussion so far:
- the documentation was reviewed and seemed to be received favorably
- there has been a lot of back and forth w/r/t which API to use for selecting the default device
  - ~~there seemed to be a consensus that ASIO should be selected by default~~
  - ~~if ASIO device is not available,~~ 
  - MME device is selected by default 
    - this is the same behavior as before - more testing showed that sometimes non-working ASIO drivers are present on Windows system by default preventing server to boot
- there have been multiple tests done and booting the server is now much more reliable than before
- an issue of device names with unicode characters has been raised; this PR does _not_ address that (see below)

## Types of changes

- Bug fix: allow scsynth with PortAudio backend to select separate input and output devices
- ~~New feature~~ Bug fix: improve default device selection
  - if one device is specified, select another one from the same API
  - ~~if no devices are specified, *try selecting an ASIO device first*~~
  - if no devices are specified, select a MME device (as before)
  - provide more verbose output for all choices made
  - provide better error reporting, including e.g. catching mismatched sample rate between input and output devices
- Bug fix: treat empty strings as "invalid device" (triggering default device selection); previously empty string was causing scsynth to choose the last device on the list.
- Bug fix: remove hardcoded default sample rate 44100 on scsynth with PortAudio on Windows (it will boot to hardware's sample rate by default)
  - this resolves booting when the API doesn't allow changing SR and SR was not specified on the command line
  - ASIO still boots to 44100 by default, which seems to be ["by design" in PortAudio](https://lists.columbia.edu/pipermail/portaudio/2019-August/001893.html)
- Documentation: Provide new document describing audio device selection, including overview of different APIs on Windows

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review
- [x] commit history cleanup (to be done after the review and before merging)

## Unresolved issues

This PR does not solve setting device names for devices with unicode characters. Character encoding seems to be a larger issue. My work so far on it was moved to #4479. Partial names however are matched as before.

### CODE REVIEW

**Comment by sonoro1234** [comment]
Default selection working for ASIO and MME
`-o 0` and `-i 0` works
Not matching samplerates works but there is a crash after could not initialize audio
(I think not related to this PR as also happens when hitting Ctrl+C)
```
Requested devices:
  In (matching device found):
  - Windows WASAPI : Mic interno (IDT High Definition Audio CODEC)
  Out (matching device found):
  - Windows WASAPI : Line 1/2 (4- M-Audio Fast Track Pro)


Requested devices Mic interno (IDT High Definition Audio CODEC) and Line 1/2 (4- M-Audio Fast Track Pro) use different sample
 rates. Please set matching sample rates in the Windows Sound Control Panel and try again.
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Invalid sample rate'
could not initialize audio.
```
Now debugging crash

**Comment by dyfer** [comment]
@sonoro1234 thanks, this also had the bug you found https://github.com/supercollider/supercollider/pull/4476#discussion_r301052877 - fixed now.

File: server/scsynth/SC_PortAudio.cpp [hunk 1]
```diff
@@ -262,31 +264,199 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+                PaSampleFormat fmt = paFloat32 | paNonInterleaved;
+                PaStreamParameters parameters;
+                parameters.device = *inDevice;
+                parameters.sampleFormat = fmt;
+                parameters.hostApiSpecificStreamInfo = NULL;
+                parameters.channelCount = Pa_GetDeviceInfo(*inDevice)->maxOutputChannels;
+                PaError err = Pa_IsFormatSupported(&parameters, nullptr, sampleRate);
+                if (err != paNoError) {
+                    fprintf(stdout, "PortAudio error: %s\nRequested sample rate %f for device %s is not supported\n",
+                            Pa_GetErrorText(err), sampleRate, Pa_GetDeviceInfo(*outDevice)->name);
```
Comment (sonoro1234) [inline server/scsynth/SC_PortAudio.cpp]: inDevice

File: server/scsynth/SC_PortAudio.cpp [hunk 2]
```diff
@@ -262,31 +264,199 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+                PaStreamParameters parameters;
+                parameters.device = *outDevice;
+                parameters.sampleFormat = fmt;
+                parameters.hostApiSpecificStreamInfo = NULL;
+                parameters.channelCount = Pa_GetDeviceInfo(*outDevice)->maxOutputChannels;
+                PaError err =
+                    Pa_IsFormatSupported(nullptr, &parameters, Pa_GetDeviceInfo(*outDevice)->defaultSampleRate);
+                if (err != paNoError) {
+                    fprintf(stdout, "PortAudio error: %s\nRequested sample rate %f for device %s is not supported\n",
+                            Pa_GetErrorText(err), sampleRate, Pa_GetDeviceInfo(*inDevice)->name);
```
Comment (sonoro1234) [inline server/scsynth/SC_PortAudio.cpp]: outDevice

**Comment by sonoro1234** [comment]
Cant debug this because only happens with my WASAPI devices but I can reach them compiling with mingw

**Comment by dyfer** [comment]
Could you give a full scsynth output for the WASAPI issue?

**Comment by sonoro1234** [comment]
It is not a WASAPI issue. The issue is a crash when not possible to boot.
I got one with ASIO and samplerate 11200 
```
Requested sample rate 11200.000000 for devices Fast Track Pro ASIO and Fast Track Pro ASIO is not supported.
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Invalid sample rate'
could not initialize audio.
[Thread 4388.0xa80 exited with code 1]
[Thread 4388.0x14ec exited with code 1]
[Thread 4388.0x16f0 exited with code 1]
[Thread 4388.0x17d0 exited with code 1]
[Thread 4388.0x13a4 exited with code 1]
[Thread 4388.0x14cc exited with code 1]
[Thread 4388.0xa58 exited with code 1]
terminate called without an active exception

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[Inferior 1 (process 4388) exited with code 01]
(gdb) thread apply all bt
(gdb)
```
There is not information in gdb. I think that it is related to exception handling in scsynth.

**Comment by dyfer** [comment]
Are you requesting sample rate 11200? I've seen issues booting to SR < 44100 (like 8000) and I don't know what's the problem. Does this happen with the regular build as well?

**Comment by sonoro1234** [comment]
> Are you requesting sample rate 11200? I've seen issues booting to SR < 44100 (like 8000) and I don't know what's the problem. Does this happen with the regular build as well?

This is not a problem, my ASIO card wont boot with 11200, I just asked for this impossible samplerate to debug the crash after `could not initialize audio.`

**Comment by dyfer** [comment]
Note on selecting ASIO soundcard by default: I had an opportunity to do more tests on other systems. I found at least one other Windows laptop that had Realtek ASIO driver present (for the internal soundcard), and booting to this did not work.

Therefore, I removed selecting ASIO device by default. Now there are still more checks that help with device selection, but the default behavior (selecting default MME device) is the same as before.

File: include/server/SC_WorldOptions.h [hunk 3]
```diff
@@ -56,11 +56,7 @@ struct WorldOptions {
     const char* mNonRealTimeOutputHeaderFormat = nullptr;
     const char* mNonRealTimeOutputSampleFormat = nullptr;
 
-#if defined(_WIN32)
-    uint32 mPreferredSampleRate = 44100;
-#else
     uint32 mPreferredSampleRate = 0;
-#endif
```
Comment (brianlheim) [inline include/server/SC_WorldOptions.h]: after reading your PR description i'm still unclear on whether this is actually a breaking change or not

File: HelpSource/Reference/AudioDeviceSelection.schelp [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+By default the server will boot to your system's default audio devices using teletype::MME:: driver (which usually means higher latency).
+
+On Windows there are multiple audio driver APIs (e.g. teletype::MME::, teletype::WASAPI::, teletype::ASIO:: etc.) that can be used to communicate with audio devices. The API (listed before the device name) needs to match between the input and the output, for example:
+code::
+o = Server.default.options;
+o.inDevice_("Windows WASAPI : Microphone");
+o.outDevice_("Windows WASAPI : Speakers");
+Server.default.reboot;
+::
+On Windows you strong::cannot:: programmatically obtain the list of available audio devices. However, all the devices are listed in the post window when the server is booting: code::Server.default.boot::
```
Comment (brianlheim) [inline HelpSource/Reference/AudioDeviceSelection.schelp]: just to be clear -- you _can_ get this list, just not in sclang, right?

File: HelpSource/Reference/AudioDeviceSelection.schelp [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+::
+## MME
+||
+LIST::
+## strong::Multichannel operation: :: Usually no
+## strong::Typical latency: :: High
+## strong::Caveats: :: It is the oldest API on this list; it is chosen by default if the user does not specify which device to use
+## strong::More info: :: This API might work out-of-the-box, but choosing a newer one instead will usually provide better performance; MME stands for Multimedia Extension (for Windows 3.0)
+::
+::
```
Comment (brianlheim) [inline HelpSource/Reference/AudioDeviceSelection.schelp]: would this work better as a table?

File: HelpSource/Reference/AudioDeviceSelection.schelp [hunk 6]
```diff
@@ -0,0 +1,184 @@
+title:: Audio device selection
```
Comment (brianlheim) [inline HelpSource/Reference/AudioDeviceSelection.schelp]: not a problem to be solved here, but since lots of people use scsynth separately, it would be great if this were documented somewhere with scsynth.

File: server/scsynth/scsynth_main.cpp [hunk 7]
```diff
@@ -253,17 +253,13 @@ int main(int argc, char* argv[]) {
...
-#ifdef __APPLE__
             if (i + 1 > argc || argv[j + 2][0] == '-') {
                 options.mOutDeviceName = options.mInDeviceName;
             } else {
                 // If there's a second argument then the user wants separate I/O devices
                 options.mOutDeviceName = argv[j + 2];
                 ++i;
             }
-#else
-            options.mOutDeviceName = options.mInDeviceName; // Non-Mac platforms always use same device
```
Comment (brianlheim) [inline server/scsynth/scsynth_main.cpp]: what in this PR allows this to work right on Linux?

File: server/scsynth/SC_PortAudio.cpp [hunk 8]
```diff
@@ -262,31 +264,199 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
         strcat(devString, " : ");
+#endif
         strcat(devString, pdi->name);
-        if (strstr(devString, device)) {
-            if (pdi->maxInputChannels > 0)
-                mInOut[0] = i;
-            if (pdi->maxOutputChannels > 0)
-                mInOut[1] = i;
+        // compare strings, but if the string is not empty
+        if (strstr(devString, device) && device && device[0]) {
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: You may specify `-H "" "output device name"` to select only output device. AFAIU empty string makes a match with every other string, while in our case should mean we don't find matching device.

You are right that we're calling this function after checking for device to not be null, should I remove `&& device` from this statement?

File: server/scsynth/SC_PortAudio.cpp [hunk 9]
```diff
@@ -262,31 +264,199 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
         }
     }
 }
 
+// this function will select default PA devices if they are not defined
+// it will also try to check for some configuration problems
+// numIns, numOuts and sampleRate are only the requested values, can change later
+PaError SC_PortAudioDriver::CheckPaDevices(int* inDevice, int* outDevice, int numIns, int numOuts, double sampleRate) {
+    // make independent checks whether we are using only input, only output, or both input and outputTouched
+    if (numIns && !numOuts) {
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: do you mean something like this? 
```c++
if (numIns) {
  if (numOuts) {
     // we have ins and outs
  } else {
    // we have only ins
} else if (numOuts) {
  // we have only outs
}
```
or something else?

File: server/scsynth/SC_PortAudio.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: in that case, why don't you just exit immediately if `device` is empty? it's invariant within the loop.

File: server/scsynth/SC_PortAudio.cpp [hunk 10]
```diff
@@ -404,6 +603,7 @@ bool SC_PortAudioDriver::DriverSetup(int* outNumSamples, double* outSampleRate)
     }
 
     // should not be necessary, but a last try with OpenDefaultStream...
+    fprintf(stdout, "\nNo devices specified, attempting to use default system devices\n");
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: OK, I'll remove the comment. 

Actually, after analyzing this code, we were never reaching that point anyway - `mDeviceInOut` `[0]` and `[1]` were populated by `Pa_GetDefaultIn(Out)putDevice();` even before my refactoring. The only time we would get here was is we would get `noPaDevice` from `Pa_GetDefault...` function (not sure if it's possible?).

But maybe I'm missing some edge case? That's why I was not removing this whole block.

File: server/scsynth/SC_PortAudio.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: i mean that this code should look like this:

```cpp
if (numIns && !numOuts) {
    DoOnlyHaveOneIOType(inputData1, outputData2, inputData3);
} else if (! numIns && numOuts) {
    DoOnlyHaveOneIOType(outputData1, inputData2, outputData3);
} else if ...
```

since both branches do the same thing, but with input/output swapped, you can abstract them into a single function.

File: HelpSource/Reference/AudioDeviceSelection.schelp (hunk 4 above)
Comment (dyfer) [reply HelpSource/Reference/AudioDeviceSelection.schelp]: Correct - not in sclang nor in scsynth. From the sclang user perspective you can't get it with the software we're providing, that's why this wording. Is that reasonable?

Of course you can get it from the PortAudio backend, that's what scsynth does to list devices in the console.

File: server/scsynth/SC_PortAudio.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: > The only time we would get here was is we would get noPaDevice from Pa_GetDefault... function (not sure if it's possible?).

It appears to be - http://portaudio.com/docs/v19-doxydocs/portaudio_8h.html#abf9f2f82da95553d5adb929af670f74b

File: HelpSource/Reference/AudioDeviceSelection.schelp (hunk 4 above)
Comment (brianlheim) [reply HelpSource/Reference/AudioDeviceSelection.schelp]: I would just add "available audio devices _in sclang_." at the end of that sentence. Otherwise it sounds a bit confusing, like it's fundamentally impossible (which wouldn't surprise me with Windows :) ).

File: HelpSource/Reference/AudioDeviceSelection.schelp (hunk 5 above)
Comment (dyfer) [reply HelpSource/Reference/AudioDeviceSelection.schelp]: Nope, I tried this. It was not looking good as I was not able to control the table's spacing. Unfortunately the original commits were rebased so I can't demonstrate easily.

File: server/scsynth/scsynth_main.cpp (hunk 7 above)
Comment (dyfer) [reply server/scsynth/scsynth_main.cpp]: There's no reason to arbitrarily make assumption about not being able to specify input and output devices independently. If you select a single device with the -H parameter, it will be used for both input and output.

I haven't tested ALSA to confirm options on linux, but I see no harm removing this limitation on that platform as well.

File: include/server/SC_WorldOptions.h (hunk 3 above)
Comment (dyfer) [reply include/server/SC_WorldOptions.h]: The problem is that it's hard to tell.

On the systems that I've tested, the default MME devices report 44100 as default sample rate, so the behavior stayed the same. 
There might be devices out there that will report different sample rate by default (their hardware sample rate ideally) which will make the default behavior different. 

This really only applies to default devices, or ASIO devices. I'll test again with ASIO to see if there's a difference in behavior.

**Comment by dyfer** [comment]
Thanks for the review @brianlheim ! I'll work on implementing changes.

Also, Travis CI is failing on an arithmetic unit test... not sure what's that about...

File: HelpSource/Reference/AudioDeviceSelection.schelp (hunk 5 above)
Comment (brianlheim) [reply HelpSource/Reference/AudioDeviceSelection.schelp]: ok! I believe you :)

File: server/scsynth/scsynth_main.cpp (hunk 7 above)
Comment (brianlheim) [reply server/scsynth/scsynth_main.cpp]: cool, thanks for the explanation!

**Comment by brianlheim** [comment]
> Thanks for the review @brianlheim ! I'll work on implementing changes.

Thanks! Let me know if you have any more questions or if any comments were unclear

> Also, Travis CI is failing on an arithmetic unit test... not sure what's that about...

Not sure either, I just restarted the job. Don't worry about it.

**Comment by dyfer** [comment]
> Thanks! Let me know if you have any more questions or if any comments were unclear

Thanks! Things are rather clear, I'll just need a bit of time to work on this and will ask you if I have questions along the way.

File: include/server/SC_WorldOptions.h (hunk 3 above)
Comment (dyfer) [reply include/server/SC_WorldOptions.h]: I tested with ASIO driver on Behringer UMC404 soundcard. Server still boots to 44100, even if the device runs at a different sample rate. This is likely driver/device dependent, but so far it looks like in most cases server boots to 44100 still.

**Comment by dyfer** [comment]
Hi @brianlheim, I tried to address your comments. Please let me know how this looks now.

Also, I created a [function to get stream parameters](https://github.com/supercollider/supercollider/pull/4475/files#diff-98d9dae5034e95458cdf63989e5ea177R308) to simplify some of the new code. Should I also use it in the [DriverSetup section](https://github.com/supercollider/supercollider/blob/c8bd2d29f3efa870f5de7e10a40e6e8a5c212978/server/scsynth/SC_PortAudio.cpp#L535) (which would be a work towards implementing your other [suggestion](https://github.com/supercollider/supercollider/pull/4477#pullrequestreview-261505635)) or should that be left for #4477?

File: server/scsynth/SC_PortAudio.cpp [hunk 11]
```diff
@@ -303,25 +450,61 @@ bool SC_PortAudioDriver::DriverSetup(int* outNumSamples, double* outSampleRate)
...
-        mDeviceInOut[0] = Pa_GetDefaultInputDevice();
-    if (mDeviceInOut[1] == paNoDevice)
-        mDeviceInOut[1] = Pa_GetDefaultOutputDevice();
+        GetPaDeviceFromName(mWorld->hw->mInDeviceName, &mDeviceInOut[0], IOType::Input);
+    if (mWorld->hw->mOutDeviceName)
+        GetPaDeviceFromName(mWorld->hw->mOutDeviceName, &mDeviceInOut[1], IOType::Output);
+
+    // report requested devices
+    fprintf(stdout, "\nRequested devices:\n");
+    if (mWorld->mNumInputs) {
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: Right now these are single lines within each block, should I still factor these?

File: server/scsynth/SC_PortAudio.cpp [hunk 12]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+    std::string name;
+#ifndef __APPLE__
     const PaHostApiInfo* apiInfo;
-    char devString[256];
+    apiInfo = Pa_GetHostApiInfo(pdi->hostApi);
+    name.append(apiInfo->name);
+    name.append(" : ");
+#endif
+    name.append(pdi->name);
+    return name;
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: You can reduce this function to:

```cpp
  std::string name;
#ifndef __APPLE__
  name += Pa_GetHostApiInfo(pdi->hostApi)->name;
  name += " : ";
#endif
  name += Pa_GetDeviceInfo(index)->name;
  return name;
```

File: server/scsynth/SC_PortAudio.cpp [hunk 13]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
-            if (pdi->maxOutputChannels > 0)
-                mInOut[1] = i;
+PaStreamParameters SC_PortAudioDriver::GetPaStreamParameters(int* device, int channelCount, double suggestedLatency) {
+    PaStreamParameters streamParams;
+    PaSampleFormat fmt = paFloat32 | paNonInterleaved;
+    streamParams.device = *device;
+    streamParams.channelCount = channelCount;
+    streamParams.sampleFormat = fmt;
+    if (suggestedLatency)
+        streamParams.suggestedLatency = suggestedLatency;
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: just assign this directly -- this is a POD (plain old data, i.e. no constructor) so if you don't assign anything to suggestedLatency it will be uninitialized and garbage

Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: additionally, the first function parameter can be plain int, no need to pass a pointer

File: server/scsynth/SC_PortAudio.cpp [hunk 14]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+            fprintf(stdout, "Requested devices %s and %s use different API. ", GetPaDeviceName(*inDevice).c_str(),
+                    GetPaDeviceName(*outDevice).c_str());
+            *outDevice = Pa_GetHostApiInfo(Pa_GetDeviceInfo(*inDevice)->hostApi)->defaultOutputDevice;
+            fprintf(stdout, "Setting output device to %s.\n", GetPaDeviceName(*outDevice).c_str());
+        }
+        // check for matching sampleRate or requested sample rate
+        if (*inDevice != paNoDevice && *outDevice != paNoDevice) {
+            PaStreamParameters in_parameters, out_parameters;
+            in_parameters = GetPaStreamParameters(inDevice, Pa_GetDeviceInfo(*inDevice)->maxInputChannels, 0);
+            out_parameters = GetPaStreamParameters(outDevice, Pa_GetDeviceInfo(*outDevice)->maxOutputChannels, 0);
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: can declare these variables much more simply -- `const auto in_params = GetPaStreamParameters(...);` in both cases

File: server/scsynth/SC_PortAudio.cpp [hunk 15]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+                }
+            }
+        }
+
+        // in case we still don't have a proper device, use the default device
+        if (*inDevice == paNoDevice || *outDevice == paNoDevice) {
+            *inDevice = Pa_GetDefaultInputDevice();
+            *outDevice = Pa_GetDefaultOutputDevice();
+            if (*inDevice != paNoDevice && *outDevice != paNoDevice)
+                fprintf(stdout, "Selecting default system input/output devices\n");
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: should there be an else here?

File: server/scsynth/SC_PortAudio.cpp [hunk 16]
```diff
@@ -303,25 +468,47 @@ bool SC_PortAudioDriver::DriverSetup(int* outNumSamples, double* outSampleRate)
...
     *outNumSamples = mWorld->mBufLength;
     if (mPreferredSampleRate)
         *outSampleRate = mPreferredSampleRate;
-    else
-        *outSampleRate = 44100.;
+    else {
+        if (mDeviceInOut[0] != paNoDevice)
+            *outSampleRate = Pa_GetDeviceInfo(mDeviceInOut[0])->defaultSampleRate;
+        if (mDeviceInOut[1] != paNoDevice)
+            *outSampleRate = Pa_GetDeviceInfo(mDeviceInOut[1])->defaultSampleRate;
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: is this right?

Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: It is... intended - outSampleRate is _the_ sample rate.

In case we only have input device (i.e. no output), then query input for sampleRate. If we have both input and output, or just the output, then use output device to get the sample rate.

File: server/scsynth/SC_PortAudio.cpp (hunk 15 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: I thought not.

If the device selection fails for some reason (and devices are still `paNoDevice`) then function continues/exits without setting devices. If that happens, then the [DriverSetup](https://github.com/dyfer/supercollider/blob/topic/scsynth-portaudio-input-output-devices/server/scsynth/SC_PortAudio.cpp#L459) continues to [OpenDefaultStream](https://github.com/dyfer/supercollider/blob/topic/scsynth-portaudio-input-output-devices/server/scsynth/SC_PortAudio.cpp#L600) making one last attempt to open default devices. Is that OK?

File: server/scsynth/SC_PortAudio.cpp [hunk 17]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+}
+
+void SC_PortAudioDriver::GetPaDeviceFromName(const char* device, int* mInOut, IOType ioType) {
+    const PaDeviceInfo* pdi;
     PaDeviceIndex numDevices = Pa_GetDeviceCount();
-    mInOut[0] = paNoDevice;
-    mInOut[1] = paNoDevice;
+    *mInOut = paNoDevice;
+
+    if (device) {
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: Sorry for misunderstanding, I this I get it now.

File: server/scsynth/SC_PortAudio.cpp [hunk 18]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+        }
+
+        if (*device != paNoDevice)
+            fprintf(stdout, "Selecting default system %s device\n", (isInput ? "input" : "output"));
+    }
+    return paNoError;
+}
+
+void SC_PortAudioDriver::SelectMatchingPaDevice(int* matchingDevice, int* knownDevice, IOType matchingDeviceType) {
+    if (*matchingDevice == paNoDevice && *knownDevice != paNoDevice) {
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: like this?
```c++
if (*matchingDevice != paNoDevice || *knownDevice == paNoDevice)
        break;

    const PaHostApiInfo* apiInfo;
    ...
```

File: server/scsynth/SC_PortAudio.cpp [hunk 19]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+        // check for requested sample rate or select the default device
+        return CheckSinglePaDevice(outDevice, sampleRate, IOType::Output);
+    } else if (numIns && numOuts) {
+        // inputs and outputs
+        // if one device is specified, let's try to open another one on matching api
+        // try matching input to output
+        SelectMatchingPaDevice(inDevice, outDevice, IOType::Input);
+        // then try matching output to input
+        SelectMatchingPaDevice(outDevice, inDevice, IOType::Output);
+        // check if devices are having mismatched API, but only if they are defined
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: I removed some of them. 

My intent was to indicate logic in choosing devices, since there is more steps to it then just "give me selected device or the default one". I can see what you say, but I don't know what's the right balance here. I'm happy to remove other comments if you think that's optimal.

File: server/scsynth/SC_PortAudio.cpp [hunk 20]
```diff
@@ -88,7 +89,12 @@ class SC_PortAudioDriver : public SC_AudioDriver {
                           const PaStreamCallbackTimeInfo* timeInfo, PaStreamCallbackFlags statusFlags);
 
 private:
-    void GetPaDeviceFromName(const char* device, int* mInOut);
+    void GetPaDeviceFromName(const char* device, int* mInOut, IOType ioType);
+    std::string GetPaDeviceName(int index);
+    PaError CheckPaDevices(int* inDevice, int* outDevice, int numIns, int numOuts, double sampleRate);
+    PaError CheckSinglePaDevice(int* device, double sampleRate, IOType ioType);
+    void SelectMatchingPaDevice(int* matchingDevice, int* knownDevice, IOType matchingDeviceType);
+    PaStreamParameters GetPaStreamParameters(int* device, int channelCount, double suggestedLatency);
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: Seems like all of them? But my understanding of this is hazy. Let me know if I got this right.

File: server/scsynth/SC_PortAudio.cpp [hunk 21]
```diff
@@ -262,39 +268,198 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+    streamParams.device = *device;
+    streamParams.channelCount = channelCount;
+    streamParams.sampleFormat = fmt;
+    if (suggestedLatency)
+        streamParams.suggestedLatency = suggestedLatency;
+    streamParams.hostApiSpecificStreamInfo = nullptr;
+    return streamParams;
+}
+
+PaError SC_PortAudioDriver::CheckSinglePaDevice(int* device, double sampleRate, IOType ioType) {
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: I made the suggested change.

I had to add additional check to `Pa_GetDeviceInfo(*xxDevice)->maxXxxputChannels` whether the device is valid. 

Is this better?

**Comment by dyfer** [comment]
Thank you for your (partial?) review Brian!

I also have a question regarding `IOType` [here](https://github.com/dyfer/supercollider/blob/topic/scsynth-portaudio-input-output-devices/server/scsynth/SC_PortAudio.cpp#L347). 

Which is better:
```c++
bool isInput; //if matchingDeviceType is hypothetically neither Input nor Output, this stays unititialized
if (matchingDeviceType == IOType::Input)
    isInput = true;
else if (matchingDeviceType == IOType::Output)
    isInput = false;

if (isInput) {
    // do on input
} else {
    // do on output
}
fprintf(stdout, "this is %s\n", (isInput ? "input" : "output"));
```

vs

```c++
bool isInput = false; //we don't check whether it's IOType::Output or something else
if (matchingDeviceType == IOType::Input)
    isInput = true; 

if (isInput) {
    // do on input
} else {
    // do on output
}
fprintf(stdout, "this is %s\n", (isInput ? "input" : "output"));
```

vs

```c++

if (matchingDeviceType == IOType::Input) {
    // do on input
} else if (matchingDeviceType == IOType::Output) {
    // do on output
}
fprintf(stdout, "this is %s\n", ((matchingDeviceType == IOType::Input) ? "input" : "output")); //we don't check whether it's IOType::Output or something else
```

File: server/scsynth/SC_PortAudio.cpp (hunk 20 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: you did :) c++ has the unfortunate flaw of not having const-by-default functions and variables

File: server/scsynth/SC_PortAudio.cpp (hunk 19 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: the only comment here that is useful IMO is `// if one device is specified, let's try to open another one on matching api`, the rest just gets in the way of understanding and can be easily figured out from context. Good comments should "tell why, not how".

File: server/scsynth/SC_PortAudio.cpp (hunk 16 above)
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: ok, just confirming. a clearer way to write this is: 

```cpp
    if (mPreferredSampleRate)
        *outSampleRate = mPreferredSampleRate;
    else if (mDeviceInOut[1] != paNoDevice)
        *outSampleRate = Pa_GetDeviceInfo(mDeviceInOut[1])->defaultSampleRate;
    else if (mDeviceInOut[0] != paNoDevice)
        *outSampleRate = Pa_GetDeviceInfo(mDeviceInOut[0])->defaultSampleRate;
```

btw, won't you be leaving `outSampleRate` unset if both devices are no-device? IIUC it will then be used in that call to [`Pa_OpenDefaultStream`](https://github.com/dyfer/supercollider/blob/topic/scsynth-portaudio-input-output-devices/server/scsynth/SC_PortAudio.cpp#L585) you mentioned before; you probably want to have set this to some reasonable value for that call.

File: server/scsynth/SC_PortAudio.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: never mind, fine as is

File: include/server/SC_WorldOptions.h (hunk 3 above)
Comment (brianlheim) [reply include/server/SC_WorldOptions.h]: Thanks for investigating!

File: server/scsynth/SC_PortAudio.cpp (hunk 15 above)
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: make sense, thanks for the explanation!

File: server/scsynth/SC_PortAudio.cpp [hunk 22]
```diff
@@ -262,39 +270,181 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+        auto* pdi = Pa_GetDeviceInfo(i);
+        std::string devString = GetPaDeviceName(i);
+        if (strstr(devString.c_str(), device)) {
+            if (ioType == IOType::Input && pdi->maxInputChannels > 0) {
+                *mInOut = i;
+                break;
+            } else if (ioType == IOType::Output && pdi->maxOutputChannels > 0) {
+                *mInOut = i;
+                break;
+            }
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: OK, sorry for iterating but it took some time to see what this function is actually trying to do. Here is an idiomatic C++ way to write it:

```cpp

int SC_PortAudioDriver::GetPaDeviceFromName(const char* device, IOType ioType) const {
    if (device == nullptr || device[0] == '\0')
        return paNoDevice;

    PaDeviceIndex numDevices = Pa_GetDeviceCount();
    for (int i = 0; i < numDevices; i++) {
        auto* pdi = Pa_GetDeviceInfo(i);
        std::string devString = GetPaDeviceName(i);
        if (strstr(devString.c_str(), device)) {
            if (ioType == IOType::Input && pdi->maxInputChannels > 0) {
                return i;
            } else if (ioType == IOType::Output && pdi->maxOutputChannels > 0) {
                return i;
            }
        }
    }

    return paNoDevice;
}
```

note:
- return value is actually returned from function rather than passed in via pointer
- null check moves inside this function
- clearer behavior when no device is found

this means that at the call site below you can directly write:

```cpp
    mDeviceInOut[0] = GetPaDeviceFromName(mWorld->hw->mInDeviceName, &mDeviceInOut[0], IOType::Input);
    mDeviceInOut[1] = GetPaDeviceFromName(mWorld->hw->mOutDeviceName, &mDeviceInOut[1], IOType::Output);
```

File: server/scsynth/SC_PortAudio.cpp [hunk 23]
```diff
@@ -262,39 +270,181 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
         }
     }
 }
 
+PaStreamParameters SC_PortAudioDriver::GetPaStreamParameters(int device, int channelCount,
+                                                             double suggestedLatency) const {
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: You always pass 0 for `suggestedLatency` -- you can remove this parameter and hard-code it, I think. Also, I generally prefer "MakeXYZ" for functions that are essentially wrappers for object construction.

File: server/scsynth/SC_PortAudio.cpp [hunk 24]
```diff
@@ -262,39 +270,181 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+    streamParams.channelCount = channelCount;
+    streamParams.sampleFormat = fmt;
+    streamParams.suggestedLatency = suggestedLatency;
+    streamParams.hostApiSpecificStreamInfo = nullptr;
+    return streamParams;
+}
+
+template <typename SupportCheck> // expected signature: PaError (*)(PaStreamParameters&, double)
+PaError SC_PortAudioDriver::CheckSinglePaDevice(int* device, double sampleRate, int maxChannels, int defaultDevice,
+                                                SupportCheck isSupportedFunc, const char* deviceType) const {
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: generally it's good to put lambda parameters last in a parameter list, since it can look awkward when the lambdas are written inline.

File: server/scsynth/SC_PortAudio.cpp [hunk 25]
```diff
@@ -262,39 +270,181 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+    if (matchingDeviceType == IOType::Input)
+        isInput = true;
+    else if (matchingDeviceType == IOType::Output)
+        isInput = false;
+
+    if (isInput) {
+        *matchingDevice = apiInfo->defaultInputDevice;
+    } else {
+        *matchingDevice = apiInfo->defaultOutputDevice;
+    }
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: grr, i've been going back and forth on the best way to handle this function. first of all, I think a more appropriate name would be something that indicates that the function may not do anything. "TryMatchUnspecifiedDevice"? "Try" would be a good word to have in the function name in any case. It also indicates that the function is encapsulating not just the matching, but the checks that happen prior to it.

`const int* knownDevice` in the parameter list would make it immediately much clearer which variable is the output and which is the input.

the way you set `isInput` is a little too careful -- we have control over all the uses of this function, it's easy to confirm that you will only ever have one or the other.

A more compact but still straightforward way to write this block would be:

```cpp
    auto* apiInfo = Pa_GetHostApiInfo(Pa_GetDeviceInfo(*knownDevice)->hostApi);
    bool isInput = matchingDeviceType == IOType::Input;
    *matchingDevice = isInput ? apiInfo->defaultInputDevice : apiInfo->defaultOutputDevice;
```

in fact, I would say this is even clearer -- the data flow is not interrupted by `if`s, and it's clear that the goal is to set `matchingDevice`. 3 lines instead of your current 14. up to you if you want to change it; though I'd at least recommend not using 5 lines to set `isInput` when 1 would do.

File: server/scsynth/SC_PortAudio.cpp [hunk 26]
```diff
@@ -262,39 +270,181 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+// numIns, numOuts and sampleRate are only the requested values, can change later
+PaError SC_PortAudioDriver::CheckPaDevices(int* inDevice, int* outDevice, int numIns, int numOuts,
+                                           double sampleRate) const {
+    if (numIns && !numOuts) {
+        *outDevice = paNoDevice;
+        // check for requested sample rate or select the default device
+        return CheckSinglePaDevice(
+            inDevice, sampleRate, (*inDevice != paNoDevice) ? Pa_GetDeviceInfo(*inDevice)->maxInputChannels : 0,
+            Pa_GetDefaultInputDevice(),
+            [](PaStreamParameters& params, double sr) { return Pa_IsFormatSupported(&params, nullptr, sr); }, "input");
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: this is looking a lot better! I think if you move this subexpression out before the call to CheckSinglePaDevice(), it will be a little clearer:

```cpp
auto maxChannels = (*inDevice != paNoDevice) ? Pa_GetDeviceInfo(*inDevice)->maxInputChannels : 0;
return CheckSinglePaDevice(inDevice, sampleRate, maxChannels, Pa_GetDefaultInputDevice(), "input", 
    [](PaStreamParameters& params, double sr) { return Pa_IsFormatSupported(&params, nullptr, sr); });
```

same goes for the branch below

File: server/scsynth/SC_PortAudio.cpp [hunk 27]
```diff
@@ -262,39 +270,181 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+            outDevice, sampleRate, (*outDevice != paNoDevice) ? Pa_GetDeviceInfo(*outDevice)->maxOutputChannels : 0,
+            Pa_GetDefaultOutputDevice(),
+            [](PaStreamParameters& params, double sr) { return Pa_IsFormatSupported(nullptr, &params, sr); }, "output");
+    } else if (numIns && numOuts) {
+        // if one device is specified, let's try to open another one on matching api
+        SelectMatchingPaDevice(inDevice, outDevice, IOType::Input);
+        SelectMatchingPaDevice(outDevice, inDevice, IOType::Output);
+
+        if (*inDevice != paNoDevice && *outDevice != paNoDevice
+            && Pa_GetDeviceInfo(*inDevice)->hostApi != Pa_GetDeviceInfo(*outDevice)->hostApi) {
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: (suggestion) consider assigning this entire condition to a named bool before using it in the `if`, it could read clearer:

```cpp
bool apisAreDifferent = *inDevice != paNoDevice && *outDevice != paNoDevice
            && Pa_GetDeviceInfo(*inDevice)->hostApi != Pa_GetDeviceInfo(*outDevice)->hostApi;
if (apisAreDifferent) {
    ...
```

File: server/scsynth/SC_PortAudio.cpp [hunk 28]
```diff
@@ -262,39 +270,181 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+                    GetPaDeviceName(*outDevice).c_str());
+            *outDevice = Pa_GetHostApiInfo(Pa_GetDeviceInfo(*inDevice)->hostApi)->defaultOutputDevice;
+            fprintf(stdout, "Setting output device to %s.\n", GetPaDeviceName(*outDevice).c_str());
+        }
+        // check for matching sampleRate or requested sample rate
+        if (*inDevice != paNoDevice && *outDevice != paNoDevice) {
+            const auto in_parameters =
+                GetPaStreamParameters(*inDevice, Pa_GetDeviceInfo(*inDevice)->maxInputChannels, 0);
+            const auto out_parameters =
+                GetPaStreamParameters(*outDevice, Pa_GetDeviceInfo(*outDevice)->maxOutputChannels, 0);
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: (suggestion) grr, I think these could fit on one line if you used `params` instead of `parameters`

File: server/scsynth/SC_PortAudio.cpp (hunk 23 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: For this one I'd like to leave `suggestedLatency` in - we'll use it once this function is used in the refactor in #4477

File: server/scsynth/SC_PortAudio.cpp (hunk 22 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: This makes sense. As you observed, I was trying to follow existing paradigms, but this looks nicer for sure.

File: server/scsynth/SC_PortAudio.cpp (hunk 28 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: unfortunately `out_params` still doesn't fit in one line, so I'm gonna leave as is.

File: server/scsynth/SC_PortAudio.cpp (hunk 23 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: I changed the name though

**Comment by dyfer** [comment]
Thanks Brian!

> * add documentation for functions (e.g., CheckPaDevices) in the header, not the cpp file.

Is [this](https://github.com/supercollider/supercollider/pull/4475/files#diff-98d9dae5034e95458cdf63989e5ea177R94) the right place? There's no separate header file
> * I don't know if you need "Pa" in the name of every function since it's already obvious these functions operate on PortAudio streams and objects. 

I renamed most functions.

Also, should I remove more inline comments or is this good now?

File: SCClassLibrary/Common/Control/Server.sc [hunk 29]
```diff
@@ -175,7 +175,7 @@ ServerOptions {
 		if (outputStreamsEnabled.notNil, {
 			o = o ++ " -O " ++ outputStreamsEnabled ;
 		});
-		if ((thisProcess.platform.name!=\osx) or: {inDevice == outDevice})
+		if (inDevice == outDevice)
```
Comment (jamshark70) [inline SCClassLibrary/Common/Control/Server.sc]: Perhaps `if((thisProcess.platform.name == \linux) or: { inDevice == outDevice })` ? Because separate IO devices won't behave the same in Linux.

File: server/scsynth/SC_PortAudio.cpp [hunk 30]
```diff
@@ -262,39 +273,168 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+    return name;
+}
+
+PaDeviceIndex SC_PortAudioDriver::GetPaDeviceFromName(const char* device, IOType ioType) const {
+    if (device == nullptr || device[0] == '\0')
+        return paNoDevice;
 
-    // This tries to find one or two devices that match the given name (substring)
-    // might cause problems for some names...
+    PaDeviceIndex numDevices = Pa_GetDeviceCount();
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: (suggestion) minor nitpick -- `numDevices` is of type `PaDeviceIndex` but `i` in the loop below is of type `numDevices`. I realize they are probably the same thing or nearly the same thing, but it still looks sloppy (I know you didn't write this part)

**Comment by brianlheim** [comment]
> Is this the right place? There's no separate header file

Yes, sorry, there is a gap between the class definition and function definitions so I mistakenly thought they were in different files.

> I renamed most functions.
> Also, should I remove more inline comments or is this good now?

Both look good! Thanks!

File: server/scsynth/SC_PortAudio.cpp (hunk 28 above)
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: ok, thanks for checking, i tried it in my shell and thought that would have put it under 120 chars but I guess not

File: server/scsynth/SC_PortAudio.cpp [hunk 31]
```diff
@@ -88,7 +89,17 @@ class SC_PortAudioDriver : public SC_AudioDriver {
...
+    std::string GetDeviceName(int index) const;
+    // this function will select default PA devices if they are not defined
+    // it will also try to check for some configuration problems
+    // numIns, numOuts and sampleRate are only the requested values, can change later
+    PaError TryGetDefaultDevices(int* inDevice, int* outDevice, int numIns, int numOuts, double sampleRate) const;
+    template <typename SupportCheck> // expected signature: PaError (*)(PaStreamParameters&, double)
+    PaError CheckSinglePaDevice(int* device, double sampleRate, int maxChannels, int defaultDevice,
+                                const char* deviceType, SupportCheck isSupportedFunc) const;
+    void TryMatchDeviceSameAPI(int* matchingDevice, const int* knownDevice, IOType matchingDeviceType) const;
+    PaStreamParameters MakePaStreamParameters(int device, int channelCount, double suggestedLatency) const;
```
Comment (jrsurge) [inline server/scsynth/SC_PortAudio.cpp]: These private member functions can all be declared `static` - as far as I can see they only operate on their arguments and don't access any instance member variables?

**Comment by jrsurge** [comment]
Server crash with ASIO:

If the user only specifies _one_ device, using `s.outDevice = ""`, and it is _not_ the default ASIO device, the server will choose to boot with two separate ASIO devices (in this case, the default inDevice, and the user specified outDevice) - which causes the server to crash.

If the user specifies a correct ASIO device, the server has to choose that device for both in and out, regardless of the default.

File: server/scsynth/SC_PortAudio.cpp [hunk 32]
```diff
@@ -262,39 +273,168 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+                                "Please set matching sample rates "
+                                "in the Windows Sound Control Panel and try again.\n",
+                                GetDeviceName(*inDevice).c_str(), GetDeviceName(*outDevice).c_str());
+                        return err;
+                    }
+                }
+            }
+        }
+
+        // in case we still don't have a proper device, use the default device
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: > Server crash with ASIO:

Thanks for spotting this!

> If the user specifies a correct ASIO device, the server has to choose that device for both in and out, regardless of the default.

I tried correcting it. If only one device is specified, and it's a full duplex ASIO device, it will be used for both input and output. Could you test on your setup if the fix works correctly?

**Comment by dyfer** [comment]
> Server crash with ASIO:
 
Thanks for spotting this!

> If the user specifies a correct ASIO device, the server has to choose that device for both in and out, regardless of the default.

I tried correcting it. If only one device is specified, and it's a full duplex ASIO device, it will be used for both input and output. Could you test on your setup if the fix works correctly?

File: SCClassLibrary/Common/Control/Server.sc (hunk 29 above)
Comment (dyfer) [reply SCClassLibrary/Common/Control/Server.sc]: Wouldn't that depend on which backend is used? While we officially support JACK only, it seems possible to build with PortAudio, in which case we might want to have different I/O devices.

It seems that conceptually the switch here should depend on the _backend_, not the platform, but we have no way of checking that so I'd not put it in. Anyway, if the user specifies a single device (`s.options.device`), which is the intended use on linux (JACK) AFAIU, this should behave the same.

**Comment by jrsurge** [comment]
> > Server crash with ASIO:
> 
> Thanks for spotting this!
> 
> > If the user specifies a correct ASIO device, the server has to choose that device for both in and out, regardless of the default.
> 
> I tried correcting it. If only one device is specified, and it's a full duplex ASIO device, it will be used for both input and output. Could you test on your setup if the fix works correctly?

Thanks for the fix! This now works as expected

File: server/scsynth/SC_PortAudio.cpp (hunk 32 above)
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: or "use default devices" ?

[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: either works

**Comment by dyfer** [comment]
> I found many minor grammar/style changes for the new Audio Device Selection helpfile. It was easier for me to change them myself, rather than adding dozens of review comments.

Hi James, you replaced "macOS" with "MacOS" in your patches. Are you sure this is best? It seems that Apple stylizes it "macOS" everywhere, including beginning of the sentence, and I was trying to follow that. Example:

Screen Shot 2019-08-04 at 12 20 51 PM

I don't have a very strong opinion, but I wanted to clarify my conscious choice here.

File: server/scsynth/SC_PortAudio.cpp [hunk 33]
```diff
@@ -383,6 +539,14 @@ bool SC_PortAudioDriver::DriverSetup(int* outNumSamples, double* outSampleRate)
             outStreamParams_p = NULL;
         }
 
+        // check if format is supported, this sometimes gives a more accurate error information than Pa_OpenStream's
+        // error
+        paerror = Pa_IsFormatSupported(inStreamParams_p, outStreamParams_p, *outSampleRate);
+        if (paerror != paNoError) {
+            PRINT_PORTAUDIO_ERROR(Pa_OpenStream, paerror);
+            return paerror == paNoError;
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: It doesn't modify the error. Should I `return false;` then? I was using the same approach as it was already used elsewhere in the file: [1](https://github.com/dyfer/supercollider/blob/topic/scsynth-portaudio-input-output-devices/server/scsynth/SC_PortAudio.cpp#L574), [2](https://github.com/dyfer/supercollider/blob/topic/scsynth-portaudio-input-output-devices/server/scsynth/SC_PortAudio.cpp#L604), [3](https://github.com/dyfer/supercollider/blob/topic/scsynth-portaudio-input-output-devices/server/scsynth/SC_PortAudio.cpp#L615)

**Comment by geoffroymontel** [comment]
I've just tried the build with both my Steinberg MR816 ASIO card and Reaper's ReaRoute ASIO and both work well, no regression ! thanks !

File: server/scsynth/SC_PortAudio.cpp [hunk 34]
```diff
@@ -262,39 +273,168 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+                    return err;
+                }
+            } else {
+                // if we don't request SR, check if devices have maching SR
+                uint32 inSR = uint32(Pa_GetDeviceInfo(*inDevice)->defaultSampleRate);
+                uint32 outSR = uint32(Pa_GetDeviceInfo(*outDevice)->defaultSampleRate);
+                if (inSR != outSR) {
+                    // if defaults are different, check if both devices can be opened using the OUTPUT's SR
+                    PaError err = Pa_IsFormatSupported(&in_parameters, &out_parameters,
+                                                       Pa_GetDeviceInfo(*outDevice)->defaultSampleRate);
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: The reason here is that sample rate should be a `double`, but for comparison I'm casting them to `uint32`. I've moved cast into the `if` statement, is that OK?

File: server/scsynth/SC_PortAudio.cpp [hunk 35]
```diff
@@ -262,39 +273,168 @@ int SC_PortAudioDriver::PortAudioCallback(const void* input, void* output, unsig
...
+
+    if (*matchingDevice != paNoDevice)
+        fprintf(stdout, "Selecting default %s %s device\n", apiInfo->name, (isInput ? "input" : "output"));
 }
 
+PaError SC_PortAudioDriver::TryGetDefaultDevices(int* inDevice, int* outDevice, int numIns, int numOuts,
+                                                 double sampleRate) const {
+    if (numIns && !numOuts) {
+        *outDevice = paNoDevice;
+        // check for requested sample rate or select the default device
```
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: I've changed to `CheckDeviceSampleRateOrGetDefault` and removed the comment. Can this name be improved or is it OK?

File: server/scsynth/SC_PortAudio.cpp (hunk 30 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: You mean `i` is of type `int`, right? This iteration was there before so I've just used that, but now I changed the type of `i` to `PaDeviceIndex` and it works.

File: server/scsynth/SC_PortAudio.cpp (hunk 31 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: These functions were `const` I've changed them to `static`. 

I have only a very rudimentary practical understanding when a function should be either `static` or `const` (I know these are two separate things, but AFAIU somewhat related). I just would like your confirmation this is the right choice, as I don't fully understand the difference.

**Comment by dyfer** [comment]
Thanks for testing @geoffroymontel 
If I could ask you to test one more thing - what happens if you don't specify sample rate in server options and boot to ASIO? The server should boot to the device's SR, is that the case? Is it different from the previous behavior?

**Comment by jamshark70** [comment]
> Question: you replaced "macOS" with "MacOS" in your patches. Are you sure this is best? It seems that Apple stylizes it "macOS" everywhere, including beginning of the sentence, and I was trying to follow that.

No objection to changing it back to Apple/apple(?) style.

**Comment by geoffroymontel** [comment]
> If I could ask you to test one more thing - what happens if you don't specify sample rate in server options and boot to ASIO? The server should boot to the device's SR, is that the case? Is it different from the previous behavior?

I've tried the following
- setting the MR816 to 96 khz
- starting SC with `s.options.device = "ASIO : Yamaha Steinberg FW ASIO";`
- SC would change the MR816 back to 44khz

```
Booting with:
  In: ASIO : Yamaha Steinberg FW ASIO
  Out: ASIO : Yamaha Steinberg FW ASIO
SCDoc: Indexed 1991 documents in 1.33 seconds
  Sample rate: 44100.000
  Latency (in/out): 0.004 / 0.012 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
```

The behaviour is the same on 3.10.2 on my Windows box

**Comment by dyfer** [comment]
@geoffroymontel thanks for testing. I'll check if there's a reason. Otherwise at least it's not a regression.

**Comment by dyfer** [comment]
update on ASIO default sample rate:

It seems this is a PortAudio bug. PortAudio obtains `defaultSampleRate` by [checking whether the device supports a given SR agains a list of known SRs and takes the first match](https://github.com/supercollider/portaudio/blob/a906f6aaddb6c7b9601e38116ee80fc778c9e9c9/src/hostapi/asio/pa_asio.cpp#L1053). I have tried to replace that line with 

```c++
ASIOError asioError = ASIOGetSampleRate(&deviceInfo->defaultSampleRate);
```

and that seemed to work, but I don't know enough to propose a full fix in PA for that. I have posted to their list so maybe it will be fixed upstream at some point.

File: server/scsynth/SC_PortAudio.cpp (hunk 31 above)
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: > I know these are two separate things, but AFAIU somewhat related

`static` member function - cannot access object state, basically an ordinary function, with access to private members of instances of the class of which they are declared a member
`const` member function - cannot mutate members (except for members declared `mutable`)

> I have only a very rudimentary practical understanding when a function should be either static or const

IMO, either is fine. `static` is nice because it lets you visually confirm that the function uses no object state. But in this case, if I were writing it, I wouldn't mind leaving them as const members. On the off chance that in the future these functions do need access to class state (and I judge that as fairly likely), it's kind of annoying to have to rework the interface by changing `static` back to `const`. In addition, these functions seem conceptually not `static` to me since they do indirectly access or modify class state.

File: server/scsynth/SC_PortAudio.cpp (hunk 30 above)
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: > You mean i is of type int, right?

yes, sorry, thanks for that

File: server/scsynth/SC_PortAudio.cpp (hunk 34 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: yeah, looks good! thanks

File: server/scsynth/SC_PortAudio.cpp (hunk 33 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: yes, return false is way clearer

File: server/scsynth/SC_PortAudio.cpp [hunk 36]
```diff
@@ -345,9 +345,16 @@ void SC_PortAudioDriver::TryMatchDeviceSameAPI(int* matchingDevice, const int* k
...
+        && (isInput ? Pa_GetDeviceInfo(*knownDevice)->maxInputChannels
+                    : Pa_GetDeviceInfo(*knownDevice)->maxOutputChannels)
+            > 0;
+    if (isAsioFullDuplex)
+        *matchingDevice = *knownDevice;
+    else
+        *matchingDevice = isInput ? apiInfo->defaultInputDevice : apiInfo->defaultOutputDevice;
 
-    if (*matchingDevice != paNoDevice)
+    if (*matchingDevice != paNoDevice && !isAsioFullDuplex)
```
Comment (brianlheim) [inline server/scsynth/SC_PortAudio.cpp]: here's a simplified version:

```cpp
const auto* devInfo = Pa_GetDeviceInfo(*knownDevice);
const auto* apiInfo = Pa_GetHostApiInfo(devInfo->hostApi);
const bool isInput = matchingDeviceType == IOType::Input;
const auto maxChannels = isInput ? devInfo->maxInputChannels : devInfo->maxOutputChannels;
const bool isAsioFullDuplex = apiInfo->type == paASIO && maxChannels > 0;
if (isAsioFullDuplex) {
    *matchingDevice = *knownDevice;
} else {
    *matchingDevice = isInput ? apiInfo->defaultInputDevice : apiInfo->defaultOutputDevice;
    if (*matchingDevice != paNoDevice)
        fprintf(stdout, "Selecting default %s %s device\n", apiInfo->name, isInput ? "input" : "output");
}
```

File: server/scsynth/SC_PortAudio.cpp (hunk 35 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: works for me!

File: server/scsynth/SC_PortAudio.cpp (hunk 33 above)
[the remark this answers is not in the document]
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: All right.  I assume I should leave other instances where this is used? Or change them as well?

File: server/scsynth/SC_PortAudio.cpp (hunk 31 above)
Comment (dyfer) [reply server/scsynth/SC_PortAudio.cpp]: Thank you for the explanation. I reverted that commit so it's back to `const`.

File: server/scsynth/SC_PortAudio.cpp (hunk 33 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: leave the other spots alone -- this PR doesn't need to clean up anything else, just set good standards :)

File: server/scsynth/SC_PortAudio.cpp (hunk 31 above)
Comment (jrsurge) [reply server/scsynth/SC_PortAudio.cpp]: I don't want to argue with Brain or make you change this again, but just to clarify why I suggested it in the first place. The use of static here would convey that they are utility functions with a strong association to the class, that don't have direct access to members - which is the case. If the nature of the function(s) change later, then it would need re-writing, but given that they are just utility functions that query portaudio it seemed appropriate. It's fine either way really, so stick with Brian on this one :)

**Comment by dyfer** [comment]
@brianlheim please let me know when you think this is ready for me be rebase.

File: server/scsynth/SC_PortAudio.cpp (hunk 31 above)
Comment (brianlheim) [reply server/scsynth/SC_PortAudio.cpp]: to be clear, i am fine with either, i just personally would have written them const.

**Comment by dyfer** [comment]
This PR is now rebased with clean commit history.

Pending @jamshark70 's approval w/r/t https://github.com/supercollider/supercollider/pull/4475#discussion_r310335227 it is ready to merge.

**Comment by brianlheim** [comment]
@jamshark70 no pressure but FYI this PR (and your approval of it) is what's currently blocking the 3.10.3 release.

File: SCClassLibrary/Common/Control/Server.sc (hunk 29 above)
Comment (jamshark70) [reply SCClassLibrary/Common/Control/Server.sc]: OK, I can accept this as "user's responsibility."

**Comment by jamshark70** [comment]
Sorry for the delay -- I hadn't realized that I was holding up a release.

I took the liberty of merging -- I hope that wasn't out of turn, but I recall this PR has already been extensively, exhaustively reviewed and if my approval was the last thing needed, seemed appropriate.

Much-needed feature!

**Comment by snappizz** [comment]
thanks @jamshark70 !!!

**Comment by sonoro1234** [comment]
@dyfer Congratulations for such a long work!!
supernova version should be done to have compatible command line and behaviour!!!
