### PR TITLE
sclang: fix unique method regression and rename variables to something useful

### LINKED ISSUE #6745: addUniqueMethod broken on 3.14 dev
## Environment
macOS 13.7.5

## Steps to reproduce
run example from Object help file:
```supercollider
a = 5;
a.addUniqueMethod(\sayHello, { |to| "hello " ++ to ++ ", I am 5" });
a.sayHello;
```

## Expected vs. actual behavior
on 3.13 this still works and answers
-> hello 5, I am 5

on 3.14 current dev, this fails with:
```
ERROR: Message 'sayHello' not understood.
RECEIVER:
   Integer 5
ARGS:
KEYWORD ARGUMENTS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = 5
		arg selector = 'sayHello'
		arg args = [*0]
		arg kwargs = [*0]	
... 
```

### PR DESCRIPTION
**Pull request by JordanHendersonMusic**
## Purpose and Motivation

Closes #6745 — a regression in unique methods.

Also adds tests to ensure this feature is not broken again.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

File: lang/LangSource/PyrMessage.cpp [hunk 1]
```diff
@@ -291,36 +291,36 @@ bool tryUniqueMethod(VMGlobals* g, PyrMethod* meth, PyrSlot* receiverSlot, PyrSl
...
-    if (array2->classptr != class_array)
+    auto receiverUniqueMethodsArray = slotRawObject(receiverUniqueMethodsArraySlot);
+    if (receiverUniqueMethodsArray->classptr != class_array)
         return false;
-    auto i2 = arrayAtIdentityHashInPairs(array2, selectorSlot);
-    if (i2 < 0)
+    auto selectorIndex = arrayAtIdentityHashInPairs(receiverUniqueMethodsArray, selectorSlot);
+    if (selectorIndex < 0)
         return false;
-    auto slot2 = array2->slots + i;
```
Comment (JordanHendersonMusic) [inline lang/LangSource/PyrMessage.cpp:318]: This should have been i2, that was the bug.

**Comment by JordanHendersonMusic** [comment]
The failing unit tests appear to be unrelated.

**Comment by adcxyz** [comment]
Wow that was really quick! 
Looks great, would like to verify it, but my build currently fails 
(with -- Could NOT find Qt6WebEngineCore (missing: Qt6WebEngineCore_DIR))

@JordanHendersonMusic, 
Do you know where I can download the CI build for that PR, 
so I can check there? 
TIA adc

**Comment by dyfer** [comment]
> Looks great, would like to verify it, but my build currently fails (with -- Could NOT find Qt6WebEngineCore (missing: Qt6WebEngineCore_DIR)

What platform are you on? Homebrew stopped shipping webengine core on older macOS systems recently... See [here](https://github.com/supercollider/supercollider/pull/6660#issuecomment-2798509531).

> 
> Do you know where I can download the CI build for that PR, so I can check there?

Go to "Checks" tab, the links to artifacts are added there:
Screenshot 2025-04-19 at 11 50 36 AM

They can also be seen at the bottom when you're in the top level of the given job (**scroll way down**)

Screenshot 2025-04-19 at 11 51 53 AM

**Comment by adcxyz** [comment]
@dyfer - on macOS, and thanks, got it!

**Review by adcxyz — APPROVED** [review]
works perfectly, and is much more readable. thanks!

**Comment by capital-G** [comment]
Hey @JordanHendersonMusic - is it possible that this PR broke 1 (on linux)/2 (on windows) tests?

At least this is the first PR which introduces constant failures of the same tests - it could be the GHA infrastructure as well though...

See <https://github.com/supercollider/supercollider/actions/runs/14559556424/job/40841234940#step:8:7988>
```
 Failed tests:

	[0/1]	TestServer_boot:test_notifyAndServerBootActions (2.34s)
		 ! Toggling Server.notify should not cause ServerBoot actions to run.
	[0/1]	TestServer_boot:test_notifyAndServerTreeActions (2.97s)
		 ! Toggling Server.notify should not cause ServerTree actions to run.
```

and <https://github.com/supercollider/supercollider/actions/runs/14559556424/job/40841234940#step:7:2891>

```
Test: test_notifyAndServerBootActions
TestServer_boot : setting clientID to 0.
Server 'TestServer_boot' exited with exit code 0.
Booting server 'TestServer_boot' on address 127.0.0.1:57110.
Number of Devices: 3
   0 : "Apple Virtual Sound Device"
   1 : "Apple Virtual Sound Device"
   2 : "Null Audio"

"Apple Virtual Sound Device" Input Device
   Streams: 1
      0  channels 2

"Apple Virtual Sound Device" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 48000.000000, driver's block size = 512
SuperCollider 3 server ready.
Requested notification messages from server 'TestServer_boot'
Requested notification messages from server 'TestServer_boot'
/notify : already registered
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
Switched off notification messages from server 'TestServer_boot'
Switched off notification messages from server 'TestServer_boot'
not registered
Requested notification messages from server 'TestServer_boot'
Requested notification messages from server 'TestServer_boot'
/notify : already registered
Requested notification messages from server 'TestServer_boot'
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
/notify : already registered
Requested notification messages from server 'TestServer_boot'
/notify : already registered
TestServer_boot - already registered with clientID 0.
TestServer_boot - handling login request though already registered - 
This seems to be a login after a loss of network contact - 
- reconnected with the same clientID as before, so probably all is well.


FAIL: a TestServer_boot: test_notifyAndServerBootActions - Toggling Server.notify should not cause ServerBoot actions to run.
Is:
	 3 
Should be:
	 1

server 'TestServer_boot' disconnected shared memory interface
'/quit' message sent to server 'TestServer_boot'.

UNIT TESTS FOR 'TestServer_boot' COMPLETED
There were failures:
a TestServer_boot: test_notifyAndServerBootActions - Toggling Server.notify should not cause ServerBoot actions to run.

	Test: test_notifyAndServerTreeActions
TestServer_boot : setting clientID to 0.
Server 'TestServer_boot' exited with exit code 0.
Booting server 'TestServer_boot' on address 127.0.0.1:57110.
Number of Devices: 3
   0 : "Apple Virtual Sound Device"
   1 : "Apple Virtual Sound Device"
   2 : "Null Audio"

"Apple Virtual Sound Device" Input Device
   Streams: 1
      0  channels 2

"Apple Virtual Sound Device" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 48000.000000, driver's block size = 512
SuperCollider 3 server ready.
Requested notification messages from server 'TestServer_boot'
Requested notification messages from server 'TestServer_boot'
Requested notification messages from server 'TestServer_boot'
/notify : already registered
/notify : already registered
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
Switched off notification messages from server 'TestServer_boot'
Switched off notification messages from server 'TestServer_boot'
not registered
Requested notification messages from server 'TestServer_boot'
Requested notification messages from server 'TestServer_boot'
/notify : already registered
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.

FAIL: a TestServer_boot: test_notifyAndServerTreeActions - Toggling Server.notify should not cause ServerTree actions to run.
Is:
	 3 
Should be:
	 1

server 'TestServer_boot' disconnected shared memory interface
'/quit' message sent to server 'TestServer_boot'.

UNIT TESTS FOR 'TestServer_boot' COMPLETED
There were failures:
a TestServer_boot: test_notifyAndServerBootActions - Toggling Server.notify should not cause ServerBoot actions to run.
a TestServer_boot: test_notifyAndServerTreeActions - Toggling Server.notify should not cause ServerTree actions to run.
```

The test code is

https://github.com/supercollider/supercollider/blob/4bb689d1f275399b771cd05f1f14ab74c430fcbf/testsuite/classlibrary/TestServer_boot.sc#L100-L116

and

https://github.com/supercollider/supercollider/blob/4bb689d1f275399b771cd05f1f14ab74c430fcbf/testsuite/classlibrary/TestServer_boot.sc#L13-L26

I can't figure out why this PR would make those tests fail, but I am also not really familiar w/ the content of the PR.

**Comment by JordanHendersonMusic** [comment]
So when doesnotunderstand is invoked, first the interpreter checks for unique methods, that's what this functions does. The only way I can think that this pr could have any affect was if the instance has unique methods, or at the very least, if it invokes doesnotunderstand.

**Comment by capital-G** [comment]
Yes, but currently these 2 tests always fail.

I looked at runs before this PR and this is very interesting, see <https://github.com/supercollider/supercollider/actions/runs/14553417411/job/40827471542#step:7:14369>

```
Test: test_notifyAndServerBootActions
TestServer_boot : setting clientID to 0.
Cannot connect to shared memory: No such file or directory
ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER:
Instance of ServerShmInterface {    (0x13327c528, gc=C8, fmt=00, flg=00, set=02)
  instance variables [2]
    ptr : nil
    finalizer : nil
}
PATH: /Users/runner/work/supercollider/supercollider/testsuite/scripts/sclang_test_runner.scd

PROTECTED CALL STACK:
	Meta_MethodError:new	0x1086fdd00
		arg this = PrimitiveFailedError
		arg what = Failed.
		arg receiver = a ServerShmInterface
	Meta_PrimitiveFailedError:new	0x108706780
		arg this = PrimitiveFailedError
		arg receiver = a ServerShmInterface
	Object:primitiveFailed	0x10827d3c0
		arg this = a ServerShmInterface
	Server:connectSharedMemory	0x10902a440
		arg this = TestServer_boot
		var id = 57110
	Server:bootInit	0x10902d500
		arg this = TestServer_boot
		arg recover = false
	a FunctionDef	0x110265200
		sourceCode = "<an open Function>"
	Routine:prStart	0x1089eca00
		arg this = a Routine
		arg inval = 592.73240575

CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	< closed FunctionDef >
		arg error = <instance of PrimitiveFailedError>
	Function:try
		arg this = <instance of Function>
		arg handler = <instance of Function>
		var result = <instance of PrimitiveFailedError>
	< FunctionDef in Method Scheduler:seconds_ >
		arg time = 594.816465542
		arg item = <instance of Routine>
	< FunctionDef in Method SequenceableCollection:pairsDo >
		arg i = 2
	Integer:forBy
		arg this = 0
		arg endval = 2
		arg stepval = 2
		arg function = <instance of Function>
		var i = 2
		var j = 1
	SequenceableCollection:pairsDo
		arg this = [*4]
		arg function = <instance of Function>
	Scheduler:seconds_
		arg this = <instance of Scheduler>
		arg newSeconds = 594.81651975
	Meta_AppClock:tick
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER: a ServerShmInterface


Server 'TestServer_boot' exited with exit code 0.
Booting server 'TestServer_boot' on address 127.0.0.1:57110.
Number of Devices: 3
   0 : "Apple Virtual Sound Device"
   1 : "Apple Virtual Sound Device"
   2 : "Null Audio"

"Apple Virtual Sound Device" Input Device
   Streams: 1
      0  channels 2

"Apple Virtual Sound Device" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 48000.000000, driver's block size = 512
SuperCollider 3 server ready.
Requested notification messages from server 'TestServer_boot'
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
Switched off notification messages from server 'TestServer_boot'
Switched off notification messages from server 'TestServer_boot'
not registered
Requested notification messages from server 'TestServer_boot'
Requested notification messages from server 'TestServer_boot'
/notify : already registered
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
TestServer_boot: server process's maxLogins (1) matches with my options.
TestServer_boot: keeping clientID (0) as confirmed by server process.
PASS: a TestServer_boot: test_notifyAndServerBootActions - Toggling Server.notify should not cause ServerBoot actions to run.
server 'TestServer_boot' disconnected shared memory interface
'/quit' message sent to server 'TestServer_boot'.

UNIT TESTS FOR 'TestServer_boot' COMPLETED
There were no failures
```

It seems to me the test was broken before, now it got somehow fixed (why? is this a timing thing only - I didn't had time to inspect whats actually happening here) and the test fails.

**Comment by dyfer** [comment]
> It seems to me the test was broken before, now it got somehow fixed (why? is this a timing thing only - I didn't had time to inspect whats actually happening here) and the test fails.

I haven't looked closely, but I'm guessing that this may happen when we start a new instance of the server when the old one did finished exiting (we don't wait for exit). I tried rebasing https://github.com/supercollider/supercollider/pull/6738 to see if that's the issue with this test, but I still got this failure, so idk.

**Comment by capital-G** [comment]
Just had a CI run where the linux tests passed => https://github.com/supercollider/supercollider/actions/runs/14943605999/job/41984200455?pr=6835#step:6:2647 - and this is w/o SHM crashing.

**Comment by dyfer** [comment]
I also see tests in https://github.com/supercollider/supercollider/pull/6738 passing now (rebased on recent develop).
