### PR TITLE
SC_JACK repair

### LINKED ISSUE #4596: SC_Jack server clock fails
(See below james added explanation)

From the issue #4580 I was most interested in server clock errors.
I did a measuring in Lua2SC similar to #4580 on linux and win32 for scsynth and supernova:

In win32 portaudio both scsynth and supernova have a very little variation from the intended sample interval between onsets, intended sample interval was 441 and I got minimum: 440 and maximum 442

-- minimum, maximum, mean, standard deviation

In win32 jack scsynth: 362	495	441.02252252252	13.226655278567

In linux supernova behaves as in win32 but scsynth gives wild variations from 408 to 455
mean 440.97895791583	standard deviation 10.14817789853

supernova systemclock numbers 440	442	441.04809619238	0.3493673645775	
supernova sampleclock numbers: 441	441	441	0

The conclusion would be that SC_Jack has some fails leading to big standard deviation in win32 and linux

code used:
```lua
local s = require"sclua.Server".Server()
local dur = 60*6
local buf = s.Buffer():alloc(s.options.SC_SAMPLERATE* dur, 1)
s:sync()
SynthDef("imp", {},function()
		Line.ar{dur=10/SampleRate.ir(), doneAction= 2};
		OffsetOut.ar(0, Impulse.ar(0));
end):store();

SynthDef("rec", {}, function()
	RecordBuf.ar(In.ar(0, 1),buf.bufnum,nil,nil,nil,nil,0,nil,2)
end):store()

s:sync()



local now = lanes.now_secs()
local inc = 0.3
local rec
s:makeBundle(now,function() rec = s.Synth("rec") end)

local pos = 0
local i = 0
while dur > pos do
	i = i + 1
	pos = pos + inc
	s:sendBundle(pos+now,{"/s_new",{"imp",-1,2,rec.nodeID}})
end
print(i,"impulses sent")

local leng = inc*s.options.SC_SAMPLERATE
window = addWindow{}
grafics = addControl{window=window,panel=panelNO, typex="funcgraph",width=600,height=300,miny=leng*0.99,maxy=leng*1.01,expand=true}

QueueAction(dur+1,{function() 
	print"QueueAction"
	buf:loadToFloatArray(0,-1,function(arr)
		print"array arrived"
		print(arr)
		
		local onsets = {}
		for i=1,#arr do
			if arr[i] > 0.5 then onsets[#onsets+1] = i end
		end
		local diff = TA(onsets):differentiate()
		local gdiff = {}
		for i=1,#diff do gdiff[i] = {i,diff[i]} end
		grafics:val(diff)
		print(#diff,diff)
		print(diff:min(),diff:max(),diff:mean(),diff:stddev())
	end)
end})

theMetro:start()
```
For sending maximum of 1000 events at a time, this code was used

```lua
local s = require"sclua.Server".Server()
local dur = 60*6
local inc = 0.01
local clust = 1000
local buf = s.Buffer():alloc(s.options.SC_SAMPLERATE* dur, 1)
s:sync()
SynthDef("imp", {},function()
		Line.ar{dur=10/SampleRate.ir(), doneAction= 2};
		OffsetOut.ar(0, Impulse.ar(0));
end):store();

SynthDef("rec", {}, function()
	RecordBuf.ar(In.ar(0, 1),buf.bufnum,nil,nil,nil,nil,0,nil,2)
end):store()

s:sync()

Routine(function()

	local now = lanes.now_secs()
	
	local rec
	s:makeBundle(now,function() rec = s.Synth("rec") end)
	
	local pos = 0
	local i = 0
	while dur > pos do
		local ci = 0
		while ci < clust do
			i = i + 1; ci = ci + 1
			pos = pos + inc
			s:sendBundle(pos+now,{"/s_new",{"imp",-1,2,rec.nodeID}})
		end
		coroutine.yield(clust*inc)
	end
	print(i,"impulses sent")
	
	local leng = inc*s.options.SC_SAMPLERATE
	window = addWindow{}
	grafics = addControl{window=window,panel=panelNO, typex="funcgraph", width=600, height=300, miny=leng*0.99, maxy=leng*1.01, expand=true}
	
	QueueAction(clust*inc+1,{function() 
		print"QueueAction"
		buf:loadToFloatArray(0,-1,function(arr)
			print"array arrived"
			print(arr)
			
			local onsets = {}
			for i=1,#arr do
				if arr[i] > 0.5 then onsets[#onsets+1] = i end
			end
			local diff = TA(onsets):differentiate()
			local gdiff = {}
			for i=1,#diff do gdiff[i] = {i,diff[i]} end
			grafics:val(diff)
			print(#diff,diff)
			print(diff:min(),diff:max(),diff:mean(),diff:stddev())
		end)
	end})

end) --Routine
theMetro:tempo(60)
theMetro:start()
```

### PR DESCRIPTION
**Pull request by sonoro1234**
## Purpose and Motivation

Fixes #4596

Which basically consist on a lot of jitter in scsynth clock when uses Jack on windows or linux
Causes are:
TimeDLL was not used because SC_JACK_USE_DLL was not defined
TimeDLL.Reset was not called on DriverStart
time provided by secondsSinceEpoch(getTime()) was not correct

## Types of changes

- Bug fix
Let JACK use TimeDLLby defining SC_JACK_USE_DLL
sc_JACKOSCTimeSeconds (mimics portaudio for scsynth) instead of secondsSinceEpoch(getTime()) 
calling mDLL.Reset on DriverStart
cast with uint64 (as done in portaudio) instead of int64

## To-do list

- [X] Code is tested
- [X] All tests are passing
- [x] This PR is ready for review

### CODE REVIEW

**Comment by jamshark70** [comment]
Confirmed that my test case from #4596 passes with this change.

I would like to run it later today for a half-hour to an hour-long improv session and be sure that it holds up for longer than 10 seconds. I don't expect any problems with it, but it's useful to be sure it survives a long session.

I'm not competent to review the C++, though I wonder -- if we compile SC_Jack.cpp only when building for the JACK backend, and if we forcibly define `#define SC_JACK_USE_DLL` in all cases (i.e. this isn't configurable in cmake), then what is the point of the `#ifdef`s? E.g.

```
#ifdef SC_JACK_USE_DLL
    mDLL.Reset(mSampleRate, mNumSamplesPerCallback, SC_TIME_DLL_BW, sc_JACKOSCTimeSeconds());
#endif
```

... but SC_JACK_USE_DLL is always set, as far as I can see, so I guess it might be cleaner just to drop the conditional.

"SC_JACK dont multiply by 0" is not a very informative commit message. I'd suggest instead "scsynth: SC_Jack: Use JACK to resolve OSC timestamps instead of std::chrono"

Excellent catch! A quick test seems to be working

**Comment by jamshark70** [comment]
Hm... even without playing a longer set, I'm getting some bad results.

When I tried it briefly this morning, I tested 100 pulses per second for 60 seconds. Seemed OK.

I've run a couple of tests with 10 pulses per second for 600 seconds (same number of pulses, but spread out over 10x longer duration), and I'm finding, somewhere in the middle of that time span, the timing becomes unstable and then gradually slides back to where it should be.

During this time, JACK does not report xruns or timing abnormalities.

One test (left) seemed to be fine at first, but then there was one delta much smaller than expected, and after that, the timing corrected slowly. On a second run, midway through, I saw a lot of "late" messages with gradually decreasing numbers, until the late messages stopped and it returned to normal functioning.

Test 1 (no late messages, but not a flat line either)
19-0928-600-sec-test1

Test 2 (with the "late" messages)
19-0928-600-sec-test2

I can't guess what the problem is, but right now it looks like: before the change, it's uniformly bad; after the change, it's very good most of the time but at some unpredictable times, it becomes much much worse.

Then I ran the test for 10 minutes again, against supernova, and it died with an error at the end because `Buffer:write` doesn't follow the protocol. So, run it one more time (waiting for ten minute tests is a lot of fun...)... and... it seems somewhat better than the scsynth results, though there are occasional outliers (severe outliers, like 50% above or below) and gradual corrections.

19-0928-600-sec-test3-supernova

(No, I haven't run the test for 10 minutes on supernova with useSystemClock = false -- because I've already spent about 45 minutes running the test multiple times and writing this up, and I need to move on to other things. Also, based on past experience, I can predict the result: either sclang runs faster than the sample clock, and the latency between sclang messaging and sounding result gets larger, or sclang runs slower than the sample clock, and eventually all messages are late. Neither of those outcomes is particularly relevant to the present case.)

I don't think anyone ever ran the test for 10 minutes on Mac or Windows/portaudio, so we don't know if this is just the best that any audio engine can do or if this approach doesn't quite get there.

I am running the test from https://github.com/supercollider/supercollider/issues/4596#issuecomment-535864440 with `~clockTest.(\routine, 10, 600);` if anyone else wants to try.

**Comment by sonoro1234** [comment]
> On a second run, midway through, I saw a lot of "late" messages with gradually decreasing numbers, until the late messages stopped and it returned to normal functioning.

That is related to discrepancies between sclang clock and server clock. Ideally the test should be independant from sclang clock: instead of using wait, all the messages should be sent in the same cluster for that.

**Comment by jamshark70** [comment]
> That is related to discrepancies between sclang clock and server clock.

But it ran for 3 minutes very smoothly, and then there was a huge jump. I'd expect slight discrepancies to be distributed over time, so that each individual delta might be subject to a small adjustment but no single adjustment is very large.

If we have 100 ms between pulses, and then suddenly one delta is about 50 ms, that doesn't fit the profile I'd expect.

> Ideally the test should be independant from sclang clock.

We should observe the behavior that occurs in typical use cases, e.g. performing onstage for 10, 15, 30, 60 minutes, real time, sclang clock driving and 1-2 sample jitter being acceptable. (It's a basic assumption in software QE that you should test stress conditions, not only ideal conditions.)

Also that suggestion would make it essentially impossible to run a long-duration test. There's a hard limit on the number of OSC messages that may be queued in the server, and this is not configurable. Max is 1024 I think. Over 10 minutes I'm producing 6000 pulses, impossible if we have to send all the bundles right now with timestamps.

**Comment by sonoro1234** [comment]
> Also that suggestion would make it essentially impossible to run a long-duration test. There's a hard limit on the number of OSC messages that may be queued in the server, and this is not configurable. Max is 1024 I think. Over 10 minutes I'm producing 6000 pulses, impossible if we have to send all the bundles right now with timestamps.

(test updated in #4596 (comment))

also tested 360 secs with 100 impulses per second sent in clusters of 1000 events:
440 442 441.00319462192 0.16722543927958

**Comment by sonoro1234** [comment]
> But it ran for 3 minutes very smoothly, and then there was a huge jump. I'd expect slight discrepancies to be distributed over time, so that each individual delta might be subject to a small adjustment but no single adjustment is very large.

It depends on how offten is sclang clock updated

**Comment by sonoro1234** [comment]
> Over 10 minutes I'm producing 6000 pulses, impossible if we have to send all the bundles right now with timestamps.

If it is possible to do what s.sendBundle does but with absolute instead of incremental time, sending in clusters of 1024 events would be more independent from sclang clock

**Comment by jamshark70** [comment]
> would be more independent from sclang clock.

Maybe you're not quite understanding my point.

If you get an ideal result when testing under ideal conditions, that gives more confidence in the algorithm, but it doesn't matter because *those ideal conditions don't reflect the way people actually use SC* in live performances in front of an audience.

I'll run some more tests today (taking more care to avoid #4375) and I hope for a cleaner result. But I'd like to be sure it's understood that testing relative to sclang's clock is relevant because this is the real world use case. If it works in the lab but it doesn't work on stage, then it doesn't really work. Let me see what happens with it today.

**Comment by jamshark70** [comment]
Some good news!

This morning, I woke the computer from sleep as usual, did some reading about open frameworks for an hour or so (plenty of time to get past issue #4375), and only after that redid the 600 second test.

The results are the same as the 10 or 60 second tests -- i.e., **pass** :grin:

```
[ 4409, 4411, 4409.9596420425, 4410 ]
569.8947845805 seconds between first and last, expected 569.9

[ 4409, 4411, 4409.9254255132, 4410 ]
569.89036281179 seconds between first and last, expected 569.9
```

Only +/-1 sample deviation, no drift, not even temporary drift. That's as good as it's gonna get.

So:

- The weird results I got yesterday are completely explained by #4375. (I thought the first test was valid, but I might not have waited long enough after waking the computer.)
- When I'm 100% sure that I avoided #4375, this PR provides timing accuracy that matches what we measured against CoreAudio and PortAudio, and this is consistently reproducible in multiple tests.

With that, I'm totally confident that the fix is valid.

I'd like to package my test case into a UnitTest method. It would be good to check in the test suite for bad handling of OSC timestamps (or clock misbehavior).

**Comment by sonoro1234** [comment]
> With that, I'm totally confident that the fix is valid.

Great!!
Out of curiosity: Is it possible with sclang to send OSC bundles with an absolute time?



> if we forcibly `#define SC_JACK_USE_DLL` in all cases (i.e. this isn't configurable in cmake), then what is the point of the `#ifdef`s?

I did the original addition of using SC_TimeDLL, it was experimental then, I would make it mandatory leaving only the code in `#ifdef SC_JACK_USE_DLL `, but this also should be done in portaudio with `SC_PA_USE_DLL` and portaudio files are now on some PR process by dyfer, so I would do that after portaudio is done.



> "SC_JACK dont multiply by 0" is not a very informative commit message.

It was the name of a commit in a series, when I "combined to one" the commits, this name was left and I dont know how to change the commit name now. How is it done?

**Comment by jamshark70** [comment]
> Out of curiosity: Is it possible with sclang to send OSC bundles with an absolute time?

It may be possible with NetAddr:sendRaw, but then the user is responsible for converting the time into OSC timestamp format. I don't know of any sclang primitives to help with that so the user might have to implement the conversion herself. In other words, it isn't very practical.

> I did the original addition of using SC_TimeDLL, it was experimental then, I would make it mandatory...

Sure, that makes sense. This should be done before merging.

> It was the name of a commit in a series, when I "combined to one" the commits, this name was left and I dont know how to change the commit name now.

Ah ok, one of those magic automated git things that never does exactly what you want. I tend to use `git rebase -i` to squash commits bc you can edit commit messages first.

You can probably amend the commit and force push. It's not merged so nobody is relying on that specific commit hash.

> Could you approve this PR?

No, it wouldn't be right to approve a PR before it's undergone style review. As I said earlier, I'm not competent to review C++ changes. It will have to be another developer.

**Comment by sonoro1234** [comment]
> No, it wouldn't be right to approve a PR before it's undergone style review. As I said earlier, I'm not competent to review C++ changes. It will have to be another developer.

Who is going to do it?

**Comment by dyfer** [comment]
do we know why timeDLL was not used beforehand?

**Comment by dyfer** [comment]
> > "SC_JACK dont multiply by 0" is not a very informative commit message.
> 
> It was the name of a commit in a series, when I "combined to one" the commits, this name was left and I dont know how to change the commit name now. How is it done?

I think if you do `git commit --amend` then you can edit the commit message. You would have to force push afterwards. (I also might be wrong...)

**Comment by dyfer** [comment]
I have tested this on macOS with native JACK backend.

The fix seem to work... although scsynth still seems to have more jitter than supernova. Similar discrepancy between supernova and scsynth occurs when not using JACK on my system.

Tests with this fix:
``` supercollider
//test 10s
[ 480, 481, 480.02900107411, 480 ] //scsynth
[ 480, 480, 480.0, 480.0 ] //supernova
```
Screen Shot 2019-10-02 at 12 22 48 PM

```supercollider
// test 20s
[ 479, 481, 479.99893786511, 480 ] //scsynth
[ 480, 481, 480.00053106745, 480 ] //supernova
```
Screen Shot 2019-10-02 at 12 29 41 PM

So I can attest that the fix works as advertised. Someone else should review the C++ part of this.

**Comment by sonoro1234** [comment]
Thanks @dyfer

**Comment by jamshark70** [comment]
I'd like to flag this one for the next release. IMO this is a critical fix for Linux (well, any Jack environment, but that's basically all Linux users).

File: server/scsynth/SC_Jack.cpp [hunk 1]
```diff
@@ -305,6 +305,9 @@ void SC_JackDriver::ConnectClientOutputs(const char* pattern) {
     free(ports);
 }
 
+
+static inline double sc_JACKOSCTimeSeconds() { return (uint64)OSCTime(getTime()) * kOSCtoSecs; }
+#define SC_JACK_USE_DLL
```
Comment (brianlheim) [inline server/scsynth/SC_Jack.cpp]: can you please do what the preprocessor would do anyway and remove all the code sections that are now turned off by this? then remove this line.

File: server/scsynth/SC_Jack.cpp [hunk 2]
```diff
@@ -305,6 +305,9 @@ void SC_JackDriver::ConnectClientOutputs(const char* pattern) {
     free(ports);
 }
 
+
+static inline double sc_JACKOSCTimeSeconds() { return (uint64)OSCTime(getTime()) * kOSCtoSecs; }
```
Comment (brianlheim) [inline server/scsynth/SC_Jack.cpp]: 1. `inline` is not necessary here
2. `uint64` cast is unnecessary since the result of OSCTime will be implicitly converted to a double to perform the following multiplication
3. please place this at the start of the file with the other free functions (e.g., oscTimeNow, which you could actually use in this function)
4. we use webkit naming conventions:

https://github.com/supercollider/supercollider/wiki/Cpp-code-style-guidelines#naming
https://webkit.org/code-style-guidelines/#names-basic

in particular, note:

> Lower-case the first letter, including all letters in an acronym, in a variable or function name.

so this should be `sc_jackOscTimeSeconds()`.

i'm also dubious about adding the `sc_` prefix, since that is typically (at least AFAICT) reserved for things that are kind of like the "supercollider API". what do you think about removing it?

File: server/scsynth/SC_Jack.cpp [hunk 3]
```diff
@@ -446,9 +453,9 @@ void SC_JackDriver::Run() {
 
         // main loop
 #ifdef SC_JACK_USE_DLL
-        int64 oscTime = mOSCbuftime = (int64)((mDLL.PeriodTime() + mMaxOutputLatency) * kSecondsToOSCunits + .5);
+        int64 oscTime = mOSCbuftime = (uint64)((mDLL.PeriodTime() + mMaxOutputLatency) * kSecondsToOSCunits + .5);
         // 		int64 oscInc = mOSCincrement = (int64)(mOSCincrementNumerator / mDLL.SampleRate());
-        int64 oscInc = mOSCincrement = (int64)((mDLL.Period() / numBufs) * kSecondsToOSCunits + .5);
+        int64 oscInc = mOSCincrement = (uint64)((mDLL.Period() / numBufs) * kSecondsToOSCunits + .5);
```
Comment (brianlheim) [inline server/scsynth/SC_Jack.cpp]: why did you change these casts? both of the things you're assigning to are `int64`

Comment (sonoro1234) [reply server/scsynth/SC_Jack.cpp]: all done

**Comment by sonoro1234** [comment]
Travis failing. Dont know why!!

**Comment by brianlheim** [comment]
@sonoro1234 not your problem -- #4692 needs to be merged

**Comment by brianlheim** [comment]
@sonoro1234 disregard my previous comment. your PR is failing the linting check (see log at https://travis-ci.org/supercollider/supercollider/jobs/628907793?utm_medium=notification&utm_source=github_status)

**Comment by sonoro1234** [comment]
```
C:\supercolliderrepos\scfork\supercollider\tools>clang-format.py formatall
  File "C:\supercolliderrepos\scfork\supercollider\tools\clang-format.py", line 583, in main
    do_formatall(options.clang_format)
  File "C:\supercolliderrepos\scfork\supercollider\tools\clang-format.py", line 502, in do_formatall
    clang_format = ClangFormat(clang_format)
  File "C:\supercolliderrepos\scfork\supercollider\tools\clang-format.py", line 232, in __init__
    raise ValueError("Could not find clang-format at %s" % cf_cmd)

*** ERROR:
Could not find clang-format at clang-format
```

**Comment by brianlheim** [comment]
https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions#linting-and-formatting

did you follow the instructions here?

**Comment by sonoro1234** [comment]
formatall seems to be done!!

File: server/scsynth/SC_Jack.cpp (hunk 3 above)
Comment (brianlheim) [reply server/scsynth/SC_Jack.cpp]: still not sure about this one, can you explain the change?

Comment (sonoro1234) [reply server/scsynth/SC_Jack.cpp]: This code is no more active!!

Comment (brianlheim) [reply server/scsynth/SC_Jack.cpp]: sorry, i really don't understand your response. why change the cast from `(int64)` to `(uint64)`?

Comment (sonoro1234) [reply server/scsynth/SC_Jack.cpp]: sorry, I thought this code was not present!!
corrected now.
