### PR TITLE
scide: Fix missing icon

### LINKED ISSUE #3905: SCIDE icon not showing
A few things I've noticed compiling SC on Kubuntu 18.04

linux readme, command for Debian jack versions conflict, one or the other:
libjack-dev libjack-jackd2-dev

linux readme, qt install command for Debian may be missing this package:
libqt5svg5-dev

scide icon on kubuntu isn't showing, not installed? from install manifest:

/usr/local/share/pixmaps/supercollider.png
/usr/local/share/pixmaps/supercollider.xpm
/usr/local/share/pixmaps/sc_ide.svg

Icons from SuperCollider/icons directory aren't installed.

why is just this example in this location?
/usr/local/share/doc/SuperCollider/examples/onetwoonetwo.sc

### PR DESCRIPTION
**Pull request by snappizz**
Purpose and Motivation
----------------------

fixes #3905 -- SCIDE is missing an icon. turns out it was something silly, the `QIcon` path should be `:icons/blah` rather than `:/icons/blah`.

unfortunately we can't use the svg icon because of #2646 (icon appears tiny on some linux DEs), so i just used the PNGs.

Types of changes
----------------
- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [x] This PR is ready for review

### CODE REVIEW

File: editors/sc-ide/core/main.cpp [hunk 1]
```diff
@@ -98,7 +98,16 @@ int main( int argc, char *argv[] )
...
+    // Unfortunately, the SVG icon shows up as a tiny dot on some Linux window
+    // managers (see #3905, #2646). Best we can do here is a PNG.
+    // app.setWindowIcon(QIcon(":icons/sc-ide-svg"));
+    QIcon icon;
+    icon.addFile(":icons/sc-ide-512");
+    icon.addFile(":icons/sc-ide-128");
+    icon.addFile(":icons/sc-ide-64");
+    icon.addFile(":icons/sc-ide-32");
+    icon.addFile(":icons/sc-ide-16");
+    app.setWindowIcon(icon);
```
Comment (brianlheim) [inline editors/sc-ide/core/main.cpp]: i'm confused -- we have code for this both here and in main_window.cpp: 

https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/widgets/main_window.cpp#L229-L240

why is the code needed in both places, and why doesn't it match?

**Comment by patrickdupuis** [comment]
On Ubuntu 18.04, the SCIDE icon shows up again in the "About SuperCollider" window. I haven't noticed any other changes.

icon

**Comment by jreus** [comment]
The missing icon is still an issue for me. I'm running KDE on Kubuntu 20.04 and built the latest 12.1 SuperCollider from source. 
The icon is missing in the upper left corner of the IDE, and when using the task switcher. 
Screenshot_20211129_131258

**Comment by telephon** [comment]
the best is you reopen #3905
