### PR TITLE
Help Browser code execution

### LINKED ISSUE #4542: help browser: shift+enter doesn't evaluate code
hitting shift+enter doesn't evaluate the current line under cursor in the help browser.

## Environment

* SuperCollider version: 3.10.2 develop [6b7e6ec58]
* Operating system: macos 10.13.6
* Other details (Qt version, audio driver, etc.): 5.13.0

## Steps to reproduce

open help browser and evaluate any line with shift+enter. 
it will do nothing

## Debugging

the shift+enter keybinding function gets called in js (`evalLine()`) but it does nothing.
i inserted a `console.log` into `function setUpWebChannel(port)` in `scdoc.js` but it never logs, so i suspect `setUpWebChannel(port)` is never called and therefore `evalLine()` in turn will do nothing since `window.IDE` will be `undefined`.

i see this output in my terminal: 

```
~/Programming/supercollider/build @develop $ ./Install/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "127.0.0.1"
```

### PR DESCRIPTION
**Pull request by elgiano**
## Purpose and Motivation

Fixes #4542 and #4000

Explained more in detail in an RFC and open for discussion. Please let's discuss it, I don't want to push this in any way. I also would really benefit from some other pairs of eyes on it. And it needs testing on Windows.
RFC: https://github.com/elgiano/rfcs/blob/helpbrowser/rfcs/0009-helpbrowser-code-evaluation.md

- fixed code execution in both HelpBrowser class and Widget + in WebView, if the rendered webpage has selectLine()/selectRegion() javascript functions. It works with selected text/line, and with selected text/region.
- code execution in webviews is more consistently delegated to javascript, calling a function to get selected text, receiving it in a callback and then sending it to the interpreter
- a workaround WebView's "funny" keypress behavior, now keyDownAction works on WebView only when an url is set. It gets all events (including the ones swallowed by the renderer) without duplication. WebView parent widgets also get all keystrokes, except the ones swallowed by the web renderer when focusing an input field (like Shift+Enter).
- Using QcWebView in ScIDE Help Browser Widget

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
It works on Linux and Mac.~~Missing testing on Windows~~. Also on Windows, thanks @dyfer
- [x] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
I've built it on Windows and tested code execution in the Help Browser - works fine. I haven't had a chance to look deeper yet, but doesn't seem like there are any apparent issues with Windows at first glance.

**Comment by elgiano** [comment]
thanks for testing it @dyfer!

**Comment by elgiano** [comment]
Rebased on 3.11

File: QtCollider/widgets/QcWebView.cpp [hunk 1]
```diff
@@ -35,13 +34,15 @@
 #    include <QStyle>
 #    include <QWebEngineCallback>
 
+#    ifndef SCIDE_NO_QWIDGETFACTORY
+#        include "../QcWidgetFactory.h"
 QC_DECLARE_QWIDGET_FACTORY(WebView);
+#    endif
```
Comment (brianlheim) [inline QtCollider/widgets/QcWebView.cpp:40]: so, instead of this macro is it possible to just move this bit into a new cpp file? that would be a lot cleaner.

File: QtCollider/widgets/QcWebView.cpp [hunk 2]
```diff
@@ -159,7 +158,8 @@ void WebView::toPlainText(QcCallback* cb) const {
 void WebView::runJavaScript(const QString& script, QcCallback* cb) {
     if (page()) {
         if (cb) {
-            page()->runJavaScript(script, cb->asFunctor());
+            // convert QVariant to string until we deal with QVariants
+            page()->runJavaScript(script, [cb](const QVariant& t) { cb->call(t.toString()); });
```
Comment (brianlheim) [inline QtCollider/widgets/QcWebView.cpp:162]: i don't understand this comment

File: QtCollider/widgets/QcWebView.h [hunk 3]
```diff
@@ -58,13 +58,12 @@ class WebView : public QWebEngineView {
     Q_INVOKABLE void navigate(const QString& url);
 
 public Q_SLOTS:
-    void findText(const QString& searchText, bool reversed, QtCollider::QcCallback* cb);
```
Comment (brianlheim) [inline QtCollider/widgets/QcWebView.h:61]: IIRC the namespace here is intentional -- see line 49 above -- why did you remove it, and are you sure this works without it?

File: SCClassLibrary/Common/GUI/tools/HelpBrowser.sc [hunk 4]
```diff
@@ -233,16 +235,13 @@ HelpBrowser {
...
-					};
-
+				#newPath, oldPath = [url,webView.url].collect {|x|
+					if(x.notEmpty) {x.findRegexp("(^\\w+://)?([^#]+)(#.*)?")[1..].flop[1][1]}
 				};
-				if(newPath!=oldPath) {
-					HelpBrowser.new(newWin:true).goTo(url);
+
+				if(newPath!=oldPath && openNewWin) {
+						HelpBrowser.new(newWin:openNewWin).goTo(url);
```
Comment (brianlheim) [inline SCClassLibrary/Common/GUI/tools/HelpBrowser.sc:244]: please put spaces around operators in code that you touch

File: editors/sc-ide/CMakeLists.txt [hunk 5]
```diff
@@ -193,11 +193,14 @@ set(ide_webengine_moc_hdrs
...
     widgets/util/IDEWebChannelWrapper.hpp
     ${CMAKE_SOURCE_DIR}/QtCollider/widgets/web_page.hpp
+    ${CMAKE_SOURCE_DIR}/QtCollider/widgets/QcWebView.h
+    ${CMAKE_SOURCE_DIR}/QtCollider/QcCallback.hpp
 )
 set(ide_webengine_src
     widgets/help_browser.cpp
     widgets/util/WebSocketTransport.cpp
     ${CMAKE_SOURCE_DIR}/QtCollider/widgets/web_page.cpp
+    ${CMAKE_SOURCE_DIR}/QtCollider/widgets/QcWebView.cpp
```
Comment (brianlheim) [inline editors/sc-ide/CMakeLists.txt:203]: not something you can address in this PR but i think we need 1 or 2 new static libraries in the project for the common Qt code (the stuff being added here) and common non-Qt code (the stuff in common/)

File: editors/sc-ide/widgets/help_browser.cpp [hunk 6]
```diff
@@ -78,42 +69,52 @@ HelpBrowser::HelpBrowser(QWidget* parent): QWidget(parent) {
...
-    mLoadProgressIndicator->setIndent(10);
-
     QVBoxLayout* layout = new QVBoxLayout;
     layout->setContentsMargins(0, 0, 0, 0);
     layout->setSpacing(0);
     layout->addWidget(mWebView);
     setLayout(layout);
 
+    mLoadProgressIndicator = new LoadProgressIndicator;
+    mLoadProgressIndicator->setIndent(10);
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp:79]: why did these lines move?

File: editors/sc-ide/widgets/help_browser.cpp [hunk 7]
```diff
@@ -78,42 +69,52 @@ HelpBrowser::HelpBrowser(QWidget* parent): QWidget(parent) {
...
     // FIXME: should actually respond to class library shutdown, but we don't have that signal
     connect(scProcess, SIGNAL(classLibraryRecompiled()), mLoadProgressIndicator, SLOT(stop()));
 
-    // Delete the help browser's page to avoid an assert/crash during shutdown. See QTBUG-56441, QTBUG-50160.
-    // Note that putting this in the destructor doesn't work.
-    connect(QApplication::instance(), &QApplication::aboutToQuit, [webPage]() { delete webPage; });
-
     createActions();
 
+    mWebView->installEventFilter(this);
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp:101]: why did this call move?

**Review by brianlheim — COMMENTED** [review]
thanks! i haven't tested it yet but i have a few questions about the code before reviewing further

File: QtCollider/widgets/QcWebView.h (hunk 3 above)
Comment (brianlheim) [reply QtCollider/widgets/QcWebView.h:61]: i don't think you need the default argument either

**Comment by brianlheim** [comment]
thanks for the quick update @elgiano . if you can address https://github.com/supercollider/supercollider/pull/4883/files#r509325107 i'm ready to review the rest of the PR after that :)

**Comment by elgiano** [comment]
Yeah, thanks for looking at it @brianlheim!
The one you point out is the one I don't really understand. What do you suggest I do about it? Shall I make the class hierarchy (my idea), or could you explain a bit more what your proposal is?
Thankssssssssssssss

**Comment by elgiano** [comment]
I think I got what you meant now! I pushed all changes for your pre-review, I hope it's fine now :)

File: editors/sc-ide/widgets/help_browser.cpp [hunk 8]
```diff
@@ -114,6 +109,11 @@ HelpBrowser::HelpBrowser(QWidget* parent): QWidget(parent) {
 }
 
 void HelpBrowser::onPageLoad() {
+    // add these actions to weview's renderer, to capture shift+enter and possibly other swallowed shortcuts
+    ((OverridingAction*)mActions[EvaluateRegion])->addToWidget(mWebView->focusProxy());
+    ((OverridingAction*)mActions[Evaluate])->addToWidget(mWebView->focusProxy());
+
+    // unused: see HelpSource/scdoc.js and HelpSource/editor.js
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp:116]: is this comment saying all the webchannel/websocket stuff is unused now? if so, delete it, it's still there in source control

File: editors/sc-ide/widgets/help_browser.cpp [hunk 9]
```diff
@@ -91,10 +81,15 @@ HelpBrowser::HelpBrowser(QWidget* parent): QWidget(parent) {
 
     connect(mWebView, SIGNAL(loadStarted()), mLoadProgressIndicator, SLOT(start()));
     connect(mWebView, SIGNAL(loadFinished(bool)), mLoadProgressIndicator, SLOT(stop()));
+    connect(mWebView, SIGNAL(loadFinished(bool)), this, SLOT(onPageLoad()));
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp:84]: onPageLoad() can call mLoadProgressIndicator->stop(), we don't need both connections

File: editors/sc-ide/widgets/help_browser.cpp [hunk 10]
```diff
@@ -142,9 +142,11 @@ void HelpBrowser::createActions() {
     connect(ovrAction, SIGNAL(triggered()), this, SLOT(resetZoom()));
     ovrAction->addToWidget(this);
 
+    // eval actions are added to mWebView->focusProxy() in onPageLoad()
     mActions[Evaluate] = ovrAction = new OverridingAction(tr("Evaluate as Code"), this);
     connect(ovrAction, SIGNAL(triggered()), this, SLOT(evaluateSelection()));
-    ovrAction->addToWidget(this);
+    mActions[EvaluateRegion] = ovrAction = new OverridingAction(tr("Evaluate as Code Region"), this);
+    connect(mActions[EvaluateRegion], &OverridingAction::triggered, this, [=]() { this->evaluateSelection(true); });
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp:149]:
```suggestion
    mActions[EvaluateRegion] = new OverridingAction(tr("Evaluate as Code Region"), this);
    connect(mActions[EvaluateRegion], &OverridingAction::triggered, this, [this]() { this->evaluateSelection(true); });
```

since you don't use ovrAction

File: editors/sc-ide/widgets/help_browser.cpp [hunk 11]
```diff
@@ -114,6 +109,11 @@ HelpBrowser::HelpBrowser(QWidget* parent): QWidget(parent) {
 }
 
 void HelpBrowser::onPageLoad() {
+    // add these actions to weview's renderer, to capture shift+enter and possibly other swallowed shortcuts
+    ((OverridingAction*)mActions[EvaluateRegion])->addToWidget(mWebView->focusProxy());
+    ((OverridingAction*)mActions[Evaluate])->addToWidget(mWebView->focusProxy());
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp:114]: always prefer the least powerful cast, here it's static_cast:

```suggestion
    static_cast<OverridingAction*>(mActions[EvaluateRegion])->addToWidget(mWebView->focusProxy());
    static_cast<OverridingAction*>(mActions[Evaluate])->addToWidget(mWebView->focusProxy());
```

File: editors/sc-ide/widgets/help_browser.cpp [hunk 12]
```diff
@@ -104,7 +99,7 @@ HelpBrowser::HelpBrowser(QWidget* parent): QWidget(parent) {
 
     // Delete the help browser's page to avoid an assert/crash during shutdown. See QTBUG-56441, QTBUG-50160.
     // Note that putting this in the destructor doesn't work.
-    connect(QApplication::instance(), &QApplication::aboutToQuit, [webPage]() { delete webPage; });
+    connect(QApplication::instance(), &QApplication::aboutToQuit, [=]() { delete mWebView->page(); });
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp:102]: i think it can just be this?

```suggestion
    connect(QApplication::instance(), &QApplication::aboutToQuit, [mWebView]() { delete mWebView->page(); });
```

File: SCClassLibrary/Common/GUI/Base/QWebView.sc [hunk 13]
```diff
@@ -223,9 +224,25 @@ WebView : View {
...
+					}{
+						if(mods.isCtrl || mods.isCmd) {
+							view.runJavaScript("selectRegion()",this.onInterpret(_));
+						};
+					}
+				}
+			};
+		}{
+			this.keyDownAction = {}
+		}
```
Comment (brianlheim) [inline SCClassLibrary/Common/GUI/Base/QWebView.sc:244]: a couple notes here:

1. please redo the spacing on this section (see style guide here: https://github.com/supercollider/supercollider/wiki/Code-style-guidelines#whitespace), and switch from arg to pipe syntax.
2. i think `key.asHexString == "..."` could be `key == 0x...` instead, no need to convert it to a string
3. and, `char.ascii == 13` could be `char == Char.ret` or `char == $\r`.
4. the 2 innermost `if` blocks could be replaced with a `case` instead, this would be clearer in my opinion and you would have one less indentation level.

File: SCClassLibrary/Common/GUI/Base/QWebView.sc [hunk 14]
```diff
@@ -3,7 +3,7 @@ WebView : View {
 
 	var <onLoadFinished, <onLoadFailed, <onLoadProgress, <onLoadStarted, <onLinkActivated, <onLinkHovered, <onReloadTriggered, <onJavaScriptMsg,
 		<onSelectionChanged, <onTitleChanged, <onUrlChanged, <onScrollPositionChanged, <onContentsSizeChanged, <onAudioMutedChanged,
-		<onRecentlyAudibleChanged;
+		<onRecentlyAudibleChanged, <enterInterpretsSelection;
```
Comment (brianlheim) [inline SCClassLibrary/Common/GUI/Base/QWebView.sc:6]: i think this should be initialized to false

File: QtCollider/widgets/QcWebView.cpp [hunk 15]
```diff
@@ -228,29 +223,36 @@ void WebView::contextMenuEvent(QContextMenuEvent* event) {
...
-        }
+// webView's renderer keypresses don't arrive to webView
+// duplicate them
+bool WebView::eventFilter(QObject* obj, QEvent* event) {
+    if (event->type() == QEvent::KeyPress) {
+        QKeyEvent* keyEvent = static_cast<QKeyEvent*>(event);
+        QKeyEvent* newEvent =
+            new QKeyEvent(QEvent::KeyPress, keyEvent->key(), keyEvent->modifiers(), keyEvent->nativeScanCode(),
+                          keyEvent->nativeVirtualKey(), keyEvent->nativeModifiers(), keyEvent->text());
+        QApplication::postEvent(this, newEvent);
```
Comment (brianlheim) [inline QtCollider/widgets/QcWebView.cpp:234]: i would recommend this. i'm pretty sure QKeyEvent has a copy ctor.

```suggestion
        // takes ownership of newEvent
        QApplication::postEvent(this, new QKeyEvent(*static_cast<QKeyEvent*>(event))); 
```

File: QtCollider/widgets/QcWebView.h [hunk 16]
```diff
@@ -140,19 +135,20 @@ public Q_SLOTS:
     inline static QUrl urlFromString(const QString& str) { return QUrl::fromUserInput(str); }
 
 protected:
-    virtual void keyPressEvent(QKeyEvent*);
     virtual void contextMenuEvent(QContextMenuEvent*);
+    virtual bool event(QEvent* ev);
+    virtual bool eventFilter(QObject* obj, QEvent* event);
```
Comment (brianlheim) [inline QtCollider/widgets/QcWebView.h:140]: i believe all 3 of these should be marked `override`

**Review by brianlheim — CHANGES_REQUESTED** [review]
i think this approach makes sense overall. i have a few questions and then some comments assuming this is the way we want to proceed

File: editors/sc-ide/widgets/help_browser.cpp (hunk 12 above)
Comment (elgiano) [reply editors/sc-ide/widgets/help_browser.cpp:102]: That gives me "error: capture of non-variable mWebView", as we can't capture data members by value. We can capture `this` though:
```
connect(QApplication::instance(), &QApplication::aboutToQuit, [this]() { delete mWebView->page(); });
```

Comment (brianlheim) [reply editors/sc-ide/widgets/help_browser.cpp:102]: oops, thanks for catching that

File: QtCollider/widgets/QcWebView.h (hunk 16 above)
Comment (elgiano) [reply QtCollider/widgets/QcWebView.h:140]: how about virtual then? shall we keep it or remove it?

Comment (brianlheim) [reply QtCollider/widgets/QcWebView.h:140]: oh good question. usually i remove virtual when i add override since the virtual part is redundant

File: QtCollider/widgets/QcWebView.h [hunk 17]
```diff
@@ -140,19 +135,20 @@ public Q_SLOTS:
...
 
 public Q_SLOTS:
     void onPageReload();
     void onRenderProcessTerminated(QWebEnginePage::RenderProcessTerminationStatus, int);
     void onLinkClicked(const QUrl&, QWebEnginePage::NavigationType, bool);
-    void updateEditable(bool);
+    void updateEditable();
```
[the remark this answers is not in the document]
Comment (elgiano) [reply QtCollider/widgets/QcWebView.h:146]: ok! I moved the logic to setEditable, and setEditable implementation to the .cpp file

File: QtCollider/widgets/QcWebView.h [hunk 18]
```diff
@@ -42,7 +42,7 @@ class WebView : public QWebEngineView {
 
 public:
     Q_INVOKABLE void setFontFamily(int genericFontFamily, const QString& fontFamily);
-    Q_INVOKABLE void triggerPageAction(int action, bool checked);
+    Q_INVOKABLE void triggerPageAction(int action, bool checked = false);
```
[the remark this answers is not in the document]
Comment (elgiano) [reply QtCollider/widgets/QcWebView.h:45]: help_browser.cpp:271 and 275 are calling triggerPageAction without a second argument. Is this default unnecessary?

File: QtCollider/widgets/QcWebView.h [hunk 19]
```diff
@@ -58,13 +58,12 @@ class WebView : public QWebEngineView {
     Q_INVOKABLE void navigate(const QString& url);
 
 public Q_SLOTS:
-    void findText(const QString& searchText, bool reversed, QtCollider::QcCallback* cb);
+    void findText(const QString& searchText, bool reversed, QtCollider::QcCallback* cb = nullptr);
```
[the remark this answers is not in the document]
Comment (elgiano) [reply QtCollider/widgets/QcWebView.h:61]: I had left a reply under your other comment, but it was "pending" until short ago, sorry. I'll copy-paste:

I think the default there is nice, so that findText can also be called without a callback (see for instance HelpBrowser::findText in help_browser.cpp:255). What do you think?

File: QtCollider/widgets/QcWebView.cpp [hunk 20]
```diff
@@ -159,7 +153,8 @@ void WebView::toPlainText(QcCallback* cb) const {
 void WebView::runJavaScript(const QString& script, QcCallback* cb) {
     if (page()) {
         if (cb) {
-            page()->runJavaScript(script, cb->asFunctor());
+            // convert QVariant to string until we deal with QVariants
+            page()->runJavaScript(script, [cb](const QVariant& t) { cb->call(t.toString()); });
```
[the remark this answers is not in the document]
Comment (elgiano) [reply QtCollider/widgets/QcWebView.cpp:157]: Please see my comments above, and sorry they were "pending" until now

File: QtCollider/widgets/QcWebView.h (hunk 17 above)
[the remark this answers is not in the document]
Comment (elgiano) [reply QtCollider/widgets/QcWebView.h:143]: and got linker errors:
```
/bin/ld: libscide.a(moc_QcWebView.cpp.o): in function `QtCollider::WebView::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
moc_QcWebView.cpp:(.text+0xadf): undefined reference to `QtCollider::WebView::updateEditable()'
collect2: error: ld returned 1 exit status
make[2]: *** [editors/sc-ide/CMakeFiles/SuperCollider.dir/build.make:165: editors/sc-ide/scide] Error 1
make[1]: *** [CMakeFiles/Makefile2:3419: editors/sc-ide/CMakeFiles/SuperCollider.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/bin/ld: libsclang.a(moc_QcWebView.cpp.o): in function `QtCollider::WebView::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
moc_QcWebView.cpp:(.text+0xadf): undefined reference to `QtCollider::WebView::updateEditable()'
collect2: error: ld returned 1 exit status
make[2]: *** [lang/CMakeFiles/sclang.dir/build.make:141: lang/sclang] Error 1
make[1]: *** [CMakeFiles/Makefile2:3353: lang/CMakeFiles/sclang.dir/all] Error 2
```

File: QtCollider/widgets/QcWebView.h (hunk 18 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply QtCollider/widgets/QcWebView.h:45]: ohh i see now, it's because we're using this in SCIDE code now

File: SCClassLibrary/Common/GUI/Base/QWebView.sc [hunk 21]
```diff
@@ -2,8 +2,8 @@ WebView : View {
 	classvar urlHandlers;
 
 	var <onLoadFinished, <onLoadFailed, <onLoadProgress, <onLoadStarted, <onLinkActivated, <onLinkHovered, <onReloadTriggered, <onJavaScriptMsg,
-		<onSelectionChanged, <onTitleChanged, <onUrlChanged, <onScrollPositionChanged, <onContentsSizeChanged, <onAudioMutedChanged,
-		<onRecentlyAudibleChanged;
+	<onSelectionChanged, <onTitleChanged, <onUrlChanged, <onScrollPositionChanged, <onContentsSizeChanged, <onAudioMutedChanged,
+	<onRecentlyAudibleChanged, <enterInterpretsSelection = false;
```
Comment (brianlheim) [inline SCClassLibrary/Common/GUI/Base/QWebView.sc:6]: please undo the whitespace changes

File: QtCollider/widgets/QcWebView.cpp (hunk 2 above)
Comment (brianlheim) [reply QtCollider/widgets/QcWebView.cpp:157]: thanks for looking into it! since this is the last PR before the 3.11.2 release, let's just leave this as it is. if you're interested you can make another PR for it, i'd also be happy to take a look myself.

File: QtCollider/widgets/QcWebView.h (hunk 18 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply QtCollider/widgets/QcWebView.h:45]: this is fine, thanks for explaining :)

File: QtCollider/widgets/QcWebView.h (hunk 19 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply QtCollider/widgets/QcWebView.h:61]: yeah this makes total sense!

**Review by brianlheim — COMMENTED** [review]
thanks @elgiano ! the code all looks good. i want to test it out before approving/merging.

File: QtCollider/factories.cpp [hunk 22]
```diff
@@ -26,6 +26,11 @@
 
 QC_DECLARE_QWIDGET_FACTORY(QLabel);
 
+#ifdef SC_USE_QTWEBENGINE
+#   include "widgets/QcWebView.h"
```
Comment (brianlheim) [inline QtCollider/factories.cpp:30]: aghh, you need to add a space here for linting
```suggestion
#    include "widgets/QcWebView.h"   
```

**Comment by brianlheim** [comment]
@elgiano do we use websockets for anything at all after this PR?

File: QtCollider/widgets/QcWebView.cpp (hunk 2 above)
Comment (elgiano) [reply QtCollider/widgets/QcWebView.cpp:157]: ok, we keep it like it is then and I'll open another PR! Just to be extra clear, now all javascript calls from sclang will always return a string only

**Comment by elgiano** [comment]
> do we use websockets for anything at all after this PR?
After a little grep I haven't found any place where we are using them, which I also suspected.

File: HelpSource/editor.js [hunk 23]
```diff
@@ -38,7 +38,10 @@ const init = () => {
             lineWrapping: true,
             viewportMargin: Infinity,
             extraKeys: {
-                'Shift-Enter': evalLine
+                // noop: prevent both codemirror and the browser to handle Shift-Enter
+                'Shift-Enter': ()=>false
```
Comment (brianlheim) [inline HelpSource/editor.js:42]: missing a comma here

Comment (elgiano) [reply HelpSource/editor.js]: yesss, thanks for catching it! btw I changed to ()=>{} which looks like a more proper noop

**Review by brianlheim — APPROVED** [review]
thanks again! i think this is all good. now that we are not using the websocket code, i would like to remove that too, but that can be done on the develop branch after the 3.11.2 release.

i also tested the latest version myself on macOS 10.14, windows 10, and arch linux, all fine.

**Comment by elgiano** [comment]
Thanks a lot @brianlheim and @dyfer!!!
