### PR TITLE
sclang: fix crash with duplicate var names and improve warning

### LINKED ISSUE #7348: Interpreter crash (segfault) on duplicate instance variable name (??)
## Environment

* SuperCollider version: develop (3b43262)
* Operating system: macOS 14
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
Quarks.install("wslib")
// recompile the library
```

## Expected vs. actual behavior

Result in scide:
```
compiling class library...
Interpreter has crashed or stopped forcefully. [Exit code: 11]
```

Result when running sclang in terminal:
```
$ /Volumes/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
compiling class library...
	Found 875 primitives.
	Compiling directory '/Volumes/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Users/marcin/Library/Application Support/SuperCollider/Extensions'
	Compiling directory '/Users/marcin/Library/Application Support/SuperCollider/downloaded-quarks/XML'
	Compiling directory '/Users/marcin/Library/Application Support/SuperCollider/downloaded-quarks/wslib'
ERROR: Found duplicate instance variable name 'focusColor'
  in file '/Users/marcin/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/RoundNumberBox.sc'
  line 3 char 92:

  	classvar <>defaultFormatFunc, <>defaultInterpretFunc, <>defaultFontFace, <>defaultFontSize;


-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
  in file '/Users/marcin/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/SMPTEBox.sc'
  line 4 char 30:

  	var <fps = 1000, scaleValues;


-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
[1]    23964 segmentation fault  /Volumes/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
```

The primary issue is that some sclang code in a quark causes sclang segfault. I haven't investigated the exact class code - naturally that class has been working fine for years (including 3.15-dev from a few months ago).

A secondary issue is that the IDE does not seem to post the full error message.

Expected: no crash :)

### PR DESCRIPTION
**Pull request by JordanHendersonMusic**
## Purpose and Motivation

closes #7348

Bug was caused by dereferencing a pointer I thought would always be valid.

Also improves error messages, here are some examples.

```
compiling class library (debug build)...
        Found 890 primitives.
        Compiling directory '/home/jordan/.repo/SuperCollider/SCClassLibrary'
        Compiling directory '/home/jordan/.local/share/SuperCollider/downloaded-quarks/XML'
        Compiling directory '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib'
ERROR: Found duplicate instance variable name 'focusColor'
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/RoundNumberBox.sc'
  line 12 char 16:

        var <focusColor, <stringColor;
                  
        var <formatFunc, <>interpretFunc, <>allowedChars = "+-.eE*/()%pi";
-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
Duplicate found in superclass RoundNumberBox.
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/SMPTEBox.sc'
  line 3 char 8:

  SMPTEBox : RoundNumberBox {
          
        var <fps = 1000, scaleValues;
-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
Duplicate found in superclass RoundNumberBox.
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/RoundNumberBox.sc'
  line 420 char 15:

  SmoothNumberBox : RoundNumberBox {
                 
  
-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/SmoothSlider.sc'
  line 10 char 16:

        var <focusColor;
                  
  
-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
Duplicate found in superclass SmoothSlider.
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/SmoothSlider.sc'
  line 524 char 11:

  RoundSlider : SmoothSlider {
             
  
-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
Duplicate found in superclass SmoothSlider.
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/SmoothRangeSlider.sc'
  line 3 char 17:

  SmoothRangeSlider : SmoothSlider { 
                   
  
-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
Duplicate found in superclass SmoothRangeSlider.
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/SmoothRangeSlider.sc'
  line 407 char 16:

  RoundRangeSlider : SmoothRangeSlider {
                  
  
-----------------------------------
ERROR: Found duplicate instance variable name 'focusColor'
Duplicate found in superclass SmoothSlider.
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/SmoothMultiSlider.sc'
  line 8 char 17:

  SmoothMultiSlider : SmoothSlider {
                   
  
-----------------------------------
ERROR: Found duplicate instance variable name 'action'
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/EZSmoothRanger.sc'
  line 3 char 12:

                var action;
              
  
-----------------------------------
ERROR: Found duplicate instance variable name 'action'
Duplicate found in superclass EZSmoothRanger.
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/GUI/Views/EZSmoothRanger.sc'
  line 163 char 13:

  EZRoundRanger : EZSmoothRanger {
               
  
-----------------------------------
ERROR: Found duplicate instance variable name 'name'
  in file '/home/jordan/.local/share/SuperCollider/downloaded-quarks/wslib/wslib-classes/Main Features/File management/FolderLibrary.sc'
  line 97 char 10:

        var <name;
            
        var <>contents;
-----------------------------------
ERROR: Library has not been compiled successfully.
```

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

### CODE REVIEW

**Review by dyfer — APPROVED** [review]
I can confirm that this 1) prints the duplicate errors and 2) does not crash interpreter.

I can't review the cpp part of this, but if you think it's solid I'm fine with merging this. Alternatively, someone else could look that over...

**Comment by dyfer** [comment]
Great, I now see a couple dozen instances of duplicate variables in both my classes and in some public quarks.

@JordanHendersonMusic thank you for fixing this so quickly!

**Comment by JordanHendersonMusic** [comment]
> thank you for fixing this so quickly!

You break it, you own it.

I know this will affect a lot of code.... here is one reason why it is necessary, I'm sure there are more.
```supercollider
A {
	var <a = 1;
	getA { ^a }
}

B : A {
	var <a = 2;
	getA { ^a }
}

A().a // 1
A().getA // 1

B().a // 2
B().getA // 1  woops!
```

I wonder if any one depends on this behaviour!!

**Comment by JordanHendersonMusic** [comment]
@Spacechild1 if you have a chance could you take a quick look at the C++ here, I'm pretty certain it is behaviourally correct, would just like another set of eyes before merging.

File: lang/LangSource/PyrParseNode.cpp [hunk 1]
```diff
@@ -803,23 +798,45 @@ void fillClassPrototypes(PyrClassNode* node, PyrClass* classobj, PyrClass* super
         return (maybe_duplicate != names.end()) ? std::optional<PyrSymbol*> { *maybe_duplicate } : std::nullopt;
     };
 
+    const auto attemptToPrintDuplicateLocation = [&](const PyrSymbol* duplicate, int varFlagType) {
+        if (node->mVarlists) {
```
Comment (Spacechild1) [inline lang/LangSource/PyrParseNode.cpp]: Very minor nitpick, but that if-check is redundant because of the for-loop below.

**Comment by Spacechild1** [comment]
Just from looking at the code and reading the commit messages, it is hard to tell what the actual fix was, as it only seems to improve the error printing. When I read the PR description, I understand that this prevents a NULL dereference because `mVarlists` may be NULL.

When you sqash and merge it, it would be good to mention this in the (squashed) commit message.

The code itself looks good to me!

**Comment by JordanHendersonMusic** [comment]
Okay, will do. Yes it is because the vardeflist is null but the class has duplicates in this case..


```
A { var a, a; }
B : A {}
```
`B` has duplicates but no vardeflist.

**Comment by dyfer** [comment]
Btw do we know why the IDE did not post the full output when there was a crash?

**Comment by JordanHendersonMusic** [comment]
Segfaulted before the print statement.

**Comment by dyfer** [comment]
But some printing was present when running sclang in the terminal as opposed to the ide...

**Comment by JordanHendersonMusic** [comment]
Oh I'm not too sure then, perhaps it has to do with when the buffer is flushed?

**Comment by dyfer** [comment]
> perhaps it has to do with when the buffer is flushed?

I'm guessing yes, something like that... it would be good to know the cause eventually, but it's not a priority imo.
