### PR TITLE
scide: Fix a dangling pointer when removing splits

### LINKED ISSUE #4133: Removing window split causes IDE crash on recompile
Environment
-----------

* Your SuperCollider version: 3.10 beta2 [d96cf6c43], Qt 5.11.1
* Your operating system and version: MacOS 10.13.6

Steps to reproduce (for bugs)
-----------------------------

The following causes the IDE to crash. It seems like at least 5 files need to be open for it to happen. 

(In IDE)
1. Session > New session
2. View > Split to Bottom
3. Open at least 5 files
4. View > Remove all splits
5. Recompile class library
6. Crash

Error message (for bugs)
------------------------

This is an excerpt from the crash report, with the crashing thread:
 
```
Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   org.qt-project.QtWidgets      	0x00000001078bc2e9 QWidgetTextControl::textCursor() const + 9
1   org.qt-project.QtWidgets      	0x000000010788dd69 QPlainTextEdit::textCursor() const + 25
2   net.sourceforge.supercollider 	0x00000001073ff043 0x1073eb000 + 81987
3   net.sourceforge.supercollider 	0x00000001073feb6e 0x1073eb000 + 80750
4   org.qt-project.QtCore         	0x000000010f7f319e QMetaObject::activate(QObject*, int, int, void**) + 2334
5   net.sourceforge.supercollider 	0x00000001074a391b 0x1073eb000 + 755995
6   net.sourceforge.supercollider 	0x000000010740d1ba 0x1073eb000 + 139706
7   org.qt-project.QtCore         	0x000000010f7f319e QMetaObject::activate(QObject*, int, int, void**) + 2334
8   org.qt-project.QtCore         	0x000000010f7f319e QMetaObject::activate(QObject*, int, int, void**) + 2334
9   org.qt-project.QtNetwork      	0x0000000108a4bdb5 0x1089a2000 + 695733
10  org.qt-project.QtNetwork      	0x0000000108a61e10 0x1089a2000 + 785936
11  org.qt-project.QtWidgets      	0x00000001076d046d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
12  org.qt-project.QtWidgets      	0x00000001076d1897 QApplication::notify(QObject*, QEvent*) + 583
13  org.qt-project.QtCore         	0x000000010f7c1f64 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
14  org.qt-project.QtCore         	0x000000010f81302b 0x10f5dc000 + 2322475
15  com.apple.CoreFoundation      	0x00007fff329e2898 __CFSocketPerformV0 + 1016
16  com.apple.CoreFoundation      	0x00007fff329c3a11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
17  com.apple.CoreFoundation      	0x00007fff32a7d42c __CFRunLoopDoSource0 + 108
18  com.apple.CoreFoundation      	0x00007fff329a6470 __CFRunLoopDoSources0 + 208
19  com.apple.CoreFoundation      	0x00007fff329a58ed __CFRunLoopRun + 1293
20  com.apple.CoreFoundation      	0x00007fff329a5153 CFRunLoopRunSpecific + 483
21  com.apple.HIToolbox           	0x00007fff31c8fd96 RunCurrentEventLoopInMode + 286
22  com.apple.HIToolbox           	0x00007fff31c8fb06 ReceiveNextEventCommon + 613
23  com.apple.HIToolbox           	0x00007fff31c8f884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
24  com.apple.AppKit              	0x00007fff2ff40a73 _DPSNextEvent + 2085
25  com.apple.AppKit              	0x00007fff306d6e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
26  com.apple.AppKit              	0x00007fff2ff35885 -[NSApplication run] + 764
27  libqcocoa.dylib               	0x0000000108c3e5bf 0x108c13000 + 177599
28  org.qt-project.QtCore         	0x000000010f7bd3de QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
29  org.qt-project.QtCore         	0x000000010f7c2552 QCoreApplication::exec() + 130
30  net.sourceforge.supercollider 	0x00000001073f253f 0x1073eb000 + 30015
31  libdyld.dylib                 	0x00007fff5a7e8015 start + 1
```

Expected Behavior
-----------------

It should not crash, but it does.

### PR DESCRIPTION
**Pull request by snappizz**
## Purpose and Motivation

Fixes #4133, supersedes #4363. When a GenericCodeEditor is destroyed but a Document refers to it via
mLastActiveEditor, said pointer is dangling and can cause a crash. For
example, creating a split, removing all splits, and then recompiling the
class library can cause a crash.

This commit is a quick bandage, simply setting mLastActiveEditor to a
null pointer in the GenericCodeEditor's destructor. A more thorough
solution would be a stack of the most recently active editors, but the
point is to just prevent an IDE crash right now.

## Types of changes

- Bug fix

## To-do list

- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
thanks! two more things to make this robust:

1. explicitly deleting all of copy assign, copy ctor, move assign, and move ctor for gce, with a note that any implementation would need to also update that pointer. this is typical "rule of 5"-- if you find yourself writing a custom move, copy, or dtor operation, you should probably be doing something custom with the others too. this will help to catch any places in the current code that expect the gce to always live at a stable memory address. i think copying a gce /might/ be okay, but i'd rather not think about it if we don't have to.

2. gce should also remove the reference to itself if its current doc is changed -- i believe there's at least one place where that happens right now.

**Comment by snappizz** [comment]
awesome, thanks for the info -- didn't know about Rule of 5

> gce should also remove the reference to itself if its current doc is changed -- i believe there's at least one place where that happens right now.

i can't find a reassignment of `mDoc` in either `GenericCodeEditor` or `ScCodeEditor`. if `mDoc` is in fact constant, then i can just make it a `const` and add a note about this.

**Comment by brianlheim** [comment]
> awesome, thanks for the info -- didn't know about Rule of 5

https://en.cppreference.com/w/cpp/language/rule_of_three

> i can't find a reassignment of mDoc in either GenericCodeEditor or ScCodeEditor.

aha, can you delete the misleading declaration of unimplemented `setDocument(Document*)` from the header then? that's probably what made me think that.

> making mDoc a const pointer works fine, so i have done so

nice!

File: editors/sc-ide/widgets/code_editor/editor.hpp [hunk 1]
```diff
@@ -41,6 +41,16 @@ class GenericCodeEditor : public QPlainTextEdit {
...
+    ~GenericCodeEditor();
+
+    // Rule of 5 -- with an explicit dtor, make sure that copy ctor, move ctor,
+    // copy assign, and move assign are deleted.
+    // If these must be implemented in the future, make sure they take care of
+    // mDoc->lastActiveEditor() appropriately. See source of dtor method.
+    GenericCodeEditor(const GenericCodeEditor& other) = delete;
+    GenericCodeEditor(GenericCodeEditor&& other) = delete;
+    GenericCodeEditor& operator=(const GenericCodeEditor& other) = delete;
+    GenericCodeEditor& operator=(GenericCodeEditor&& other) = delete;
```
Comment (brianlheim) [inline editors/sc-ide/widgets/code_editor/editor.hpp]: note for the future -- typically these are ordered as copy ctor, copy assign, move ctor, move assign. that's because they're all viewed of sort-of constructors, and grouping things by copy vs move semantics is easier to read logically.

File: editors/sc-ide/widgets/code_editor/editor.hpp [hunk 2]
```diff
@@ -41,10 +41,19 @@ class GenericCodeEditor : public QPlainTextEdit {
...
 public:
     GenericCodeEditor(Document*, QWidget* parent = NULL);
+    ~GenericCodeEditor();
+
+    // Rule of 5 -- with an explicit dtor, make sure that copy ctor/assign and move
+    // ctor/assign are deleted.
+    // If these must be implemented in the future, make sure they take care of
+    // mDoc->lastActiveEditor() appropriately. See source of dtor method.
+    GenericCodeEditor(GenericCodeEditor& other) = delete;
+    GenericCodeEditor& operator=(GenericCodeEditor& other) = delete;
```
Comment (brianlheim) [inline editors/sc-ide/widgets/code_editor/editor.hpp]: you dropped `const` from the copy ops when you moved them -- can you please add those back?

**Comment by snappizz** [comment]
sweet, thanks
