### PR TITLE
[bug] fix Signal equality

### LINKED ISSUE #3963: Signal equality returns true or false randomly
* SuperCollider version:
develop
macOS 10.13.6

Expected Behavior
-----------------
The same true or false result on the same test

Current Behavior
----------------
Random true or false on same test
Steps to reproduce (for bugs)
-----------------------------
```
20.collect { Signal[1] == Signal[1] }.asSet; // -> -> Set[true, false]
20.collect { Signal[1] == Signal[2] }.asSet; // ->Set[true, false]
```

### PR DESCRIPTION
**Pull request by patrickdupuis**
Purpose and Motivation
----------------------

Fixes #3963 

Types of changes
----------------

Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [X] All tests are passing

- [X] If necessary, new tests were created to address changes in PR (and tests are passing)

- [ ] Updated documentation, if necessary

- [X] This PR is ready for review

### CODE REVIEW

File: lang/LangSource/PyrSignal.cpp [hunk 1]
```diff
@@ -537,7 +537,7 @@ bool signal_equal_xx(VMGlobals *g, PyrObject* ina, PyrObject* inb)
 	float *endptr = a + ina->size;
 	if (ina->size != inb->size) return false;
 	if (slotRawSymbol(&ina->slots[ kSignalRate ]) != slotRawSymbol(&inb->slots[ kSignalRate ])) return false;
-	while (a < endptr) { if (*a++ != *b++) return false; }
+	while (a < endptr) { if (*++a != *++b) return false; }
```
Comment (snappizz) [inline lang/LangSource/PyrSignal.cpp]: this should be refactored for clarity:

```
while (a < endptr) {
    a++;
    b++;
    if (*a != *b) {
        return false;
    }
}
```

Comment (snappizz) [reply lang/LangSource/PyrSignal.cpp]: actually, let's keep this as clear as possible:

```
bool signal_equal_xx(VMGlobals *g, PyrObject* ina, PyrObject* inb)
{
	float *a = (float*)(ina->slots);
	float *b = (float*)(inb->slots);
	if (ina->size != inb->size) return false;
	if (slotRawSymbol(&ina->slots[ kSignalRate ]) != slotRawSymbol(&inb->slots[ kSignalRate ])) return false;
	for (int i = 0; i < ina->size; i++) {
		if (a[i] != b[i]) {
			return false;
		}
	}
	return true;
}
```

Comment (scztt) [reply lang/LangSource/PyrSignal.cpp]: I like using `std::equal`, and I would expect a performance bump since that's probably doing some simd optimization - but I would suggest merging the simple fix first, and then refactoring (with std::equal or whatever else) as a separate change.
Also, it's worth checking wether nova_simd has a wrapper for simd equality comparison - that could be the best thing to use here.
