### PR TITLE
various Server plugin changes/fixes

### LINKED ISSUE #6040: Windows: allow developers to ship .dll files next to .scx extensions
When developing new extensions, there might be the need of shipping them with external .dll / .so / .dynlib files to link against. Dynamically setting the `rpath` for Unix is quite simple, and it can be done when building the extension itself. On Windows, this is not possible to do. Instead, it must be done with a call to [SetDllDirectory](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectoryw) before calling `LoadLibrary`, which SC is currently not doing in its `PlugIn_Load` function.

The current workaround, which is admittedly quite ugly, is to prompt the users of the extension to copy the .dll next to the `scsynth` executable, following Windows' way of shipping dlls.

Would it be worth to add these changes to allow developers to ship .dll files next to .scx?

### PR DESCRIPTION
**Pull request by Spacechild1**
## Purpose and Motivation

This PR fixes several issues regarding Server plugins. The motivation is to ensure a uniform behavior across platforms. Most importantly:
1. use the same plugin extension (`.scx`) on all platforms
2. allow to ship shared library dependencies (`.dll`, `.dylib`, `.so`) together with the plugin

I have added a simple test plugin in `testsuite/server/plugins` that implements a function in a shared library. I can now successfully load this plugin on all three platforms!

## Changes

- Linux: change the plugin extension from `.so` to `.scx`. This means people can finally ship shared library dependencies together with their UGen plugins, without having to put them in special folders. **This is a breaking change!** However, I have provided the following upgrade path:
    
    If a `.so` file is in the same directory as a `.scx` file, or in any subdirectory, we assume it is a dependency of the `.scx` file and therefore ignore it. Otherwise we try to open the `.so` file as a plugin and post a warning to the console. We also post a (one-time) message that tells the user what they can do to avoid the warning.
    
    We can remove this workaround in SC 3.16 or SC 3.17
    
- Windows: call `SetDllDirectory` with the current plugin directory so that plugins can find DLLs in the same directory

- Linux/scsynth: fix segfault when `dlopen` fails.

- scsynth: only unload plugins after all Nodes have been destroyed.

- Supernova: follow symlinks when loading plugins and ignore special folders to ensure the same behavior as scsynth.

Closes #6040 and #7342.

## Types of changes

- Bug fix
- Breaking change

## To-do list

- [x] Code is tested
- [ ] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

File: server/scsynth/SC_Lib_Cintf.cpp [hunk 1]
```diff
@@ -65,8 +66,18 @@ HashTable<struct PlugInCmd, Malloc>* gPlugInCmds = nullptr;
...
+// parent folders we simply ignore the .so file because we can assume it is a dependency.
+// Otherwise we load the .so file and post a warning.
+// NOTE: we should remove this workaround in the future!
+#ifdef __linux__
+#    define LINUX_PLUGIN_WORKAROUND
+#endif
+
 void initMiscCommands();
-static bool PlugIn_LoadDir(const fs::path& dir, bool reportError);
+static bool PlugIn_LoadDir(const fs::path& dir, bool reportError, bool didFindPlugin = false);
```
Comment (JordanHendersonMusic) [inline server/scsynth/SC_Lib_Cintf.cpp]: `didFindPlugin`

I'm a bit confused as to what this argument does? Particularly since you write to it on line 438 when doing the linux work-around. Could it be renamed to something clearer?

If we are loading a directory then I'd expect a 'did find plugin' argument to be an out parameter.

Comment (Spacechild1) [reply server/scsynth/SC_Lib_Cintf.cpp]: Maybe `didFindScxFile` is clearer?

Comment (JordanHendersonMusic) [reply server/scsynth/SC_Lib_Cintf.cpp]: That implies it returns to the call sight whether or not it found a plugin, i.e., `bool& didFindScxFile`.

Is it `hasAlreadySeenFileWithSCXExtentionInDir`?

Comment (Spacechild1) [reply server/scsynth/SC_Lib_Cintf.cpp]: > That implies it returns to the call sight whether or not it found a plugin

Why? The name says nothing about whether it's an in or out parameter. However, the fact that it's a value, and not a reference, makes this pretty clear.

> Is it hasAlreadySeenFileWithSCXExtentionInDir?

You really like long variable names :-D What if I just add a comment above the function? Then `didFindScxFile` should be sufficient, I think.

Comment (Spacechild1) [reply server/scsynth/SC_Lib_Cintf.cpp]: Is it clearer with 5ae8786?

Comment (JordanHendersonMusic) [reply server/scsynth/SC_Lib_Cintf.cpp]: > The name says nothing about whether it's an in or out parameter. 

I read it like ... 'did find plugin?'. 

If I'm right about what it does, then perhaps, `hasSeenScxFile` would work? 

Comment would work to.

Comment (Spacechild1) [reply server/scsynth/SC_Lib_Cintf.cpp]: Aha, it's a grammer issue. `didFindScxFile` indeed reads like a question. So I guess `foundScxFile` should do it.

Comment (JordanHendersonMusic) [reply server/scsynth/SC_Lib_Cintf.cpp]: > `foundScxFile`

Sounds good!

Comment (Spacechild1) [reply server/scsynth/SC_Lib_Cintf.cpp]: What about 523f84b?

File: server/supernova/sc/sc_ugen_factory.cpp [hunk 2]
```diff
@@ -215,22 +225,82 @@ bool sc_plugin_container::run_cmd_plugin(World* world, const char* name, struct
...
+    for (const auto& entry : fs::directory_iterator(dir, options)) {
+        if (fs::is_directory(entry.path())) {
+            load_plugin_folder(entry.path(), found_scx_file);
+        } else if (!found_scx_file && entry.path().extension() == ".so") {
+            // No .scx plugins were found in this directory or any parent directory -> assume the .so file is a plugin.
+            load_plugin(entry.path());
+            std::cout << "*** WARNING: '" << SC_Codecvt::path_to_utf8_str(entry.path()).c_str()
+                      << "': the .so extension has been deprecated!" << std::endl;
+
+            static bool didWarn = false;
```
Comment (JordanHendersonMusic) [inline server/supernova/sc/sc_ugen_factory.cpp:292]: I'm not super familiar with supernova... is there any chance of multiple threads accessing this static at the same time?

Edit: it wouldn't be the end of the world because its just a bool and the write is a single instruction, worse that would happen is you get multiple posts, but it would be good to know.

File: server/scsynth/SC_Lib_Cintf.cpp (hunk 1 above)
Comment (JordanHendersonMusic) [reply server/scsynth/SC_Lib_Cintf.cpp]: Looks good, much clearer.

File: server/supernova/sc/sc_ugen_factory.cpp (hunk 2 above)
Comment (Spacechild1) [reply server/supernova/sc/sc_ugen_factory.cpp:292]: No. Only UGen calc functions can run in parallel.

Comment (JordanHendersonMusic) [reply server/supernova/sc/sc_ugen_factory.cpp:292]: Thanks!

**Review by JordanHendersonMusic — APPROVED** [review]
Merge after CI.
