### PR TITLE
Topic/simplenumber series

### LINKED ISSUE #4452: SimpleNumber:series can overshoot its last value
## Environment

* SuperCollider version: SC develop at 7227a4d2d
* Operating system: macOS 10.14

## Steps to reproduce

This fixes a bug wherein `SimpleNumber:series` can overshoot its last value if the step is specified as a `float` and does not evenly divide into the range of the series.

The problem is illustrated here:

```supercollider
(0, 39952.0 .. 958845).last
// -> 958848.0 // overshoots 'last' value
(0, 39952   .. 958845).last
// -> 918896   // int type stops short of 'last', as expected
(0, 2.00001 .. 8).last
// -> 8.0004   // overshoots when step is near an even division
(0, 3.0 .. 8.0).last
// -> 6.0      // otherwise stops short of the 'last' value
```

## Expected vs. actual behavior

I would expect all returned values to be within the range of `first` and `last`, with the `returnedArray.last <= last`.

The problem is here:
https://github.com/supercollider/supercollider/blob/7227a4d2d3b1d37273815245ced1f4e71b87da41/lang/LangPrimSource/PyrMathPrim.cpp#L865
Where it looks like the algorithm may have been just copied from the commented-out `sclang` method it replaced:
https://github.com/supercollider/supercollider/blob/7227a4d2d3b1d37273815245ced1f4e71b87da41/SCClassLibrary/Common/Math/SimpleNumber.sc#L616-L624

If it's agreed this is is in fact a bug, I have a PR ready to go.

### PR DESCRIPTION
**Pull request by mtmccrea**
## Purpose and Motivation

This fixes #4452, where `SimpleNumber:series` can overshoot its last value if the step is specified as a `float` and does not evenly divide into the range of the series.

The problem is illustrated here:
```supercollider
(0, 39952.0 .. 958845).last
// -> 958848.0 // overshoots 'last' value
(0, 39952   .. 958845).last
// -> 918896   // int type stops short of 'last', as expected
(0, 2.00001 .. 8).last
// -> 8.0004   // overshoots when step is near an even division
(0, 3.0 .. 8.0).last
// -> 6.0      // otherwise stops short
```

## Types of changes
- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by mtmccrea** [comment]
Looks like one of the travis builds failed:

> `C++ QT=false DO_LINT=true 44 sec linux`

with this error:
>`clang-format` found, but incorrect version at clang-format with version: clang-format version 5.0.0 (tags/RELEASE_500/final)`

Is this a problem with the CI build configuration? Looks like the `clang-format` version needs to be specified to be `8.0.0`

**Comment by brianlheim** [comment]
@supercollider/reviewers Anyone want to take this one? :)

File: lang/LangPrimSource/PyrMathPrim.cpp [hunk 1]
```diff
@@ -862,7 +862,7 @@ int prSimpleNumberSeries(struct VMGlobals* g, int numArgsPushed) {
         }
 
         step = second - first;
-        size = (int)floor((last - first) / step + 0.001) + 1;
```
Comment (lnihlen) [inline lang/LangPrimSource/PyrMathPrim.cpp]: You're right to catch that this line creates a bug, but I also worry that it prevents a different bug. Is it now possible to create a divide-by-zero error here with a zero value for step? I tested this patch with a step=0 and I know the error check on line 867 is catching this, but would it make sense to add a special check for a zero step size and report that error before attempting the divide?

Comment (lnihlen) [reply lang/LangPrimSource/PyrMathPrim.cpp]: Hey @mtmccrea thanks for the PR! I had one question but overall looks good.

Comment (mtmccrea) [reply lang/LangPrimSource/PyrMathPrim.cpp]: Thanks for having a look at this @lnihlen!

Good catch. I tested the 0-step case and it was caught as you saw, but it's a good point about the divide by zero.

Out of curiosity, I inserted some checks to see what the math was doing:
```
        step = second - first;
		post(
			 "prSimpleNumberSeries: first: %f, step: %f, last %f\n",
			 first, step, last);
        size = (int)((last - first) / step) + 1;
		post(
			 "prSimpleNumberSeries: size: %d\n", size);
		
        if ((size < 1) || ((step >= 0) && (last < first)) || ((step <= 0) && (last > first))) {
            post(
                "prSimpleNumberSeries: arguments do not form an arithmetic progression: first: %f, step: %f, last %f\n",
                first, step, last);
            return errFailed;
        }
```
and with this input:
`(1.2, 1.2 .. 100)`
here's what went through:
```
prSimpleNumberSeries: first: 1.200000, step: 0.000000, last 100.000000
prSimpleNumberSeries: size: -2147483647
prSimpleNumberSeries: arguments do not form an arithmetic progression: 
first: 1.200000, step: 0.000000, last 100.000000
```

So yes, worth catching.
I found that there was an inconsistency between `Int` and `Float` behavior:
```
/* 0-step, first == last */
1.series(1, 1)
// -> [ 1 ]
1.2.series(1.2, 1.2)
// -> ERROR: Primitive '_SimpleNumberSeries' failed.
```
So rather than error out on a step of `0`, I now catch the case and set `size` to `1`. So the behavior is now consistent with `Int`:
```
/* 0-step, first == last */
1.series(1, 1)
// -> [ 1 ]
1.2.series(1.2, 1.2)
// -> [ 1.2 ]
```

I'll push this change shortly.
Thanks!

Comment (mtmccrea) [reply lang/LangPrimSource/PyrMathPrim.cpp]: I've also added a unit test for this case.

**Comment by lnihlen** [comment]
Sweet, thanks for the great follow-through @mtmccrea! Looks like CI is reporting a C++ linter error on the change to the error reporting string, but otherwise this is LGTM.

**Comment by mtmccrea** [comment]
Working through some `clang-format` issues now...

**Comment by mtmccrea** [comment]
OK, so it looks like appveyor CI is getting caught up on linting issues on lines that the `clang-format.py` script itself modified (4134851).
Does that mean there's either a drift in the rules between my clang-format, and the one installed on the ci machine?
Perhaps @brianlheim has seen an issue like this?

**Comment by lnihlen** [comment]
Which version of clang-format are you using? We are pinned on 8.0.0 right now.

**Comment by mtmccrea** [comment]
```
-> clang-format --version
clang-format version 8.0.0 (tags/RELEASE_800/final)
```

**Comment by mtmccrea** [comment]
FWIW the edit that `clang-format` made appears to be related to capping the line length, then wrapping the remainder to the next line, and indenting it to align with the open parenthesis of the `post(` method above it.

**Comment by mtmccrea** [comment]
I think I may have found the problem. We'll see what CI says...

**Comment by mtmccrea** [comment]
OK CI is passing. 

This may be a missed case in `clang-format`. It was actually a couple lines above the auto-format change I mentioned before. There was a line with auto-indent spaces at the beginning but the line was otherwise empty. Running:
```
-> python3 ../tools/clang-format.py lint
--- lang/LangPrimSource/PyrMathPrim.cpp	(before formatting)
+++ lang/LangPrimSource/PyrMathPrim.cpp	(after formatting)
@@ -867,7 +867,7 @@
         } else {
             size = (int)((last - first) / step) + 1;
         }
-        // << THERE ARE SPACES HERE
+
         if ((size < 1) || ((step >= 0) && (last < first)) || ((step <= 0) && (last > first))) {
             post("prSimpleNumberSeries: arguments do not form an arithmetic progression:\n\tfirst: %f, step: %f, last "
                  "%f\n",
```
Yet running:
```
-> python3 ../tools/clang-format.py format
```
does not remove these spaces. So it's caught when CI lints the file.

I can file this as a bug if it's agreed this shouldn't happen.

**Comment by mtmccrea** [comment]
Thanks, @lnihlen! I've filed the format issue: #4464.
