### PR TITLE
scide: Find an open port for WebSocket communication with SCDoc rather than hardcoding port 12344

### LINKED ISSUE #4177: [IDE] Can only have one instance of IDE open at a time
Environment
-----------

* Your SuperCollider version: 3.10.0
* Your operating system and version: MacOS 10.13.6

Steps to reproduce (for bugs)
-----------------------------

Try two open two separate instances of the IDE. The second one doesn't open.

This is a direct result of https://github.com/supercollider/supercollider/pull/3960; the second IDE instance tries to open its web socket on the same port and fails. When run from the command line this is the output:

```
Failed to open web socket server.
Received signal 6
 [0x000117450773]
 [0x7fff67fa6f5a]
 [0x00011585a960]
 [0x7fff67d441ae]
 [0x000110a8dadd]
 [0x00010f268ba3]
 [0x7fff67c98015]
[end of stack trace]
Abort trap: 6
```

Not sure if this is a 'bug' or a 'feature'. If it's a bug, the IDE could communicate to the help browser what port it's using, and find one by linearly scanning if the hardcoded one isn't available. Not sure off the top of my head how to do that. Maybe by setting local storage in the web view or executing a JS snippet on creation. At any rate this value needs to be available in the help browser's JS code.

If it's a 'feature', we should just show a popup that says 'you can't do that!' and quit.

### PR DESCRIPTION
**Pull request by snappizz**
Purpose and Motivation
----------------------

fix #4177 and #4256 with the following changes:

- the web socket server finds an open port rather than hardcoding port 12344.
- if the web socket server setup fails, SCIDE still starts. i'm not sure it's good to allow multiple IDE's running, but the regression in 3.10 shouldn't have happened. there's no need for a failed web socket connection to be a fatal error!
- scdoc.js is smarter about recognizing whether it's in the IDE, and doesn't print errors.

Testing
-----

- if there is already an instance of SCIDE open, you should be able to open another SCIDE without the latter crashing at start.
- you should be able to run code from the help browser in any open instance of SCIDE.
- if you have SCIDE open and you fire up a command-line sclang and run `HelpBrowser()` at it, there should be no error about websockets in the command line. (a weird `QObject::connect` error will appear, which is a different bug unrelated to this PR.)
- SCIDE should compile and run fine even if SC_USE_QTWEBENGINE is off (`cmake -DSC_USE_QTWEBENGINE=OFF ..`).

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [x] Updated documentation, if necessary
- [x] This PR is ready for review

### CODE REVIEW

File: editors/sc-ide/core/main.cpp [hunk 1]
```diff
@@ -135,22 +131,7 @@ int main( int argc, char *argv[] )
...
-    // setup comm channel
-    WebSocketClientWrapper clientWrapper(&server);
-    QWebChannel channel;
-    QObject::connect(&clientWrapper, &WebSocketClientWrapper::clientConnected,
-                     &channel, &QWebChannel::connectTo);
-
-    // publish IDE interface
-    IDEWebChannelWrapper ideWrapper{win->helpBrowserDocklet()->browser()};
-    channel.registerObject("IDE", &ideWrapper);
+    win->helpBrowserDocklet()->browser()->setUpServer();
```
Comment (snappizz) [inline editors/sc-ide/core/main.cpp]: i've tried calling `setUpServer()` in the constructor for `HelpBrowser`, but it just doesn't work (client does not establish connection and prints an error). it has to be called in this exact spot. i'm not sure why

Comment (brianlheim) [reply editors/sc-ide/core/main.cpp]: you have a dangling pointer in `setUpServer`. that might have something to do with it; I'll try to review this PR in detail soon (this week). thanks for getting it started!

File: editors/sc-ide/widgets/help_browser.hpp [hunk 2]
```diff
@@ -116,6 +116,8 @@ class HelpBrowser : public QWidget
     
     bool helpBrowserHasFocus() const;
 
+    void setUpServer(void);
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.hpp]: get rid of `(void)`.

File: editors/sc-ide/widgets/help_browser.cpp [hunk 3]
```diff
@@ -27,6 +27,9 @@
 #include "../core/util/overriding_action.hpp"
 #include "QtCollider/widgets/web_page.hpp"
 #include "QtCollider/hacks/hacks_qt.hpp"
+#include "../widgets/util/WebSocketClientWrapper.hpp"
+#include "../widgets/util/WebSocketTransport.hpp"
+#include "../widgets/util/IDEWebChannelWrapper.hpp"
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp]: can simplify all these paths to `util/xyz.hpp`

File: editors/sc-ide/widgets/help_browser.cpp [hunk 4]
```diff
@@ -120,6 +124,41 @@ HelpBrowser::HelpBrowser( QWidget * parent ):
...
+        QWebChannel channel;
+        QObject::connect(&clientWrapper, &WebSocketClientWrapper::clientConnected,
+                         &channel, &QWebChannel::connectTo);
+
+        // publish IDE interface
+        IDEWebChannelWrapper ideWrapper{this};
+        channel.registerObject("IDE", &ideWrapper);
+    } else {
+        qWarning("Failed to set up help browser server.");
+    }
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp]: all of these objects need to live for the lifetime of the program (or at least the help browser); best to keep this in `main` I think. you can communicate the port to the help browser with a member function (like `setServerPort(int)`)

File: HelpSource/scdoc.js [hunk 5]
```diff
@@ -198,8 +198,13 @@ function fixTOC() {
 // Set up a QWebChannel for communicating with C++ IDE objects. The main app publishes a handle
 // to IDE functionality at "IDE" which is made globally available here after the page and
 // WebSocket have loaded.
-function setUpWebChannel() {
-    var baseUrl = "ws://localhost:12344";
+
+// This function is called by the IDE, and will not be called otherwise.
+function setUpWebChannel(port) {
+    if (typeof QWebChannel === "undefined") {
```
Comment (brianlheim) [inline HelpSource/scdoc.js]: is it even possible for this to evaluate to false when it's called from the IDE code?

File: editors/sc-ide/widgets/help_browser.cpp [hunk 6]
```diff
@@ -120,6 +124,41 @@ HelpBrowser::HelpBrowser( QWidget * parent ):
...
+}
+
+void HelpBrowser::onPageLoad()
+{
+    if (!mServerRunning) {
+        return;
+    }
+    mWebView->page()->runJavaScript(QString("setUpWebChannel(%1)").arg(mServerPort));
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp]: again this is more verbose than it needs to be:

```cpp
if (mServerPort >= 0) { // see comment below
    mWebView->page()->...
}
```

File: editors/sc-ide/widgets/help_browser.hpp [hunk 7]
```diff
@@ -154,6 +157,9 @@ private slots:
     QSize mSizeHint;
 
     QAction *mActions[ActionCount];
+
+    bool mServerRunning = false;
+    int mServerPort = 12344;
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.hpp]: you could have two members here, but you really only need one if you use a default value of `-1` or some other invalid-by-definition port number; opinions differ on it, but I find this use of bools kind of wasteful since the semantics are obvious. and in fact, it makes the logic above (in setUpServer) more difficult to follow.

File: editors/sc-ide/widgets/help_browser.cpp [hunk 8]
```diff
@@ -120,6 +124,41 @@ HelpBrowser::HelpBrowser( QWidget * parent ):
...
+
+    // setup HelpBrowser server
+    QWebSocketServer server("SCIDE HelpBrowser Server", QWebSocketServer::NonSecureMode);
+    for (int i = 0; i < 8; i++) {
+        mServerRunning = server.listen(QHostAddress::LocalHost, mServerPort);
+        if (mServerRunning) {
+            break;
+        }
+        mServerPort += 1;
+    }
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp]: since there are two magic-number constants in this snippet (default value of server port and ergonomic value 8), might be a good idea to pull this out into a separate function, and then you can use `return` instead of `break`, and provide a failure-case return value after the loop, which will clarify the logic. this would be another argument for using only port to indicate the server status, since you can then easily just manage the one variable instead of two:

```cpp
int tryFindOpenServerPort()
{
    int const startPort = 12344;
    QWebSocketServer server(...);
    for (int port = startPort; port < startPort + 8; ++port) {
        if (server.listen(...)) {
            return port;
        }
    }
    return -1; // failure
}
```

**Comment by brianlheim** [comment]
overall this is a really elegant solution to the problem, thanks for tackling it!

File: editors/sc-ide/core/main.hpp [hunk 9]
```diff
@@ -33,6 +34,8 @@
 #include "settings/manager.hpp"
 #include "../widgets/style/style.hpp"
 
+static void findOpenPort(QWebSocketServer& server);
```
Comment (brianlheim) [inline editors/sc-ide/core/main.hpp]: don't put this in the header. headers are for definitions that should be shared; also, a `static` function should [almost?] never appear in a header, because then its definition will be placed in every TU that includes this header. just move the definition above `main`, or put this declaration above main

File: editors/sc-ide/widgets/help_browser.cpp [hunk 10]
```diff
@@ -120,6 +120,18 @@ HelpBrowser::HelpBrowser( QWidget * parent ):
     setFocusProxy(mWebView);
 }
 
+void HelpBrowser::setServerPort(int serverPort)
+{
+    mServerPort = serverPort;
+}
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp]: in the future you can define things like this inline in the class definition, since the implementation is trivial and one-line:

```cpp
bool helpBrowserHasFocus() const;
void setServerPort(int serverPort) { mServerPort = serverPort; }
```

i'd rather have that than 5 lines in the cpp file

File: editors/sc-ide/widgets/help_browser.cpp [hunk 11]
```diff
@@ -120,6 +120,18 @@ HelpBrowser::HelpBrowser( QWidget * parent ):
...
+
+void HelpBrowser::onPageLoad()
+{
+    if (mServerPort) {
```
Comment (brianlheim) [inline editors/sc-ide/widgets/help_browser.cpp]: personal style gripe -- I really don't like implicitly converting int (or anything) to bool in a condition. if the type of the object isn't obvious, you have to look it up to check the logic, and it also doesn't work semantically, for me anyway. would rather see this as `mServerPort != 0`. don't need to change it now, though, there are more important things in this PR

File: editors/sc-ide/core/main.cpp [hunk 12]
```diff
@@ -135,24 +136,39 @@ int main( int argc, char *argv[] )
...
+
+        // setup comm channel
+        WebSocketClientWrapper clientWrapper(&server);
+        QWebChannel channel;
+        QObject::connect(&clientWrapper, &WebSocketClientWrapper::clientConnected,
+                         &channel, &QWebChannel::connectTo);
+
+        // publish IDE interface
+        IDEWebChannelWrapper ideWrapper{browser};
+        channel.registerObject("IDE", &ideWrapper);
```
[the remark this answers is not in the document]
Comment (snappizz) [reply editors/sc-ide/core/main.cpp]: ehh i'm not on board with that, looks pretty weird. how about setting them as members of `HelpBrowser` instead?

[the remark this answers is not in the document]
Comment (brianlheim) [reply editors/sc-ide/core/main.cpp]: making them members means you now need to manage extra state (i.e. are these objects default-constructed and therefore invalid, or valid; maybe even need to write those default constructors an and state accessors). this goes against RAII and is not idiomatic C++. it's not worth it when you could be much clearer by adding one line here. besides, logically these objects do not really belong to the help browser if it can be constructed without them. there could be some sort of RAII wrapper that encapsulates this logic but I would rather be explicit about that than put it in a logically distinct object.

[the remark this answers is not in the document]
Comment (snappizz) [reply editors/sc-ide/core/main.cpp]: well alright -- but for the record, i really dislike the two copies of `return app.exec()`!

**Comment by snappizz** [comment]
this is too risky / not important enough for the 3.10.2 hotfix, so postponing until 3.10.3.

**Comment by madskjeldgaard** [comment]
Hi Snapizz. FYI: Following the link to the tree of this commit, the fork repo seems to contain a videopoker advertisement https://github.com/snappizz/supercollider/tree/topic/webchannel2

That said, the statement may hold true: SuperCollider is the ultimate videopoker experience. 

Skærmbillede 2019-05-13 kl  08 33 38

**Comment by snappizz** [comment]
ok

**Comment by snappizz** [comment]
ready for review!

**Comment by snappizz** [comment]
wow, i'm dumb. we don't actually need to do this sequential port search nonsense, since we can just leave off the `port` argument to `QWebSocketServer::listen` and it will automatically find us an open port.

**Comment by brianlheim** [comment]
oh nice! not dumb, i didn't know about that either.

**Comment by escuta** [comment]
Hello!

I tried to build SC with this pull request in the hope of being able to run SCDoc help from emacs. Unfortunately the SCDoc window still freezes. I'll write the steps I took in case I made a mistake:

Unistalled the supercollider
In the supercollider git directory:
git fetch origin pull/4267/head:mytestbranch 
git checkout mytestbranch
make
make install
ldconfig

When i run sclang on the command line, I can open the SCDoc once with: HelpBrowser.instance
If I close the window however and attempt to run HelpBrowser.instance again, the opened window freezes.

Running HelpBrowser.openHelpFor("Blip") freezes on first attempt (without having first run HelpBrowser.instance)

My laptop is running Ubuntu 18.04.2 LTS. If relevant, qmake --version gives:
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

**Comment by escuta** [comment]
The solution for me was to upgrade to Ubuntu 18.10 from the long-term-support 18.04. This comes with Qt version 5.11.1. Everything working now with this version.

**Comment by adcxyz** [comment]
just tested building with this on macOS 10.13, copied the app, 
both instances open, help browser works fine in both - yay!

**Comment by snappizz** [comment]
@escuta sorry for the late reply. strange that it seems to work with qt 5.11 and not with qt 5.9, since i don't think i've touched features that change across features much. maybe your initial `make install` didn't really install, and the second time around the installation did take effect?

**Comment by patrickdupuis** [comment]
Tested on Fedora 30 using Qt 5.12. Seems to work fine.

**Comment by escuta** [comment]
Thanks Nathan. I'm away from my computer for a week or so. I'll check again, but problems started to occur with a recent install on my desktop machine. Will give details laterEnviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De : Nathan Ho <notifications@github.com> Data: 04/07/2019  04:09  (GMT-03:00) Para: supercollider/supercollider <supercollider@noreply.github.com> Cc: "Escuta.org" <mott@escuta.org>, Mention <mention@noreply.github.com> Assunto: Re: [supercollider/supercollider] scide: Find an open port for WebSocket communication with SCDoc rather than hardcoding port 12344 (#4267) @escuta sorry for the late reply. strange that it seems to work with qt 5.11 and not with qt 5.9, since i don't think i've touched features that change across features much. maybe your initial make install didn't really install, and the second time around the installation did take effect?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/supercollider/supercollider/pull/4267?email_source=notifications\u0026email_token=AD6FS5HZVIWAZUHRIEC2KDDP5WOZNA5CNFSM4GROSEA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZGRB3I#issuecomment-508367085",
"url": "https://github.com/supercollider/supercollider/pull/4267?email_source=notifications\u0026email_token=AD6FS5HZVIWAZUHRIEC2KDDP5WOZNA5CNFSM4GROSEA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZGRB3I#issuecomment-508367085",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

File: editors/sc-ide/core/main.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply editors/sc-ide/core/main.cpp]: revisiting this -- one way to clean this a bit would be by creating a small wrapper class with pointers for services that are only valid if the server listens. the design is fairly straightforward IMO and encapsulates this logic well. dunno what you think.

```cpp
// in main.cpp
class HelpBrowserWebSocketServices {

public:
    HelpBrowserWebSocketServices(HelpBrowser* browser) :
    {
        m_server = new QWebSocketServer("SCIDE HelpBrowser Server", QWebSocketServer::NonSecureMode);
        if (m_server->listen(QHostAddress::LocalHost)) {
            browser->setServerPort(m_server->serverPort());

            // setup comm channel
            m_clientWrapper = new WebSocketClientWrapper(m_server);
            m_channel = new QWebChannel();
            QObject::connect(m_clientWrapper, &WebSocketClientWrapper::clientConnected, m_channel, &QWebChannel::connectTo);

            // publish IDE interface
            m_ideWrapper = new IDEWebChannelWrapper(browser);
            m_channel.registerObject("IDE", m_ideWrapper);
        } else {
            qWarning("Failed to set up help browser web socket.");
            // [don't take up heap space with a useless object]
            delete m_server;
            m_server = nullptr;
        }
    }

    ~HelpBrowserWebSocketServices()
    {
        // [delete on nullptr is valid and no-op]
        delete m_server;
        delete m_clientWrapper;
        delete m_channel;
        delete m_ideWrapper;
    }

private:
    // non-null only if server listens successfully
    QWebSocketServer* m_server;
    WebSocketClientWrapper* m_clientWrapper;
    QWebChannel* m_channel;
    IDEWebChannelWrapper* m_ideWrapper;
};
```

then this part becomes:

```cpp
    // line 130
    if (startInterpreter)
        main->scProcess()->startLanguage();

    HelpBrowserWebSocketServices services(win->helpBrowserDocklet()->browser());
    return app.exec();
```

[the remark this answers is not in the document]
Comment (brianlheim) [reply editors/sc-ide/core/main.cpp]: this would also make things cleaner in #4328

**Comment by snappizz** [comment]
thanks for the feedback @brianlheim. that sounds like a good idea, although i'll probably put that class along with the rest of the help browser code rather than dumping it in main.cpp

realizing now that this PR has some potential conflicts with #4328 -- i believe that should be reviewed and merged first.

**Comment by brianlheim** [comment]
> realizing now that this PR has some potential conflicts with #4328 -- i believe that should be reviewed and merged first.

Sgtm! will review ASAP

**Comment by brianlheim** [comment]
@snappizz I merged 4328, please fix conflicts here when you have time!

**Comment by brianlheim** [comment]
At @snappizz 's request I am taking over this PR and making the changes I requested.

**Comment by brianlheim** [comment]
Rebased to latest 3.10. Tested this with SC_QT_WEBENGINE both On and Off, works fine. (Hope you don't mind the force-push @snappizz)

**Comment by snappizz** [comment]
thanks @brianlheim ! that's perfect, and everything runs fine. (i can't technically approve my own pull request)
