### PR TITLE
Escape quotes in strings sent from SCIDE to lang

### LINKED ISSUE #1036: SCIDE needs to escape quotes in strings submitted to "openHelpFor"
I accidentally had a block of code selected when I hit ctrl-D to open the help browser (first time in the session). The browser window opened and said "Sending request..." but it never got as far as scanning the help files because:

```
ERROR: syntax error, unexpected NAME, expecting ')'
  in file 'selected text'
  line 1 char 43:

  HelpBrowser.openHelpFor("w = Window("window name", Rect(600, 200, 300, 120));
z = EZSlider(w,
    bounds: Rect(5, 5, 290, 20),
    label: "freq",
    controlSpec: [110, 880, \exp],  // short form OK
    action: { |view| ~sound.set(\freq, view.value) },
    i
                                       ^^^^^^
-----------------------------------
ERROR: Command line parse failed
```

SCIDE plugs in the entire string without escaping the quote marks in it.

User impact is: If SCDoc hasn't been initialized, the help browser is useless without at least recompiling the class library. In my case, I did recompile, but the help browser was still non-functional. I had to quit SCIDE and relaunch.

### PR DESCRIPTION
**Pull request by brianlheim**
Fixes #1036, tested and works (on macOS 10.13 high sierra).

## Reproducer

1. Start scide.
2. Type the line `"broken`
3. Select-all, and Cmd-D (to search documentation) or Cmd-U (to look up references).

## Old behavior

Errors:

```
ERROR: syntax error, unexpected NAME, expecting ')'
  in interpreted text
  line 1 char 32:

  HelpBrowser.openHelpFor(""broken") 
                            ^^^^^^
-----------------------------------
ERROR: Command line parse failed
ERROR: syntax error, unexpected NAME, expecting ')'
  in interpreted text
  line 1 char 88:

  ScIDE.request("{ec39ccb4-c981-43ac-a72e-a75439af6b6c}",'findReferencesToSymbol',""broken") 
                                                                                    ^^^^^^
-----------------------------------
ERROR: Command line parse failed
```

Also freezes the help browser.

## New behavior

Works without error/complaint.

## Addendum

I noticed similar opportunities for this issue to arise in other IDEs (search result at the end of this post), but I think this is more pressing/issue-worthy because (a) the IDE has widest usage and (b) this issue actually causes a major freeze. I am not sure if it does in other contexts. Since I'm not a user of any other SC environments, I haven't changed any of those files.

```
[brianheim@BrianMBP supercollider]$ rg openHelpFor
HelpSource/Classes/HelpBrowser.schelp
28:method:: openHelpFor
40:method:: openHelpForMethod

SCClassLibrary/DefaultLibrary/Main.sc
119:		HelpBrowser.openHelpFor(this.getCurrentSelection);

editors/scel/el/sclang-help.el
628:      (sclang-eval-string (sclang-format "HelpBrowser.openHelpFor(%o)" topic))

editors/sced/sced/WindowHelper.py
289:        self.__lang.evaluate("HelpBrowser.openHelpFor(\"" + text + "\");")

editors/sced/sced3/supercollider.py
527:        cmd = 'HelpBrowser.openHelpFor(\"' + text + '\");'

editors/sc-ide/widgets/help_browser.cpp
187:    QString code = QStringLiteral("HelpBrowser.openHelpFor(\"%1\")").arg(escaped);
193:    QString code = QStringLiteral("HelpBrowser.openHelpForMethod( %1.findMethod(\\%2) )").arg(className, methodName);

editors/scvim/ftplugin/supercollider.vim
244:  call SendToSCSilent('HelpBrowser.openHelpFor("' . a:subject . '");')

SCClassLibrary/Common/Core/Kernel.sc
517:		HelpBrowser.openHelpForMethod(this);

SCClassLibrary/Common/Quarks/Quark.sc
277:			^HelpBrowser.openHelpFor(p);

editors/sced/scedwin/py/WindowHelper.py
307:        self.__lang.evaluate("HelpBrowser.openHelpFor(\"" + text + "\");")

SCClassLibrary/Common/GUI/tools/HelpBrowser.sc
59:	*openHelpFor {|text|
66:	*openHelpForMethod {|method|

SCClassLibrary/Common/GUI/PlusGUI/Collections/StringPlusGUI.sc
94:			HelpBrowser.openHelpFor(this);
[brianheim@BrianMBP supercollider]$ rg gotoHelpFor
editors/sc-ide/core/main.cpp
292:    helpDock->browser()->gotoHelpFor(symbol);
300:    helpDock->browser()->gotoHelpForMethod(className, methodName);

editors/sc-ide/widgets/help_browser.cpp
183:void HelpBrowser::gotoHelpFor( const QString & symbol )
192:void HelpBrowser::gotoHelpForMethod( const QString & className, const QString & methodName )

editors/sc-ide/widgets/main_window.cpp
1612:    mHelpBrowserDocklet->browser()->gotoHelpFor("Guides/SCIde");

editors/sc-ide/widgets/help_browser.hpp
99:    void gotoHelpFor( const QString & );
100:    void gotoHelpForMethod( const QString & className, const QString & methodName );

editors/sc-ide/widgets/code_editor/autocompleter.cpp
1312:    helpDock->browser()->gotoHelpFor(symbol);
```

### CODE REVIEW

**Comment by brianlheim** [comment]
I milestoned this 3.9.1, would rather not shove it into 3.9.0.

File: editors/sc-ide/widgets/help_browser.cpp [hunk 1]
```diff
@@ -182,13 +182,22 @@ void HelpBrowser::closeDocument()
...
     sendRequest(code);
 }
 
 void HelpBrowser::gotoHelpForMethod( const QString & className, const QString & methodName )
 {
-    QString code = QStringLiteral("HelpBrowser.openHelpForMethod( %1.findMethod(\\%2) )").arg(className, methodName);
+    QString escapedClass{className};
+    QString escapedMethod{methodName};
+    escapedClass.replace('\"', "\\\"");
+    escapedMethod.replace('\"', "\\\"");
```
Comment (snappizz) [inline editors/sc-ide/widgets/help_browser.cpp]: small amount of duplicated code here -- how about making this into a function?

Comment (brianlheim) [reply editors/sc-ide/widgets/help_browser.cpp]: good point, I've done that now. :)
