### PR TITLE
Only the main window should received a signal when cmd+q is pressed o…

### LINKED ISSUE #4300: IDE doesn't quit on macOS
## Environment

* SuperCollider version: develop 0a601d50c
* Operating system: macOS 10.13.6
* Other details (Qt version, audio driver, etc.): QT 5.12.0 (homebrew), build config RelWithDebInfo, Debug

## Steps to reproduce
Open SuperCollider (IDE).
Quit the IDE (either via top menu or cmd-q)

## Expected vs. actual behavior

Expected: sclang quits, IDE closes (quits) as well.

Actual: sclang quits, but the IDE stays open. _Cmd-q doesn't work._

The behavior differs slightly whether the attempt to close SC was done using the keyboard shortcut or the top menu:
- if it was done using the top menu, then after the interpreter quits the menu still has the option to quit SuperCollider. The menu still works and can quit the IDE (on the second attempt)
- if it was done using cmd-q, then there is no option in the menu to quit the IDE. In that case the IDE can be quit by pressing the close window icon ("x") in the top left corner.

(no) error message after attempting to close the IDE:
```
main: waiting for input thread to join...
main: quitting...
cleaning up OSC
Interpreter has quit. [Exit code: 0]
```
After this the IDE stays open.

### PR DESCRIPTION
**Pull request by geoffroymontel**
## Purpose and Motivation

Fixes #4300.

## Types of changes
- Bug fix

## Description

Some users reported that in the develop branch, one could not quit the IDE with CMD+Q anymore (see #4300).
I could reproduce that on my local machine (Mac OS 10.12, QT 5.13).
I first thought it was due to a change in the code base since 3.10.2 as I could not reproduce the problem with the release.
I tried recompiling releases tags 3.10.2, then 3.10.1 and 3.10.0 and I could still reproduce the problem with the most recent version of QT installed with brew (5.13).
I put a lot of traces and I realized that when pressing cmd+q, `MainWindow::onQuit` was not called. Instead, `ScProcess::toggleRunning` was called.
I then remembered reading in [QT MacOS issues page](https://doc.qt.io/qt-5/macos-issues.html#) that Qt automagically handles certain actions by their texts. Basically, if you add an action with the word "Quit" or "Exit" in it, QT will register them to cmd+Q. I would have thought that it would be only for menu item actions, or at least for QWidgets, but it seems that, at least for recent QT versions, it also applies to `QProcess` or plain `QObject`.
QT doc recommends to action action roles to bypass the magical interpretation of the action based on its text.
So the solution was disable reacting to cmd+q by adding a `QAction::NoRole` to the `Boot or Quit Interpreter` and `Boot or Quit Server` actions, and adding a `QAction::QuitRole` to clearly define that the callback shall be called on MainWindow, whatever the translation of the `Quit` is, when pressing cmd+q.

## To-do list

- [X] All tests are passing
- [X] This PR is ready for review
- [X] Tested on Windows
- [X] Tested on Linux

### CODE REVIEW

**Comment by geoffroymontel** [comment]
Thanks for testing James !

**Comment by patrickdupuis** [comment]
On Fedora 30 with Qt 5.12:
- Ctrl+Q quits the IDE
- When `Window.new.front`, Ctrl+Q does nothing

**Comment by geoffroymontel** [comment]
Thanks Patrick for testing on Linux !

File: editors/sc-ide/core/sc_process.cpp [hunk 1]
```diff
@@ -63,6 +63,7 @@ void ScProcess::prepareActions(Settings::Manager* settings) {
     const QString interpreterCategory(tr("Interpreter"));
 
     mActions[ToggleRunning] = action = new QAction(tr("Boot or Quit Interpreter"), this);
+    action->setMenuRole(QAction::NoRole); // to prevent the action from being fired with cmd+q on macosx
```
Comment (snappizz) [inline editors/sc-ide/core/sc_process.cpp]: idea for a more explicit comment:

> the default QAction::TextHeuristicRole incorrectly detects a quit role on macOS

Comment (geoffroymontel) [reply editors/sc-ide/core/sc_process.cpp]: I like that comment better, thanks.

**Comment by geoffroymontel** [comment]
@snappizz I changed the three comments in a new commit, hope it's better now

**Comment by snappizz** [comment]
aside from the formatting issues mentioned above this looks good to me, and i'll merge once they're fixed. thanks @geoffroymontel!!

**Comment by geoffroymontel** [comment]
@brianlheim I was blindly trusting clang-format, my bad !
I submitted a fix.
Please squash the commits when you merge ;)

**Comment by dyfer** [comment]
Sorry I didn't jump on this before - thanks @geoffroymontel for this fix! On macOS 10.13 it does work for the IDE. 

However, there's I can still experience crash when Interpreter is in focus and `cmd+q` is pressed, as described in #3824. Is this at all related?

**Comment by geoffroymontel** [comment]
Hey @dyfer ! I can have a look at this in the near future ! I guess that's because the default behaviour of macOS is to kill the process when cmd+q is pressed.
