### PR TITLE
[IDE] fix shift-enter behavior in IDE

### LINKED ISSUE #3877: Shift + Return deletes highlighted code in Help browser
Shift + Return doesn't execute. It erases text

### PR DESCRIPTION
**Pull request by brianlheim**
Purpose and Motivation
----------------------

shift-enter needs to be intercepted at the JS level and call a slot on a
C++ object in order to evaluate a line. This shortcut isn't propagated
normally. This commit adds QWebChannel and QWebSockets to the dependencies
and uses them to allow JS to request the help browser C++ code to evaluate
a line.

Also some changes to JS code and SCDoc renderer code

Note that the WebChannel should only be loaded on pages with code to
execute.

The WebChannel is constructed in the IDE's main() and then the help browser
is published to it. On the JS side, evaluateSelection(false) is called
whenever shift-enter on a code snippet is detected.

Note that I based this off @htor's other branch, since that will be
merged soon and since I needed to interface with some of the codemirror code.

Comments on JS style/design welcome, I dunno what I'm doing there.

Fixes #3877.

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

Checklist
---------

- [x] All tests are passing

- [x] If necessary, new tests were created to address changes in PR (and tests are passing)

- [x] Updated documentation, if necessary

- [x] This PR is ready for review

Remaining Work
------------

- [x] ~May need to update guides since new libs are required (QWebChannel, QWebSockets).~ added qt5xxwebsockets to lists of dependencies in travis and readmes.
- [x] ~Need to check on other platforms (I don't anticipate any problems there, though)~ reportedly works fine on linux.
- [x] ~Update scdoc_version?~ updated
- [x] ~May need to credit code in the new files, which were taken with very minor edits from the Qt WebChannel Standalone Example (https://doc.qt.io/qt-5/qtwebchannel-standalone-example.html)~ included BSD license which is compatible with GPL3.

Also note that QWebChannel may open up an easy/convenient way for us to
translate configuration settings from the IDE to the browser via the
existing Qt signal/slot interface. I see no reason not to do this.

### CODE REVIEW

**Comment by brianlheim** [comment]
For the actual PR:

https://github.com/brianlheim/supercollider/compare/brianlheim:htor-topic/docs-editor...topic/shift-enter-eval

Right now it's just one commit so also https://github.com/supercollider/supercollider/pull/3960/commits/30edd158bf15231c99d247e5b73dd596fa96b38c works.

After or before @htor's PR is merged I assume it will be on 3.10, at which point I'll rebase this. (Basically, Everything Will Be OK)

File: HelpSource/editor.js [hunk 1]
```diff
@@ -129,7 +129,13 @@ const selectRegion = (options = { flash: true }) => {
     }
 }
 
-/* returns the code selection or line */
+const evalLine = () => {
+    // Call to C++ help browser. `evaluateSelection(false)` evaluates a line. It will execute
```
Comment (htor) [inline HelpSource/editor.js]: maybe a little verbose comment, perhaps something like "call c++ evaluation function in order to capture shift-enter" would be fine. the comment should go on top of the function signature.

File: HelpSource/scdoc.js [hunk 2]
```diff
@@ -193,3 +193,35 @@ function fixTOC() {
...
+        });
+    }
+}
+
+// Fixes the TOC and sets up the QWebChannel for communicating back to C++ code
+function didLoadRenderedWindow() {
+    fixTOC();
+
+    // Check that webchannel.js was loaded
+    if(typeof QWebChannel != "undefined") {
```
Comment (htor) [inline HelpSource/scdoc.js]: `!==` is preferred in js instead of `!=` by convention. because less bugs and weird behaviour.

File: editors/sc-ide/core/main.cpp [hunk 3]
```diff
@@ -124,6 +127,22 @@ int main( int argc, char *argv[] )
     if (startInterpreter)
         main->scProcess()->startLanguage();
 
+    // setup HelpBrowser server
+    QWebSocketServer server("SCIDE HelpBrowser Server", QWebSocketServer::NonSecureMode);
+    if (!server.listen(QHostAddress::LocalHost, 12345)) {
```
Comment (htor) [inline editors/sc-ide/core/main.cpp]: should we have another port number or is this going to be fine?

Comment (brianlheim) [reply editors/sc-ide/core/main.cpp]: A question I have as well!

**Comment by htor** [comment]
tested on macos and shift-enter works!

but, there are alot of warnings now when i start sc. possibly related to qwebchannel stuff:

```
~/Projects/supercollider/build2 $ ./Install/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider 
Property 'modal'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'windowModality'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'enabled'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'geometry'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameGeometry'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'normalGeometry'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'x'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'y'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'pos'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'frameSize'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
Property 'size'' of object 'ScIDE::HelpBrowser' has no notify signal and is not constant, value updates in HTML will be broken!
... (many more)
```

File: editors/sc-ide/core/main.cpp (hunk 3 above)
Comment (miczac) [reply editors/sc-ide/core/main.cpp]: pick something in the range of 12323 and 12344 for instance.
based on: 
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt
12345 should be fine though: LocalHost is apparently hard-coded anyway and 12345 is not in the well-known ports.
Only an overzealous security tool (e.g. on Windows) might be irritated since there are trojans out-there using 12345. (https://www.speedguide.net/port.php?port=12345)

**Comment by brianlheim** [comment]
@htor Addressed your comments, thanks! I noticed (and forgot about) the warnings. I solved that by creating a new wrapper that will serve as the singular encapsulated point of comm between the help browser and the IDE. Given the discussion we've had around extending the use of this WebChannel and given that it eliminates the warnings, I think that's warranted.

File: SCClassLibrary/SCDoc/SCDocRenderer.sc [hunk 4]
```diff
@@ -244,10 +246,10 @@ SCDocHTMLRenderer {
...
 		<< "<script src='" << baseDir << "/scdoc.js' type='text/javascript'></script>\n"
 		<< "<script src='" << baseDir << "/docmap.js' type='text/javascript'></script>\n" // FIXME: remove?
-		<< "</head>\n";
-
-		stream
-		<< "<body onload='fixTOC()'>\n";
+		// QWebChannel access
+		<< "<script src='qrc:///qtwebchannel/qwebchannel.js' type='text/javascript'></script>\n"
+		<< "</head>\n"
+		<< "<body onload='didLoadRenderedWindow()'>\n";
```
Comment (snappizz) [inline SCClassLibrary/SCDoc/SCDocRenderer.sc]: this is more of a problem with the existing code, but `<body onload="...">` is really old hat. it's better to leave `fixTOC` be, and then write this in the JS:

```
$(function () {
    if (typeof QWebChannel !== "undefined") {
        setUpWebChannel();
    }
});
```

File: HelpSource/scdoc.js [hunk 5]
```diff
@@ -193,3 +193,35 @@ function fixTOC() {
         set_up_toc();
     }
 }
+
+// Set up a QWebChannel for communicating with C++ IDE objects. The main app publishes a handle
+// to IDE functionality at "IDE" which is made globally available here after the page and
+// WebSocket have loaded.
+function setUpWebChannel() {
+    if (location.search != "")
+        var baseUrl = (/[?&]webChannelBaseUrl=([A-Za-z0-9\-:/\.]+)/.exec(location.search)[1]);
```
[the remark this answers is not in the document]
Comment (htor) [reply HelpSource/scdoc.js]: just drop the if-part all together! it's never going to be used since we hardcoded `ws://localhost:12345` in the server anyway. (it allows overriding the websocket url by setting a query string `?webChannelBaseUrl=...`.

File: SCClassLibrary/SCDoc/SCDocRenderer.sc (hunk 4 above)
Comment (brianlheim) [reply SCClassLibrary/SCDoc/SCDocRenderer.sc]: OK, where should I write that?

File: HelpSource/scdoc.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (brianlheim) [reply HelpSource/scdoc.js]: done

File: SCClassLibrary/SCDoc/SCDocRenderer.sc (hunk 4 above)
Comment (snappizz) [reply SCClassLibrary/SCDoc/SCDocRenderer.sc]: it should go in `scdoc.js`, at the top level. `<body onload="fixTOC()">`, and the `fixTOC()` function itself, should stay as is.

**Comment by brianlheim** [comment]
I've updated the top PR comment with new info, AFAICT all remaining items are taken care of now.

**Comment by brianlheim** [comment]
This should be ready to go!

File: editors/sc-ide/CMakeLists.txt [hunk 6]
```diff
@@ -101,6 +112,10 @@ set ( ide_moc_hdr
     widgets/util/color_widget.hpp
     widgets/util/docklet.hpp
     widgets/util/volume_widget.hpp
+    widgets/util/volume_widget.hpp
```
Comment (patrickdupuis) [inline editors/sc-ide/CMakeLists.txt]: There's a repeated element in this list.

Comment (brianlheim) [reply editors/sc-ide/CMakeLists.txt]: fixed

**Comment by brianlheim** [comment]
This is tested and works on Windows
